### ISSUE TITLE
Wacom device is not recognized on Yoga 260.

### ISSUE THREAD

**Issue by rainwoodman** [linuxwacom/libwacom#1]
[sysinfo.h8i2nOYbjH.tar.gz](https://github.com/linuxwacom/libwacom/files/831681/sysinfo.h8i2nOYbjH.tar.gz)

On a Yoga 260, GNOME issues device not recognized error. sysinfo.sh output is attached.

**Comment by jigpu** [comment]
Apologies for the delay in replying. This should be fixed by 3b37fe1 which will be part of libwacom 0.25
