### ISSUE TITLE
Huion H610 Pro evtest output

### ISSUE THREAD

**Issue by ozeszty** [linuxwacom/libwacom#13]
I saw FIXME comment in libwacom/data/huion-h610-pro.tablet, so here's `evtest` output for old Huion H610 Pro (2048 pressure levels). Values seems to match, if you need any other testing, feel free to let me know.

> Input driver version is 1.0.1
> Input device ID: bus 0x3 vendor 0x256c product 0x6e version 0x111
> Input device name: "HUION PenTablet Pad"
> Supported events:
>   Event type 0 (EV_SYN)
>   Event type 1 (EV_KEY)
>     Event code 256 (BTN_0)
>     Event code 257 (BTN_1)
>     Event code 258 (BTN_2)
>     Event code 259 (BTN_3)
>     Event code 260 (BTN_4)
>     Event code 261 (BTN_5)
>     Event code 262 (BTN_6)
>     Event code 263 (BTN_7)
>   Event type 4 (EV_MSC)
>     Event code 4 (MSC_SCAN)
> Properties:

**Comment by jigpu** [comment]
The order of the codes listed in the tablet file matters. Can you verify that the buttons send BTN_0 through BTN_7 in that order from top to bottom? If it does, then we can safely remove the FIXME.

Thanks for looking into this!

**Comment by ozeszty** [comment]
I pressed all the buttons from top to bottom and, I think, there were no inconsistencies in `evtest` output. I should be able to confirm it over the weekend.

Happy to help.

**Comment by ozeszty** [comment]
I just tested it and the order is correct. All buttons are working correctly now (libwacom-0.28-3.fc27).
