### ISSUE TITLE
Install the generated udev rules as part of the install process

### ISSUE THREAD

**Issue by whot** [linuxwacom/libwacom#144]
Pretty sure anyone who needs to install a new libwacom also needs to update the udev rules to ensure the correct `ID_INPUT_TABLET`/`ID_INPUT_TABLET_PAD` tagging. Without that we may have issues where users manually install but then the pad isn't tagged correctly (this would affect libinput, not the xf86-input-wacom driver).

So let's fix this by just installing the udev rules, they're there for a reason after all.

**Comment by jigpu** [comment]
Sounds like this would be a solution to https://github.com/NixOS/nixpkgs/issues/52490
