### ISSUE TITLE
Add support for HP Spectre x360 (Elan i2c:04f3:22e2)

### ISSUE THREAD

**Issue by jigpu** [linuxwacom/libwacom#15]
See https://github.com/linuxwacom/wacom-hid-descriptors/issues/21

**Comment by brauliobo** [comment]
have put this file at `/usr/share/libwacom` and `xsetwacom --list devices` still doesn't return anything. My laptop is a HP x360 Convertible 15-bq100

**Comment by brauliobo** [comment]
where can I find the device id of mine?

**Comment by brauliobo** [comment]
sorry, related to https://github.com/linuxwacom/wacom-hid-descriptors/issues/12,

**Comment by jigpu** [comment]
Looking at your post in the other issue, it looks like the ID is i2c:04F3:2537. Other necessary information should be in the sysinfo.sh output I requested. Please open a new issue here requesting support for your particular HP system.

**Comment by whot** [comment]
Note that neither the kernel nor the xorg driver use libwacom. So adding the libwacom file is only for the benefit of GNOME's control-center and, to a lesser extent, libinput. It does not have any effect on the xsetwacom output.

**Comment by jigpu** [comment]
@brauliobo I opened an issue for your particular sensor at https://github.com/linuxwacom/libwacom/issues/21 and sent a tablet definition to the linuxwacom-devel mailinglist.

**Comment by whot** [comment]
Closing, see commit e7d4994086498005ef6b76895c0913c69ddcacf
