### ISSUE TITLE
libwacom-1.0.tar.bz2 install fails due to duplicate data/foo directory

### ISSUE THREAD

**Issue by d4ddi0** [linuxwacom/libwacom#157]
Building from source on gentoo linux fails due to the existence of data/foo, which contains .tablet files that duplicate those in data

WORKAROUND: deleting the data/foo directory allows the build to proceed.

See the gentoo bug report here: https://bugs.gentoo.org/693434
And a build log here: https://bugs.gentoo.org/attachment.cgi?id=589006

**Comment by whot** [comment]
whoops. fwiw, another workaround should also be to build with meson instead of autotools.

Fixed now with the 1.1 release I just posted, apologies for the mess.
