### ISSUE TITLE
Libwacom literally snapped half of my software out of my arch setup, desktop included.

### ISSUE THREAD

**Issue by warriormaster12** [linuxwacom/libwacom#159]
How is this possible that when you either install or uninstall your library that it wants to delete also most of my kde software? 

The whole thing literally requests that I should uninstall my whole DE if I also want to uninstall the library.
I'm sorry if this will sound rude but seriously WTF.

**Comment by jigpu** [comment]
Can you please provide some more information about what distribution you are using, the command you're trying to run, and the list of packages it wants to remove? Package management and dependencies are largely defined by distros -- not us -- but we can definitely take a closer look.

**Comment by warriormaster12** [comment]
Distro:Arch linux
Package Manager: Pamac 
Packages requested to be removed when installing or uninstalling the library 
`To remove (156):
  accounts-qml-module         0.7-2                     extra
  appstream-qt                0.12.8-1                  extra
  attica                      5.62.0-1                  extra
  baloo                       5.62.0-1                  extra
  baloo-widgets               19.08.1-1                 extra
  bluedevil                   1:5.16.5-1                extra
  bluez-qt                    5.62.0-1                  extra
  breeze                      5.16.5-1                  extra
  breeze-gtk                  5.16.5-1                  extra
  discover                    5.16.5-1                  extra
  dolphin                     19.08.1-1                 extra
  drkonqi                     5.16.5-1                  extra
  flatpak                     1.4.2-1                   extra
  frameworkintegration        5.62.0-1                  extra
  kaccounts-integration       19.08.1-1                 extra
  kactivities                 5.62.0-1                  extra
  kactivities-stats           5.62.0-1                  extra
  kactivitymanagerd           5.16.5-1                  extra
  karchive                    5.62.0-1                  extra
  kauth                       5.62.0-1                  extra
  kbookmarks                  5.62.0-1                  extra
  kcm-wacomtablet             1:3.2.0-1                 community
  kcmutils                    5.62.0-1                  extra
  kcodecs                     5.62.0-1                  extra
  kcompletion                 5.62.0-1                  extra
  kconfig                     5.62.0-1                  extra
  kconfigwidgets              5.62.0-1                  extra
  kcoreaddons                 5.62.0-1                  extra
  kcrash                      5.62.0-1                  extra
  kdbusaddons                 5.62.0-1                  extra
  kde-cli-tools               5.16.5-1                  extra
  kde-gtk-config              5.16.5-1                  extra
  kdeclarative                5.62.0-1                  extra
  kdeconnect                  1.3.5-3                   community
  kdecoration                 5.16.5-1                  extra
  kded                        5.62.0-1                  extra
  kdelibs4support             5.62.0-2                  extra
  kdeplasma-addons            5.16.5-1                  extra
  kdesu                       5.62.0-1                  extra
  kdnssd                      5.62.0-1                  extra
  kemoticons                  5.62.0-1                  extra
  kfilemetadata               5.62.0-1                  extra
  kgamma5                     5.16.5-1                  extra
  kglobalaccel                5.62.0-1                  extra
  kguiaddons                  5.62.0-1                  extra
  kholidays                   1:5.62.0-1                extra
  khotkeys                    5.16.5-1                  extra
  ki18n                       5.62.0-1                  extra
  kiconthemes                 5.62.0-1                  extra
  kidletime                   5.62.0-1                  extra
  kinfocenter                 5.16.5-1                  extra
  kinit                       5.62.0-1                  extra
  kio                         5.62.1-1                  extra
  kio-extras                  19.08.1-1                 extra
  kirigami2                   5.62.0-1                  extra
  kitemmodels                 5.62.0-1                  extra
  kitemviews                  5.62.0-1                  extra
  kjobwidgets                 5.62.0-1                  extra
  kjs                         5.62.0-1                  extra
  kjsembed                    5.62.0-1                  extra
  kmenuedit                   5.16.5-1                  extra
  knetattach                  5.16.5-1                  extra
  knewstuff                   5.62.0-1                  extra
  knotifications              5.62.0-1                  extra
  knotifyconfig               5.62.0-1                  extra
  konsole                     19.08.1-1                 extra
  kpackage                    5.62.0-1                  extra
  kparts                      5.62.0-1                  extra
  kpeople                     5.62.0-1                  extra
  kpty                        5.62.0-1                  extra
  krunner                     5.62.0-1                  extra
  kscreen                     5.16.5-1                  extra
  kscreenlocker               5.16.5-1                  extra
  kservice                    5.62.0-1                  extra
  ksshaskpass                 5.16.5-1                  extra
  ksysguard                   5.16.5-1                  extra
  ktexteditor                 5.62.0-1                  extra
  ktextwidgets                5.62.0-1                  extra
  kunitconversion             5.62.0-1                  extra
  kwallet                     5.62.0-1                  extra
  kwallet-pam                 5.16.5-1                  extra
  kwayland                    5.62.0-1                  extra
  kwayland-integration        5.16.5-1                  extra
  kwidgetsaddons              5.62.0-1                  extra
  kwin                        5.16.5-2                  extra
  kwindowsystem               5.62.0-1                  extra
  kwrite                      19.08.1-1                 extra
  kwrited                     5.16.5-1                  extra
  kxmlgui                     5.62.0-1                  extra
  kxmlrpcclient               5.62.0-1                  extra
  latte-dock                  0.9.2-1                   community
  libaccounts-qt              1.15-2                    extra
  libdbusmenu-qt5             0.9.3+16.04.20160218-4    extra
  libinput                    1.14.1-1                  extra
  libkipi                     19.08.1-1                 extra
  libkscreen                  5.16.5-1                  extra
  libksysguard                5.16.5-1                  extra
  libwacom                    1.0-1                     extra
  milou                       5.16.5-1                  extra
  modemmanager-qt             5.62.0-1                  extra
  networkmanager-qt           5.62.0-1                  extra
  oxygen                      5.16.5-1                  extra
  phonon-qt5                  4.11.0-1                  extra
  phonon-qt5-gstreamer        4.10.0-1                  extra
  plasma-browser-integration  5.16.5-1                  extra
  plasma-desktop              5.16.5-1                  extra
  plasma-framework            5.62.0-1                  extra
  plasma-integration          5.16.5-1                  extra
  plasma-nm                   5.16.5-1                  extra
  plasma-pa                   5.16.5-1                  extra
  plasma-sdk                  5.16.5-1                  extra
  plasma-vault                5.16.5-1                  extra
  plasma-workspace            5.16.5-1                  extra
  polkit-kde-agent            5.16.5-1                  extra
  polkit-qt5                  0.113.0-1                 extra
  poppler-qt5                 0.80.0-1                  extra
  powerdevil                  5.16.5-1                  extra
  prison                      5.62.0-1                  extra
  purpose                     5.62.0-1                  extra
  qca                         2.2.1-2                   extra
  qqc2-desktop-style          5.62.0-1                  extra
  qt5-base                    5.13.1-2                  extra
  qt5-declarative             5.13.1-1                  extra
  qt5-graphicaleffects        5.13.1-1                  extra
  qt5-imageformats            5.13.1-1                  extra
  qt5-location                5.13.1-1                  extra
  qt5-multimedia              5.13.1-1                  extra
  qt5-quickcontrols           5.13.1-1                  extra
  qt5-quickcontrols2          5.13.1-1                  extra
  qt5-script                  5.13.1-1                  extra
  qt5-sensors                 5.13.1-1                  extra
  qt5-speech                  5.13.1-1                  extra
  qt5-svg                     5.13.1-1                  extra
  qt5-tools                   5.13.1-1                  extra
  qt5-webchannel              5.13.1-1                  extra
  qt5-webengine               5.13.1-2                  extra
  qt5-webkit                  5.212.0alpha3-4           extra
  qt5-x11extras               5.13.1-1                  extra
  sddm                        0.18.1-1                  extra
  sddm-kcm                    5.16.5-1                  extra
  signon-kwallet-extension    19.08.1-1                 extra
  signon-plugin-oauth2        0.24-2                    extra
  signon-ui                   0.17+20150611-2           extra
  signond                     8.60-1                    extra
  solid                       5.62.0-1                  extra
  sonnet                      5.62.0-1                  extra
  spectacle                   19.08.1-1                 extra
  syntax-highlighting         5.62.0-1                  extra
  systemsettings              5.16.5-1                  extra
  telegram-desktop            1.8.8-1                   community
  threadweaver                5.62.0-1                  extra
  user-manager                5.16.5-1                  extra
  xdg-desktop-portal          1.4.2-1                   extra
  xdg-desktop-portal-kde      5.16.5-1                  extra
  xf86-input-libinput         0.29.0-1                  extra
  xorg-server                 1.20.5-2                  extra
`

**Comment by warriormaster12** [comment]
Like why does it need telegram to be removed?

**Comment by whot** [comment]
libinput uses libwacom for some tablet bits. if you remove libinput, you're removing all the wayland compositors you have, including the xf86-input-libiput driver. Since that's the main X input driver it suggest to remove the X server. Removing that removes your KDE stuff because you don't need it without an X server. And so on and so forth until you end up with telegram removed.

This is normal for low-level system libraries, you cannot remove libwacom from most distributions because it's an integral part. And a fairly small part at that, I'm not sure why you want it removed to begin with.

and to answer the follow-up: libinput can be built without libwacom but you'll lose some tablet integration capabilities and your distribution has (wisely) chosen not to drop those.

**Comment by warriormaster12** [comment]
@whot the thing is that it did the same thing when you want to install it. The library wasn't originally installed on my system and when I did install it, it removed those upper mentioned packages.

**Comment by warriormaster12** [comment]
It wasn't by default installed on my distro

**Comment by whot** [comment]
quick test in an arch podman container shows that it's a dependency of libinput. Removing it with `pacman -Rsc libwacom` wants to basically remove everything, as expected. And while i"m not too familiar with pacman, `pacman -S libwacom` installs it, even though it's clearly already present.
So maybe you did have it installed already anyway? Either way, (re)installing it worked just fine.

Based on the above log there isn't really anything else I can tell you. libwacom is just a library and the packaging is handled by the Arch teams. But the behaviour is basically what i'd expect from trying to remove it. If this happens during install, it's either some weird bug or an issue with pacman. I suggest filing a ticket with Arch first to rule out the latter.

**Comment by warriormaster12** [comment]
Thanks for clarifying.
