### ISSUE TITLE
Support for XP-PEN 13.3v2

### ISSUE THREAD

**Issue by DanielJoyce** [linuxwacom/libwacom#172]
**Device name**

> XP-PEN 13.3 V2

**Device model identifier**

> Unknown

Previous saga here: https://github.com/DIGImend/digimend-kernel-drivers/issues/204

Something broke on the upgrade to 19.04 and now it doesn't work anymore, I get a weird device list when i run xinput

```
$ xinput 
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ELAN24EE:00 04F3:24EE                   	id=12	[slave  pointer  (2)]
⎜   ↳ DELL07E6:00 06CB:76AF Touchpad          	id=13	[slave  pointer  (2)]
⎜   ↳ PS/2 Synaptics TouchPad                 	id=18	[slave  pointer  (2)]
⎜   ↳ MX Anywhere 2 Mouse                     	id=20	[slave  pointer  (2)]
⎜   ↳ XP-PEN ARTIST 13.3 touch                	id=21	[slave  pointer  (2)]
⎜   ↳ XP-PEN ARTIST 13.3 stylus               	id=22	[slave  pointer  (2)]
⎜   ↳ XP-PEN ARTIST 13.3 Mouse touch          	id=23	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD: Integrate         	id=10	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD: Integrate         	id=11	[slave  keyboard (3)]
    ↳ Intel HID events                        	id=14	[slave  keyboard (3)]
    ↳ Intel HID 5 button array                	id=15	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=16	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=17	[slave  keyboard (3)]
    ↳ MX Anywhere 2 Keyboard  
```

My tablet doesn't support touch at all, and pad no longer shows.

hid-uclogic isn't loaded, so I don't think that's the problem as this device id is not recognized as uc logic. 

sys-info.sh dump:
[sysinfo.cEDPCoNzWB.tar.gz](https://github.com/linuxwacom/libwacom/files/3786960/sysinfo.cEDPCoNzWB.tar.gz)

**Comment by DanielJoyce** [comment]
Stylus works in gnome-wacom-settings, pressure works, calibration works, testing works, but no matter what I try, gnome-wacom won't load the template file and let me set the pad button keys

**Comment by whot** [comment]
something isn't right here. `sysinfo.sh` cannot find libevdev or libwacom, both of those are very unlikely to be missing on any normal system. And the dump includes a libwacom list for that device but we don't have a file for that device. Do you have a local one?

**Comment by DanielJoyce** [comment]
Yes I have a local one I put together. 

As for evdev or libwacom not showing up, I don't know. It's pop os based on Ubuntu. I can try digging around.

With the plethora of tablets coming out now it seems to me some flexible user space configuration is needed. I'm working on a userspace style config tool right now, in the vein of 'sc-controller' that makes it easy to explore hid events and map them to virtual devices. The plan is to eventually add a gui and wizard.

**Comment by DanielJoyce** [comment]
The kernel also subtly changed how it apparently reports the tablet. So under earlier kernels I could it to work by tweaking mappings and config. Under 5.x the kernel apparently changed some of the hid/evdev stuff and I can't convince libwacom it's a tablet just from config settings.

**Comment by whot** [comment]
fwiw, libwacom only cares about the `ID_INPUT_TABLET` property which is assigned by udev. And we ship udev rules to explicitly tag each supported device as such based on the vid/pid.

You can either add a custom ruleset to assign that tag but generally where the tablet files are in place and installed by libwacom proper, everything should JustWork.

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks
