### ISSUE TITLE
Pen oddities with X1 Yoga 4th-gen

### ISSUE THREAD

**Issue by expoqeteer** [linuxwacom/libwacom#173]
I have a Lenovo X1 Yoga 4th Generation.  The pen that comes with the laptop has a rocker switch on the side with two buttons.  The pen sort-of works and I'd like to get it completely working.  

What works:
- the pointer moves with the pen when the tip nears the screen
- things are selected/drawn/etc. when the tip touches the screen
- the upper side button works as a middle/right button (depending on the configuration in gnome-control-center

What doesn't work:
- the lower side button doesn't seem to do anything

Some system information:
- Fedora 30
- libwacom-0.33-1.fc30.x86_64

`/usr/share/libwacom/isdv4-51bf.tablet` contains:

    # this is for the Wacom pen + touchscreen as found in the Lenovo X1 Yoga 4th-gen
    
    [Device]
    Name=Wacom ISDv4 51BF
    ModelName=
    DeviceMatch=usb:056a:51bf
    Class=ISDV4
    Width=12
    Height=7
    IntegratedIn=Display;System

    [Features]
    Stylus=true
    Touch=true

`xinput list` returns:

    ⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
    ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
    ⎜   ↳ Wacom Pen and multitouch sensor Finger touch	id=9	[slave  pointer  (2)]
    ⎜   ↳ Wacom Pen and multitouch sensor Pen stylus	id=10	[slave  pointer  (2)]
    ⎜   ↳ SYNA8004:00 06CB:CD8B Touchpad          	id=13	[slave  pointer  (2)]
    ⎜   ↳ TPPS/2 ALPS TrackPoint                  	id=15	[slave  pointer  (2)]
    ⎜   ↳ Wacom Pen and multitouch sensor Pen eraser	id=17	[slave  pointer  (2)]
    ⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
        ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
        ↳ Power Button                            	id=6	[slave  keyboard (3)]
        ↳ Video Bus                               	id=7	[slave  keyboard (3)]
        ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
        ↳ Integrated Camera: Integrated C         	id=11	[slave  keyboard (3)]
        ↳ Integrated Camera: Integrated I         	id=12	[slave  keyboard (3)]
        ↳ AT Translated Set 2 keyboard            	id=14	[slave  keyboard (3)]
        ↳ ThinkPad Extra Buttons                  	id=16	[slave  keyboard (3)]

When I run `xinput test 10`, I can see `motion` events when the pen nears the screen and `button press 1` and `buton release ` events when the tip touches the screen.  When I press the upper barrel button, `button press 2` and `button release 2` events are show.  However, when I bring the pen in proximity and press the lower barrel button, no events -- of any kind -- are displayed.  `xinput test` stops emitting messages altogether.

This behavior occurs both with the stylus that came with the system, a "Lenovo ThinkPad Pen Pro" (SD60M68134) and a Bamboo Ink Plus Smart Stylus (CS-322A).  For some reason, the Bamboo pen is recognized as an eraser (id=17), which means the barrel buttons can't be remapped, but I think that's a different issue to be solved after we figure this out.

Is there a configuration setting that's needs to be tweaked?  What additional information would help figure out what's wrong?

Thanks for any help you can provide.

**Comment by jigpu** [comment]
The lower button should function as an eraser switch. Unless you are in an application that is configured to treat the eraser differently, it won't appear to do anything. If you run `xinput test` on the eraser device, you should see motion events whenever the button it held down. Similarly, if you configure GIMP to use both the stylus and eraser devices, it should automatically switch between tools as you hold and release the button.

Does this match what you experience?

As for your Bamboo stylus, the X driver has a bug that causes it to incorrectly confuse the stylus/eraser status. A fix for the issue is being reviewed at https://github.com/linuxwacom/xf86-input-wacom/pull/92

**Comment by expoqeteer** [comment]
Thanks for the quick update and the information on the Bamboo stylus.  The buttons on the min-pen that come with the Yoga are nearly unusable, so it will be nice to have a larger pen that works properly.

> If you run xinput test on the eraser device, you should see motion events whenever the button it held down. 

Yup, I see that.

> Similarly, if you configure GIMP to use both the stylus and eraser devices, it should automatically switch between tools as you hold and release the button.

That works too.

What doesn't work is the "Test Your Settings" area in GNOME Control Center. I can draw in that area with the pen, but if I press the lower button and draw in the area, it doesn't erase (just more ink is drawn).  Interestingly the Bamboo stylus **does** erase when I draw in that area (which is how I began to understand that the Bamboo stylus was being interpreted as an eraser and not a stylus).

I minor issue I suppose, but it would be nice to fix the GNOME Control Center behavior.  Is that something that would need to be addressed here or with GNOME?

**Comment by jigpu** [comment]
Huh, I didn't realize that the "Test Your Settings" area would erase, but indeed it does! Issues with the control center can be reported at https://gitlab.gnome.org/GNOME/gnome-control-center/issues
