### ISSUE TITLE
Improper button order in .tablet files

### ISSUE THREAD

**Issue by tb2097** [linuxwacom/libwacom#182]
Currently in the GUI I have written I am unable to ascertain the button order from the .tablet files.  Note, some .tablet files show a correct order (ie. cintiq-companion.tablet), however many do not (ie. intuos-pro-m.tablet).

My current solution to this is to parse the SVG file, which is a little painful.  As well, there are cases (like cintiq-companion.tablet) where there are 3 buttons horizontally aligned.  My suggestion would be to modify the .tablet files (without breaking their functionality with other processes) to more cleanly provide this information. For buttons that are horizontally aligned (on left/right side of tablet) or vertically aligned (if top/bottom), they could have their buttons delineated by - vs ;.  As well, the button in the middle of a ring (if it exists) can then assume RingUp is located above and RingDown is below.  I provide 2 examples below:

intuos-pro-m.tablet:
```
[Buttons]
- Left=A;B;C;D;E;F;G;H;I
+ Left=B;C;D;E;A;F;G;H;I

Ring=A
RingNumModes=4
```

In this example I would then know the button order is:
```
B
C
D
E
RingUp
A
RingDown
F
G
H
I
```
cintiq-companion.tablet
```
[Buttons]
- Left=B;C;G;H;A;F;I;D;E
+ Left=B;C;G;H-A-F;I;D;E
```

In this example I would be able to determine the button order is:
```
B
C
G
H A F
I
D
E
```

Known Issues:
A few legacy tablets would have issues with this display, as the buttons are not laid out cleanly.  As well, they also have touch strips that do not have a relative placement. Some alternative solution would need to be found to support these that doesn't require parsing the SVG file.

```
cintiq-12wx.tablet
cintiq-20wsx.tablet
cintiq-21ux2.tablet
cintiq-21ux.tablet
cintiq-22hd.tablet
cintiq-22hdt.tablet
generic.tablet
intuos3-*.tablet
```

**Comment by whot** [comment]
one of the reasons we never did this and went the way of the SVG instead is that we cannot be sure that any system we pick represents the actual buttons of past, let alone future tablets. Look at the Intuos3 tablets as an example, those use a colspan/rowspan-type layout.

So I guess the question here is really: what's your interface and how does it look like and why is the svg file insufficient. Maybe there's some other way around the issue.

Also, fwiw, the data files are an implementation detail so we can change them at-will. Which means we can use more expressive approaches to the button numbering than hiding it in `-`, `+`, etc.

**Comment by whot** [comment]
Closing, almost 3 years
