### ISSUE TITLE
Toshiba z20t-c digitizer screen setup

### ISSUE THREAD

**Issue by pheidrias** [linuxwacom/libwacom#183]
Dear all,
I'm not sure, wether this is the right place to seek for help.

My Screen of the z20t should support Wacom Stylus, but does so only as like I do simple finger touch. Stylus is recognized a few mm above the screen, but cannot be configured etc. 

System is up-to-date and fresh Ubuntu 19.10.
```
$ xsetwacom list devices
Wacom ISD-V4 Pen stylus         	id: 11	type: STYLUS    
Wacom ISD-V4 Pen eraser         	id: 17	type: ERASER 
```

but libwacom-list-local-devices doesn't yield anything.

```
$ sudo evtest
...selecting /dev/input/event7:	Wacom ISD-V4 Pen
gives 

Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x56a product 0x149 version 0x110
Input device name: "Wacom ISD-V4 Pen"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 320 (BTN_TOOL_PEN)
    Event code 321 (BTN_TOOL_RUBBER)
    Event code 329 (?)
    Event code 330 (BTN_TOUCH)
    Event code 331 (BTN_STYLUS)
    Event code 332 (BTN_STYLUS2)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value      0
      Min        0
      Max    27648
      Fuzz       4
      Resolution     100
    Event code 1 (ABS_Y)
      Value      0
      Min        0
      Max    15552
      Fuzz       4
      Resolution     100
    Event code 24 (ABS_PRESSURE)
      Value      0
      Min        0
      Max     2047
Properties:
  Property type 1 (INPUT_PROP_DIRECT)
```
When testing, the values change with proximity and applied pressure etc. 

So it seems, that the kernel part of the stylus input seems to be working. How do I set up or debug the libwacom setup properly to have a working stylus? I'd like to contribute my findings to the project...

Thanks in advance,
Guntram

EDIT:

I forgot to mention, that I did create a .tablet file, copying a Lenovo Yoga S3-type file and inserting Wacom ISD-V4 Pen as name and usb:056a:0149 . Unfortunately, this didn't change anything...

**Comment by whot** [comment]
nothing immediately sticks out here and given that the device shows up in `xsetwacom list` everything appears fine. Right now, the only guess I have is that the `.tablet` file you created had a typo or wasn't in the same directory as the others. I don't see any reason why `libwacom-list-local-devices` wouldn't list your device once the tablet file is in place.

**Comment by pheidrias** [comment]
Hello!

Thanks for having a look at this issue. I now tried several distributions etc. .
With a fresh Ubuntu 19.10 in a wayland session neither of the commans (xsetwacom list devices, libwacom-list-local-devices) shows anything, but the device is working.
At least in Xournal(pp) I can select from different wacom options an have the stylus working as well as the touchscreen.

This is however some strange behaviour - basic system tools won't identify something which apperently works :-(..

With best wishes for the holidays,
pheidrias

**Comment by whot** [comment]
xsetwacom [does not work under wayland](https://who-t.blogspot.com/2016/12/the-future-of-xinput-xmodmap-setxkbmap.html) but the device will work just fine - it's handled by libinput and the compositor directly.

if `libwacom-list-local-devices` doesn't show anything however, then it's not recognised which would indicate a typo in the `.tablet` file. That tool is independent of any GUI session and only uses the kernel files directly.

**Comment by pheidrias** [comment]
I finally got it running. I'm not too comfortable with git - could you maybe add this .tablet file to the libwacom database?

`cat /usr/share/libwacom/z20t.tablet
# this is for the Wacom pen + touchscreen as found in the Toshiba z20t-b, z20t-c and others.

[Device]
Name=Wacom ISD-V4 Pen
ModelName=
DeviceMatch=usb:056a:0149
Class=ISDV4
Width=10.9
Height=6.1
IntegratedIn=Display;System

[Features]
Stylus=true
Touch=true
Buttons=0
`
