### ISSUE TITLE
Intuos Pro M (PTH-651-ENES) not listed by xsetwacom, but works otherwise

### ISSUE THREAD

**Issue by battlesnake** [linuxwacom/libwacom#184]
Tablet is `PTH-651-ENES (Intuos pro medium)`
Kernel is `4.14.123`
Distro is `Arch`

Tablet is detected when plugged in or used wirelessly.

Wired:

    $ lsusb | grep -i wacom
    Bus 002 Device 022: ID 056a:0315 Wacom Co., Ltd PTH-651 [Intuos pro (M)]

Wireless:

    $ lsusb | grep -i wacom
    Bus 002 Device 017: ID 056a:0084 Wacom Co., Ltd ACK-40401 [Wireless Accessory Kit]

Kernel module is loaded:

    $ lsmod | grep wacom
    wacom                 110592  0
    led_class              16384  4 input_leds,wacom,iwlmvm,hp_accel
    usbhid                 57344  1 wacom
    hid                   122880  3 wacom,usbhid,hid_generic

`libwacom` can detect the tablet and lists a lot of information for it:

    $ libwacom-list-local-devices
    # Device node: /dev/input/event24
    [Device]
    Name=Wacom Intuos Pro M
    ModelName=PTH-651
    DeviceMatch=usb:056a:0315;
    Class=Intuos5
    Width=9
    Height=6
    IntegratedIn=
    Layout=intuos-pro-m.svg
    Styli=0x802;0x804;0x806;0x80a;0x80c;0x902;0x90a;0x100802;0x100804;0x10080a;0x10080c;0x100902;0x10090a;0x120802;0x140802;0x14080a;0x160802;0x16080a;
    ...
    ...

`xinput` also shows it:

    $ xinput list
    ⎡ Virtual core pointer                          id=2    [master pointer  (3)]
    ⎜   ↳ ...
    ⎜   ↳ Wacom Intuos Pro M (WL) Pad               id=19   [slave  pointer  (2)]
    ⎜   ↳ Wacom Intuos Pro M (WL) Finger            id=20   [slave  pointer  (2)]
    ⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
        ...
        ↳ Wacom Intuos Pro M (WL) Pen               id=18   [slave  keyboard (3)]

But `xsetwacom` doesn't list the tablet:

    $ xsetwacom --list devices
    $ echo $?
    0

Consequently, tools which seem to use `xsetwacom` also don't work with this tablet (e.g. https://github.com/lubosz/wacom-utility).

The tablet seems to work fine otherwise — pen does absolute cursor movement, finger does relative, Krita handles pressure and pen/eraser ends correctly.  But the various configuration GUI tools don't work, as `xsetwacom` isn't listing the tablet.

**Comment by whot** [comment]
most likely cause: you're using the libinput xorg driver, not the wacom one. `xinput list-props "Wacom Intuos Pro M (WL) Pen"` should verify this, just check the property name prefixes.

We generally still recommend the wacom driver in X.org setups, simply because clients have accumulated a decades-long tail of quirks and may not work with the simpler and slightly-different tablet implementation that the xorg libinput uses. `xsetwacom` [cannot work with the libinput driver or under Wayland](https://who-t.blogspot.com/2016/12/the-future-of-xinput-xmodmap-setxkbmap.html)

**Comment by battlesnake** [comment]
Ok, you're almost certainly right there.  For completeness, what am I looking for in this output from the command you provided?

```
$ xinput list-props "Wacom Intuos Pro M (WL) Pen"
Device 'Wacom Intuos Pro M (WL) Pen':
        Device Enabled (142):   1
        Coordinate Transformation Matrix (144): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        Device Node (267):      "/dev/input/event22"
        Device Product ID (268):        1386, 789
```

**Comment by whot** [comment]
that's all that command gives you? That is strange. Usually there's a bunch of properties with the driver name prefixed. Can you *attach* your xorg.log please?

**Comment by battlesnake** [comment]
[Xorg.0.log](https://github.com/linuxwacom/libwacom/files/3888848/Xorg.0.log)

```
$ pacman -Qqs xf86-input
xf86-input-keyboard
xf86-input-libinput
xf86-input-mouse
xf86-input-synaptics
xf86-input-vmmouse
xf86-input-void
xf86-input-wacom
```

How can I force it to use the wacom driver for the tablet, instead of libinput?

**Comment by battlesnake** [comment]
Info about my `libinput` binary+package:

```
$ pacman -Qo `which libinput`
/usr/bin/libinput is owned by libinput 1.14.3-1

$ pacman -Qi libinput
Name            : libinput
Version         : 1.14.3-1
Description     : Input device management and event handling library
Architecture    : x86_64
URL             : https://www.freedesktop.org/wiki/Software/libinput/
Licenses        : custom:X11
Groups          : None
Provides        : None
Depends On      : mtdev  systemd  libevdev  libwacom
Optional Deps   : gtk3: libinput debug-gui [installed]
                  python-pyudev: libinput measure
                  python-libevdev: libinput measure
Required By     : clutter  qt5-base  weston  xf86-input-libinput
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 849.09 KiB
Packager        : Andreas Radke <andyrtr@archlinux.org>
Build Date      : Mon 28 Oct 2019 08:22:13 EET
Install Date    : Wed 30 Oct 2019 01:15:39 EET
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by whot** [comment]
ok, log says `[ 34506.301] (II) Using input driver 'libinput' for 'Wacom Intuos Pro M (WL) Pen'`. Which means that for whatever reason, your [70-wacom.conf](https://github.com/linuxwacom/xf86-input-wacom/blob/master/conf/70-wacom.conf) is missing because there should be a message stating `Applying InputClass "Wacom USB tablet class"`.

That snippet should be part of the wacom driver package which means it either got removed or there's some packaging issue with the arch package.

**Comment by battlesnake** [comment]
Odd, I have that file, line-for-line in `/usr/share/X11/xorg.conf.d`.  It's possibly I haven't restarted X11 since installing the wacom driver a few weeks ago (I normally just put this machine to sleep), I'll try that just in case this is a user-idiocy bug.

**Comment by battlesnake** [comment]
Bug was user idiocy, `xsetwacom` works fine now that I've restarted X.  `wacom-utility` still doesn't see the tablet, but that issue is almost certainly not relevant to `libwacom`.  Thanks for your help.

**Comment by droukd** [comment]
I have exactly the same issue.

```[    18.251] (II) config/udev: Adding input device Wacom Intuos5 M Pen (/dev/input/event4)
[    18.251] (**) Wacom Intuos5 M Pen: Applying InputClass "Wacom USB tablet class"
[    18.251] (**) Wacom Intuos5 M Pen: Applying InputClass "Wacom tablet class"
[    18.251] (**) Wacom Intuos5 M Pen: Applying InputClass "libinput tablet catchall"
[    18.251] (II) Using input driver 'libinput' for 'Wacom Intuos5 M Pen'
[    18.304] (II) systemd-logind: got fd for /dev/input/event4 13:68 fd 35 paused 0
[    18.304] (**) Wacom Intuos5 M Pen: always reports core events
[    18.304] (**) Option "Device" "/dev/input/event4"
[    18.304] (**) Option "_source" "server/udev"
[    18.305] (II) event4  - Wacom Intuos5 M Pen: is tagged by udev as: Tablet
[    18.305] (II) event4  - Wacom Intuos5 M Pen: device is a tablet
[    18.305] (II) event4  - Wacom Intuos5 M Pen: device removed
[    18.305] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:056A:002A.0001/input/input11/event4"
[    18.305] (II) XINPUT: Adding extended input device "Wacom Intuos5 M Pen" (type: TABLET, id 9)
[    18.307] (II) event4  - Wacom Intuos5 M Pen: is tagged by udev as: Tablet
[    18.307] (II) event4  - Wacom Intuos5 M Pen: device is a tablet
[    18.307] (II) config/udev: Adding input device Wacom Intuos5 M Pad (/dev/input/event10)
[    18.307] (**) Wacom Intuos5 M Pad: Applying InputClass "Wacom USB tablet class"
[    18.307] (**) Wacom Intuos5 M Pad: Applying InputClass "Wacom tablet class"
[    18.307] (**) Wacom Intuos5 M Pad: Applying InputClass "libinput tablet catchall"
[    18.307] (II) Using input driver 'libinput' for 'Wacom Intuos5 M Pad'
[    18.308] (II) systemd-logind: got fd for /dev/input/event10 13:74 fd 36 paused 0
[    18.308] (**) Wacom Intuos5 M Pad: always reports core events
[    18.308] (**) Option "Device" "/dev/input/event10"
[    18.308] (**) Option "_source" "server/udev"
[    18.309] (II) event10 - Wacom Intuos5 M Pad: is tagged by udev as: Tablet
[    18.310] (EE) event10 - Wacom Intuos5 M Pad: libinput bug: missing tablet capabilities: pen resolution. Ignoring this device.
[    18.310] (II) event10 - Wacom Intuos5 M Pad: device is a tablet
[    18.310] (II) event10 - failed to create input device '/dev/input/event10'.
[    18.310] (EE) libinput: Wacom Intuos5 M Pad: Failed to create a device for /dev/input/event10
[    18.310] (EE) PreInit returned 2 for "Wacom Intuos5 M Pad"
[    18.310] (II) UnloadModule: "libinput"
[    18.310] (II) systemd-logind: releasing fd for 13:74
[    18.328] (II) config/udev: Adding input device Wacom Intuos5 M Pad (/dev/input/js0)
[    18.328] (II) No input driver specified, ignoring this device.
[    18.328] (II) This device may have been added with another device file.
```

Except, I use «Wayland». Not sure, what to do.

Since there is no experience same as with official drivers, I should probably stick to using tablet with/through mainstream OS. Especially when apps are already there and extensions working well, with no need to configure/ debug/ tinker.
Feels weird. Desktops, these days.

(Makes me wonder, why Valve moved to Linux, and _Wacom_ have not.
All I want to do is do my job, frictionless.)

**Comment by whot** [comment]
> Except, I use «Wayland». Not sure, what to do.

Not according to the log above, that's Xorg running natively, not Xwayland.

> [    18.251] (II) Using input driver 'libinput' for 'Wacom Intuos5 M Pen'

As in https://github.com/linuxwacom/libwacom/issues/184#issuecomment-558371385, you're **not** using the xf86-input-wacom driver, your configuration assigns the libinput driver instead. I don't know why. If you're on fedora, install xorg-x11-drv-wacom and you're good, not sure for other distributions.

> [    18.309] (II) event10 - Wacom Intuos5 M Pad: is tagged by udev as: Tablet

If this shows up, your installation is broken somehow. This device should be tagged as `ID_INPUT_TABLET_PAD` in udev but that tag is missing. This tag is usually assigned by libwacom, so your libwacom installation is somehow broken.
