### ISSUE TITLE
Cross-issue: Motion Computing R12 lost of touch in kernel 5.3

### ISSUE THREAD

**Issue by bionade24** [linuxwacom/libwacom#190]
Problem occurs with `libwacom`, too.  https://github.com/linuxwacom/input-wacom/issues/121

**Comment by jigpu** [comment]
Unless I'm misunderstanding, this isn't an issue with libwacom at all. The broken touch is caused by an interaction between the device and the kernel driver. Libwacom is just a database of tablet properties.

**Comment by bionade24** [comment]
Okay, why do then some people try to patch the userspace part (`xf86-input-wacom`) Thought  another problem is that the fix will need a change in the userspace part which probably don't work with older Kernels.

**Comment by bionade24** [comment]
Sorry, my fault. Was confused by the names.

**Comment by jigpu** [comment]
Ah, okay. Its super easy to get the various projects and their names confused. :smile:
