### ISSUE TITLE
can not use wacom pth660 on Ubuntu buidge 17.04 only connection succeed

### ISSUE THREAD

**Issue by 243750496** [linuxwacom/libwacom#2]
![screenshot](https://cloud.githubusercontent.com/assets/6311930/24926802/68439532-1f2f-11e7-8619-71178215aac1.png)
![screenshot-wacom](https://cloud.githubusercontent.com/assets/6311930/24926864/a3e266c2-1f2f-11e7-8866-d21f8690f6e2.png)

with the pen moved there's nothing happened and theres no item show up in wacom settings page
so any solutions?

BTW:xserver-xorg-input-wacom=0.34
![version](https://cloud.githubusercontent.com/assets/6311930/24927003/127976fc-1f30-11e7-8d27-724d783b44ca.png)

**Comment by terzag** [comment]
(There's an typo in your title, it should be Budgie, not buidge.)

The pth660 tablet seems to be an Intuos Pro? Not sure of the exact model but have you checked if in the various intuos .tablet files in the data dir of the project there is one that matches your tablet ID (that you can get through lsusb)? If not, it looks like your model isn't handled but I guess you could create a working .tablet file. I have a similar issue witha Graphire 2 and I've managed to make it appear in the Tablet tab. Still don't have anything in the Stylus one, I'm trying to work out if it's normal or not (and how to fix it in that case).

**Comment by jigpu** [comment]
Indeed, the lack of any entry in the Wacom Tablet Settings control panel is almost surely a result of Ubuntu 17.04 shipping a version of libinput (0.22.0) which does not have definitions for the PTH-660. You would need to install at least libwacom 0.24.0.

The PTH-660 requires the Linux 4.11 kernel for full support (including Bluetooth). Ubuntu 17.04 appears to only ship Linux 4.10, which will not work properly. Alternatively, version 0.35.0 of our "input-wacom" driver can be installed which will provide an updated kernel driver for pre-4.11 kernels.
