### ISSUE TITLE
Duplicate matching error and problem with USB for CTL 6100 WL

### ISSUE THREAD

**Issue by treedoug** [linuxwacom/libwacom#200]
I am trying to use a CTL-6100WL (Wacom Intuos BT M) with Ubuntu 18.04. I had several issues with this tablet. After installing input-wacom-0.45.0 and xfs-input-wacom-0.39.0 from source, I got the ["duplicate matches" error](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#duplicate-matches). I edited several files in /usr/share/libwacom to get rid of duplicates. The troubleshooting page indicated that I should file a bug report in this case.

In addition, after doing this, I find the following:
* The tablet *is not* recognized using `libwacom-list-local-devices` when plugged in with usb.
* The tablet has some kind of a mapping issue when plugged in using usb. The screen is mapped to only about half of the tablet area. When moving the stylus to the right past the half-way point, drawing cannot continue to the right.
* The tablet *is* recognized when using bluetooth and works normally when using bluetooth.

I subsequently added the address from lsusb to the intuos-m-p3-wl.tablet file. This causes the command `libwacom-list-local-devices` to retrieve the correct .tablet file, but does not lead to a functioning tablet.

**Comment by whot** [comment]
did you install libwacom from source too? the duplicate matches is most likely because you left the system package in place - removing that package first should fix the issue. We have now enough CI that for duplicate matches I tend to blame a local setup :)

> The tablet is not recognized using libwacom-list-local-devices when plugged in with usb.

this means that the .tablet file is missing or does not match the device

> The tablet has some kind of a mapping issue when plugged in using usb. 

sounds like a kernel or X driver issue. my bet is on the input-wacom module here, please file a separate issue there.

> I subsequently added the address from lsusb to the intuos-m-p3-wl.tablet file

**Comment by treedoug** [comment]
Yes, I did build libwacom from source. I removed the system package and re-built it. This resolved the duplicates mess. I also updated the .tablet file as requested (see PR). 

I will submit an issue to input-wacom for the other bug. Thanks!

**Comment by skomra** [comment]
I saw your PR, If you are seeing 2d1f as the vendor ID (VID) that means the tablet firmware has wrongly detected that it is connected to and Android device. You can manually switch the tablet back into Linux mode by holding down buttons 1&4 for N number of seconds.

**Comment by treedoug** [comment]
Perfect! This solved my problem. Thanks for the video link. It wasn't clear that the light indicated Android/Linux mode.

**Comment by skomra** [comment]
Glad to help. My apologies that this hasn't been communicated better.

**Comment by whot** [comment]
I think we can close this issue then, thanks!
