### ISSUE TITLE
Thinkpad L390 Yoga Pen Pro does not show up in control panel and secondary buttons not functioning properly

### ISSUE THREAD

**Issue by NovaViper** [linuxwacom/libwacom#218]
Hi! I just finished installing Ubuntu 19.10 and I notice that my pen works with the computer just fine (I can erase and draw on it, even pressure sensitivity is working) but I notice that the pen will not appear in the Wacom tablet control panel (the Tablet section recongizes, but the stylus does not). Even stranger is that the tablet data is on the computer, as shown here: https://paste.ubuntu.com/p/BVw2WBpDxr/

**Comment by jigpu** [comment]
This is a known issue. We're working on patches to add support for tablet PC pens right now and will hopefully have libwacom support soon, and GNOME control panel support a few months afterward.
