### ISSUE TITLE
Can't recognise Wacom Bamboo CTH-470

### ISSUE THREAD

**Issue by ollylove** [linuxwacom/libwacom#226]
Help!
I followed all instructions, removed duplicates and this is the output of `libwacom-list-local-devices`:

```
# Device node: /dev/input/event25
[Device]
Name=Wacom Bamboo Capture
ModelName=CTH-470
DeviceMatch=usb:056a:00de;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=bamboo-16fg-s-pt.svg
Styli=0xffffe;0xfffff;

[Features]
Reversible=true
Stylus=true
Ring=false
Ring2=false
Touch=true
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
Left=A;B;C;D;
# Right=
# Top=
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x110;0x115;0x116;0x111;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0
```

I rebooted, plugged in my tablet and it doesn't work, and this command prints this output:
```
grep "" /sys/module/wacom*/version
grep: /sys/module/wacom*/version: No such file or directory
```

What do I do now?

**Comment by whot** [comment]
Note that libwacom doesn't have an effect on whether the tablet works:
https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work

Based on the above I'd say the libwacom entry is correct and if the tablet doesn't work it's an issue either with the wacom drivers in the kernel or the Xorg drivers (or libinput under Wayland).

**Comment by jigpu** [comment]
What instructions did you follow, and which components have you manually installed (libwacom, input-wacom, xf86-input-wacom)?

It would be helpful for you to run our [sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) and then attach the generated tarball to this issue.

**Comment by whot** [comment]
Closing after a month of silence
