### ISSUE TITLE
Pointer occasionally jumps to the edge of screen when mapping CTH-470 to a portrait oriented screen

### ISSUE THREAD

**Issue by gergelypolonkai** [linuxwacom/libwacom#234]
I have a Bamboo Fun tablet (listed as CTH-470), mapped to my HDMI screen HDMI-A-2. The environment is Sway (Wayland) running on Arch Linux, with all packages being up to date.

Here is my desired configuration in Sway:

```
output HDMI-A-2 {
    transform 270
}

input 1386:222:Wacom_Bamboo_16FG_4x5_Pen {
    map_to_output HDMI-A-2
}
```

When i omit the `transform 270` section from my config, everything is fine. When i add it back, the tablet is mapped correctly to the new orientation (i have to rotate the device so its buttons are on the top instead of being on the left), but when i draw a vertical line, the pointer occasionally jumps to the left edge of the screen. The result (drawn in Krita) is… not so useful.

![bamboo pen problem_resized](https://user-images.githubusercontent.com/264485/79037264-dc679500-7bbe-11ea-9796-9920874e98d8.jpg)

**Comment by whot** [comment]
In Wayland compositors, the screen mapping and resulting coordinate handling is managed by the compositor alone. libwacom just says "this is an external tablet device" and nothing more. libinput provides the on-device coordinates to the compositor but beyond that it's compositor issue.

Please file a bug against sway, this cannot be fixed here.
