### ISSUE TITLE
Wacom one medium no more recognized

### ISSUE THREAD

**Issue by chdioux** [linuxwacom/libwacom#24]
Hello,
My Wacom one medium tablet was not recognized on both of my computers under Ubuntu 16.04.
Although I'm not a developer, I tried to fix that by building the drivers from the sources you are providing because i can't wait any longer a built-in version in Ubuntu. Your explanations were very helpful for a non professional like me, thank you so much for that.
Unfortunately, on both computers, my tablet is still not recognized. BUT more than that, on my old Packard Bell EasyNote, it actually ***DID work*** for a while yesterday at night, just after the upgrading of the drivers, but it is not working anymore this morning. I've done nothing in the meantime, except to shutdown the computer.
I'm attaching the logs you asked for on another similar topic.
By the way, if this is not the best place to get help for a grassroots user like me, could you please tell me were i can get this kind of advanced help, because i'd really love to use my Wacom tablet and on "general" Ubuntu forums, people there can't help much more than by saying to look here.
Regards
[sysinfo.LKtj9xwr3T.tar.gz](https://github.com/linuxwacom/libwacom/files/2076287/sysinfo.LKtj9xwr3T.tar.gz)

**Comment by skomra** [comment]
Hi chdioux, 

This should be filed against input-wacom instead of libwacom, but you are otherwise in the correct place. I've reproduced this issue and I'm investigating. 

Thanks

**Comment by whot** [comment]
closing this based on aaron's comment, please move this to input-wacom instead. For a summary of what libwacom is: https://who-t.blogspot.com/2017/10/what-is-libwacom.html

**Comment by chdioux** [comment]
Hi,
Thanks for the answer and the explanations and sorry for the mistake. I'm really a newbie here. I will do that.

**Comment by whot** [comment]
> sorry for the mistake.

just to not let this just pass - it really doesn't matter. We (well, definitely I) are usually terse in bug reports, but things like misfiling a bug is not something you need to apologise for. better a misfiled bug than someone not daring to file a bug in the first place.
