### ISSUE TITLE
Driver detects two devices at the same time causing graphic problems.

### ISSUE THREAD

**Issue by Betrocoli** [linuxwacom/libwacom#242]
Hello, here's what happened.
1. Took my wacom intuos S out of the box and plugged it
2. Control panel won't detect it.
3. proceed to install the three drivers from here https://linuxwacom.github.io/ following every instruction.
4. after the first and second driver tablet was detected and worked fine but I wanted to configure the 4 top buttons too so...
5. Proceeded to install libwacom to identify the buttons. Reboot.
6. Now I plug the tablet and the general monitor image starts acting weird, all the fonts in action menus of every window start blinking changin font size at the rythm the cursor blinks.

7. I run "libwacom-list-local-devices" and this is the output:
```
> betrocoli@broccoloco:~$ libwacom-list-local-devices 
# Device node: /dev/input/event16
[Device]
Name=Wacom Intuos S
ModelName=CTL-4100
DeviceMatch=usb:056a:0374;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x100;0x101;0x102;0x103;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
# Device node: /dev/input/event15
[Device]
Name=Wacom Intuos S
ModelName=CTL-4100
DeviceMatch=usb:056a:0374;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x100;0x101;0x102;0x103;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

 ---------------------------------------------------------------
```
I already checked for duplicated files in the /usr/share/libwacom directory as the troubleshooting section says and nothing is duplicated.
Pls help as soon as possible, I have tons of work to do and the tablet is a bless for comodity.

**Comment by whot** [comment]
The duplicate listing is expected. `libwacom-list-local-devices` scans every event node it finds and checks it for product/vendor id matches and most wacom devices expose at least 2 event nodes with the same PID/VID (one for the stylus, one for the pad).


> Now I plug the tablet and the general monitor image starts acting weird, all the fonts in action menus of every window start blinking changin font size at the rythm the cursor blinks.

unrelated. libwacom is a C library around a bunch of text files, see also [here](https://github.com/linuxwacom/libwacom/wiki#purpose) and has no effect on how the device itself works or how other bits in the stack work. This sounds like your upgrade introduced another bug elsewhere.

**Comment by Betrocoli** [comment]
Update:
Excuse my ignorance I'll try to explain myself. 
So I had two directories named libwacom, one in /home/username/libwacom, this one had the make files and a bunch of other files i guess necesary for building the driver, also a "data" directory where all the text files for each model of tablet.
The other one was in /usr/share/libwacom with the text files for each model
Thinking it was a bug caused by some kind of duplicity of the files I removed the one directory that was in the /home folder. The bug of the monitor's weird behavior stopped.
Still, I forgot to mention another thing that was happened: the "wacom tablet" option in the "system settings" menu crashed when I tried to open it while the bug was active making it impossible to configure anything from the control panel, so I got curious, I temporarily moved the text file corresponding to my tablet model (CTL4100) from the /usr/share/libwacom directory and inmmediatly the "system settings" menu worked only that not with the correct layout but one without the top buttons I initially wanted to configure.
I guess I can work like this, I'll try to configure the buttons from termina but still the libwacom driver is not working as it should for some reason.

**Comment by Betrocoli** [comment]
Do you think it is related with the driver confusing linux for android?

**Comment by Betrocoli** [comment]
Update:
Yes. It is confirmed. When I move the file corresponding to my tablet's model out of /usr/share/libwacom the bug disappears. When I move it back the monitor starts blinking.

**Comment by whot** [comment]
that is ... strange.

the xf86-input-wacom driver doesn't use libwacom and neither does the input-wacom kernel driver module. The ctl-4100 is an external tablet so it's not like its presence would trigger any monitor reconfiguration.

libinput does use libwacom but only to set the various bits on a stylus. if you're on Wayland then you're using libinput but that would indicate some really bad (and strangely consistent) memory corruption. On X check with `xinput list-props <device name>` whether the device's properties are prefixed with "libinput" or "wacom" - if the latter you're using the xf86-input-wacom driver.

Either way, I have no idea what could possibly cause this issue.

**Comment by whot** [comment]
almost 2y since the last update, closing. And as said above, no idea how this could possibly be related to libwacom.
