### ISSUE TITLE
Configurator show the tablet but not the pencil 

### ISSUE THREAD

**Issue by juanwacom** [linuxwacom/libwacom#246]
Dear Sirs, 

I use Ubuntu 18.04 and Wacom Intuos BT S and I see the tablet on the configurator but I don't see the PENCIL on the configurator screen.

I followed the instructions of https://github.com/linuxwacom/libwacom/wiki

And found duplicated matches so I removed the libwacom-common package from the system and now seems there aren't duplicate files.

But, when I do xsetwacom --list devices I have this:

Wacom Intuos BT S Pad pad       	id: 12	type: PAD       
Wacom Intuos BT S Pen cursor    	id: 20	type: CURSOR    
Wacom Intuos BT S Pen stylus    	id: 13	type: STYLUS    
Wacom Intuos BT S Pen eraser    	id: 19	type: ERASER 

![tablet screenshot ](https://user-images.githubusercontent.com/65011790/81388288-62bcbb80-9118-11ea-84e8-64568129d949.png)

![pencil screenshot configurator](https://user-images.githubusercontent.com/65011790/81388304-6a7c6000-9118-11ea-92a2-bfac4830662b.png)

Please any ideas why don't show the PENCIL on the configurator?

Thanks for your help.

Juan

**Comment by jigpu** [comment]
This is a GNOME bug that was recently fixed in its 3.36 release. You will need to update to Ubuntu 20.04 or similar to get this fix. See also https://github.com/linuxwacom/input-wacom/issues/175
