### ISSUE TITLE
Wacom One is working but Wacom GUI showing no tablet detected on Lenovo Think Pad 

### ISSUE THREAD

**Issue by rishabhverma17** [linuxwacom/libwacom#254]
**Device name**
One By WACOM
>

**Device model identifier**
CTL-472/KO-CX
> 

Tablet Works but the Wacom Tablet GUI shows no tablet detected. 
OS : Ubuntu 16.04

**udevadm info output**

**Comment by rishabhverma17** [comment]
lsubsb shows the device
Bus 001 Device 021: ID 056a:037a Wacom Co., Ltd 

modinfo wacom | grep version
version:        v2.00-0.46.0
srcversion:     62537F6XXXXXXXXXXX

![image](https://user-images.githubusercontent.com/8901196/82441155-26477300-9abb-11ea-8c1a-980a516943f1.png)

**Comment by whot** [comment]
does `libwacom-list-local-devices` show the device?

**Comment by whot** [comment]
oh, wait -  `OS : Ubuntu 16.04` - is that correct? In that case you'll need to talk to Ubuntu to update the libwacom package, the device was added in ca4482219c05413eb98da234cfdcf63b61f7ab52 but that's 2 years after 16.04 was released. So they need to backported the patch or updated to libwacom >= 0.28.

**Comment by rishabhverma17** [comment]
## Got it working. Installed **input-wacom-0.43.0**
--------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/8901196/82663812-02686680-9c4e-11ea-80a9-4ae8b12f5984.png)

Yes, **_libwacom-list-local-devices_** shows the device, It was showing with the latest driver as well but tablet was not getting detected.

### How it worked for me: [In all the below steps I downloaded the zip file, Build them locally then Installed the package]
------------------------------------------------------------------------------------------------------------
- Installed **input-wacom-0.43.0** 
- Installed **xf86-input-wacom-0.39.0**
- Installed or update **libwacom**

```bash
sudo reboot
```
