### ISSUE TITLE
ASUS Vivobook TP412 - Stylus Cannot be Found/Configured

### ISSUE THREAD

**Issue by BugInACode** [linuxwacom/libwacom#255]
`xsetwacom --list devices` shows nothing in the terminal, tried rebuilding drivers and nothing changed. I can use the stylus in things like xournalpp but cannot configure any buttons or how the stylus functions in say a web browser (can only highlight text and only one button of the two works as a middle wheel scroll).

This is the output of machine.txt of the sysinfo script

```
/sys/class/dmi/id/bios_date:01/10/2020
/sys/class/dmi/id/bios_vendor:American Megatrends Inc.
/sys/class/dmi/id/bios_version:TP412FAC.300
/sys/class/dmi/id/board_name:TP412FAC
/sys/class/dmi/id/board_vendor:ASUSTeK COMPUTER INC.
/sys/class/dmi/id/board_version:1.0
/sys/class/dmi/id/chassis_type:31
/sys/class/dmi/id/chassis_vendor:ASUSTeK COMPUTER INC.
/sys/class/dmi/id/chassis_version:1.0
/sys/class/dmi/id/modalias:dmi:bvnAmericanMegatrendsInc.:bvrTP412FAC.300:bd01/10/2020:svnASUSTeKCOMPUTERINC.:pnVivoBook_ASUSLaptopTP412FAC_TP412FA:pvr1.0:rvnASUSTeKCOMPUTERINC.:rnTP412FAC:rvr1.0:cvnASUSTeKCOMPUTERINC.:ct31:cvr1.0:
grep: /sys/class/dmi/id/power: Is a directory
/sys/class/dmi/id/product_family:VivoBook Flip
/sys/class/dmi/id/product_name:VivoBook_ASUSLaptop TP412FAC_TP412FA
/sys/class/dmi/id/product_sku:
/sys/class/dmi/id/product_version:1.0
grep: /sys/class/dmi/id/subsystem: Is a directory
/sys/class/dmi/id/sys_vendor:ASUSTeK COMPUTER INC.
/sys/class/dmi/id/uevent:MODALIAS=dmi:bvnAmericanMegatrendsInc.:bvrTP412FAC.300:bd01/10/2020:svnASUSTeKCOMPUTERINC.:pnVivoBook_ASUSLaptopTP412FAC_TP412FA:pvr1.0:rvnASUSTeKCOMPUTERINC.:rnTP412FAC:rvr1.0:cvnASUSTeKCOMPUTERINC.:ct31:cvr1.0:
```

**Comment by jigpu** [comment]
Was xsetwacom previously working at some point? Also, can you provide the rest of the sysinfo output? The following information from sysinfo is necessary to help us figure out what's going on:

* What distribution are you using (e.g. Ubuntu 20.04)
* Are you using Wayland or Xorg
* What devices are printed out by `xinput list`?

**Comment by BugInACode** [comment]
> Virtual core pointer                    	id=2	[master pointer  (3)]
> ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
> ⎜   ↳ ELAN1300:00 04F3:310C Mouse             	id=11	[slave  pointer  (2)]
> ⎜   ↳ ELAN1300:00 04F3:310C Touchpad          	id=12	[slave  pointer  (2)]
> ⎜   ↳ ELAN2097:00 04F3:2B22                   	id=13	[slave  pointer  (2)]
> ⎜   ↳ Logitech T400                           	id=9	[slave  pointer  (2)]
> ⎜   ↳ ELAN2097:00 04F3:2B22 Pen (0)           	id=23	[slave  pointer  (2)]
> ⎜   ↳ ELAN2097:00 04F3:2B22 Eraser (0)        	id=24	[slave  pointer  (2)]
> ⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
>     ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
>     ↳ Power Button                            	id=6	[slave  keyboard (3)]
>     ↳ Video Bus                               	id=7	[slave  keyboard (3)]
>     ↳ Power Button                            	id=8	[slave  keyboard (3)]
>     ↳ USB2.0 VGA UVC WebCam: USB2.0 V         	id=10	[slave  keyboard (3)]
>     ↳ ELAN2097:00 04F3:2B22                   	id=14	[slave  keyboard (3)]
>     ↳ Intel HID events                        	id=15	[slave  keyboard (3)]
>     ↳ Intel HID 5 button array                	id=16	[slave  keyboard (3)]
>     ↳ Asus WMI hotkeys                        	id=17	[slave  keyboard (3)]
>     ↳ AT Translated Set 2 keyboard            	id=18	[slave  keyboard (3)]
>     ↳ Logitech T400                           	id=19	[slave  keyboard (3)]
>     ↳   USB Keyboard System Control           	id=20	[slave  keyboard (3)]
>     ↳   USB Keyboard Consumer Control         	id=21	[slave  keyboard (3)]
>     ↳   USB Keyboard                          	id=22	[slave  keyboard (3)] 

The above is the output of `xinput list` and I'm running Ubuntu 20.04, in X11. It has been like this the entire time.

**Comment by whot** [comment]
looks like you're running the `xf86-input-libinput` driver, not the wacom driver. That is to be expected, the wacom driver is somewhat selective in what tablet devices it binds to (see `70-wacom.conf`). You can try a local xorg.conf override:

```
$ cat /etc/X11/xorg.conf.d/99-elan-tablet.conf
Section "InputClass"
   Identifier "ELAN tablet uses wacom now"
   MatchIsTablet "true"
   MatchName "ELAN1300:00 04F3:310C"
   Driver "wacom"
EndSection
```

that should work, though I recommend reading the xorg.conf man page to understand what the above does.

**Comment by BugInACode** [comment]
The folder 'xorg.conf.d' only exists in /usr/share/X11, not /etc/X11. Inside this folder only contains the following five files
> 10-amdgpu.conf
> 10-quirks.conf
> 10-radeon.conf
> 40-libinput.conf
> 70-wacom.conf
I'm not exactly sure if this was the folder you meant, but if it was, which .conf file would I edit, and would it still be the same as above?

**Comment by whot** [comment]
`/usr/share/X11/xorg.conf.d` is where the packages install their files, `/etc/X11/xorg.conf.d` is where you put the local custom overrides. Just create that folder if it doesn't exist. And you don't edit, the above is the whole content of the file. [this post](https://who-t.blogspot.com/2014/03/stacking-xorgconfd-snippets.html) may help.

**Comment by BugInACode** [comment]
Just added the .conf file with the contents you mentioned, rebooted my computer and I could not boot into an Xorg session, I had to boot into Wayland to write this, I have now removed the file. Any idea on what to do next?

**Comment by whot** [comment]
if X didn't start that means the xorg.conf file had a typo in it, check for the error message in the journal.

**Comment by BugInACode** [comment]
I'm relatively new to linux but from what I gathered i run `journalctl`? I didn't notice anything that was an error message. You'll have to forgive me as I am still learning all of this

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks
