### ISSUE TITLE
1.4: libwacom still is not LTO ready

### ISSUE THREAD

**Issue by kloczek** [linuxwacom/libwacom#267]
It was alredy reported in #152.
```
[tkloczko@barrel libwacom-1.4]$ /usr/bin/ninja -v -j1 -C x86_64-redhat-linux-gnu
ninja: Entering directory `x86_64-redhat-linux-gnu'
[1/2] /usr/bin/meson --internal exe --capture 65-libwacom.hwdb -- /home/tkloczko/rpmbuild/BUILD/libwacom-1.4/x86_64-redhat-linux-gnu/generate-hwdb
[2/2] gcc  -o test-deprecated 'test-deprecated@exe/test_test-deprecated.c.o' -Wl,--as-needed -Wl,--no-undefined -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -Os -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--start-group libwacom.so.2.6.1 -ldl -Wl,--end-group '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/home/tkloczko/rpmbuild/BUILD/libwacom-1.4/x86_64-redhat-linux-gnu/
FAILED: test-deprecated
gcc  -o test-deprecated 'test-deprecated@exe/test_test-deprecated.c.o' -Wl,--as-needed -Wl,--no-undefined -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -Os -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--start-group libwacom.so.2.6.1 -ldl -Wl,--end-group '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/home/tkloczko/rpmbuild/BUILD/libwacom-1.4/x86_64-redhat-linux-gnu/
/usr/bin/ld: test-deprecated.lto.o: in function `main':
/home/tkloczko/rpmbuild/BUILD/libwacom-1.4/x86_64-redhat-linux-gnu/../test/test-deprecated.c:77: undefined reference to `libwacom_match_destroy@LIBWACOM_0.33'
/usr/bin/ld: /home/tkloczko/rpmbuild/BUILD/libwacom-1.4/x86_64-redhat-linux-gnu/../test/test-deprecated.c:78: undefined reference to `libwacom_match_new@LIBWACOM_0.33'
/usr/bin/ld: /home/tkloczko/rpmbuild/BUILD/libwacom-1.4/x86_64-redhat-linux-gnu/../test/test-deprecated.c:79: undefined reference to `libwacom_error_set@LIBWACOM_0.33'
/usr/bin/ld: /home/tkloczko/rpmbuild/BUILD/libwacom-1.4/x86_64-redhat-linux-gnu/../test/test-deprecated.c:80: undefined reference to `libwacom_stylus_destroy@LIBWACOM_0.33'
/usr/bin/ld: /home/tkloczko/rpmbuild/BUILD/libwacom-1.4/x86_64-redhat-linux-gnu/../test/test-deprecated.c:81: undefined reference to `libwacom_update_match@LIBWACOM_0.33'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by whot** [comment]
Please see #174, the state of this hasn't changed. This is a test that fails that tests specifically for the deprecated symbols which won't work with LTO. Disable that test and it should work fine.

**Comment by kloczek** [comment]
If it is already deprecated  code is it would to remove testing that and/or at least have possibility to disable that parto of source code configurarion stage?

**Comment by whot** [comment]
the testing is there to verify that our symver handling does the right thing, so we won't remove that. The MR in #174 adds the option to disable that test with lto set in meson - if that's insufficient I'll need some more ideas or patches to suggest what we are supposed to do.

**Comment by kloczek** [comment]
However because those symbols are not part of the ABI interface defined in linker script that code is not included in produced with LTO binary.
So again: it that code is not part of the officially defined ABI what is the sens to test it?
Do you know is iot any 
Just checked fedora spec files:
```
[tkloczko@barrel SPECS.fedora]$ grep libwacom * -l
cinnamon-control-center.spec
cinnamon-settings-daemon.spec
cinnamon.spec
gnome-control-center.spec
gnome-settings-daemon.spec
kcm_wacomtablet.spec
libinput.spec
libwacom.spec
mutter.spec
```
Do you see on that list any other projects which needs/uses that code?

**Comment by whot** [comment]
> So again: it that code is not part of the officially defined ABI what is the sens to test it?

It's a backwards-incompatible ABI change, see b9961dbe912fa096230460b194eebdc8a590d256. We could make that change because we don't expect there to be any users of that particular ABI, but it's made **binary** backwards-compatible by the symver dance. Any software built against libwacom will continue to work, even if it uses those old symbols that no longer exist.

IOW, if you're recompiling the source against libwacom, you're not the target audience for this because you won't need to link against the symbols removed from the ABI. The test is there so we can make sure we are **binary** compatible. It may eventually be removed, but that requires a soname bump and this rebuilding of everything linked against libwacom.

**Comment by kloczek** [comment]
If that code on API layer is abandoned and nothing is using that IMO it would be just easier to just change SONAME and remove that over complexity.
libwacom it is not sensitive as libc so keeping that kind of ABI compatibility on source code layer is IMO a bit odd.
At least it should be IMO source code configuration option allowing to (consciously) drop that ABI compat bits (with disable testing that part as well).
KISS principle .. :)
With bumped SONAME it would be not possible use latest source code to generate libwacom DSO code for the systems which still needs to be ABI compliance. Everything else which will be rebuild from source code will not have such problems. Isn't it?

**Comment by whot** [comment]
>  nothing is using that 

we don't know and libwacom is used in the enterprise distros where binary compatibility is a thing. given it costs us virtually nothing to keep compatibility, we might as well do so. and again, your issue is not with the lib itself but with a single **test**. 

You're welcome to submit a MR to disable the test case, we already have it for meson after all.

**Comment by kloczek** [comment]
Using latest version of the linuxwacom with very old binaries is not the case which anyone will try to exercise.
I can understand what you are trying to archive but IMO it should be an source code configure stage option to remove all that legacy support. or enable that support on demand because in  most of the cases that code is dangling like lead weight between the legs.
Have encircled that code by proper #ifdef wrapping will allow to separate those bits and in some future remove that code entirely from linuxwacom master branch..
Really keeping that code as active one always IMO is not wise ..
