### ISSUE TITLE
Graphics Tablet Settings Automatically close

### ISSUE THREAD

**Issue by isaacelliott33** [linuxwacom/libwacom#27]
I have Ubuntu 18.04 using Cinnamon Desktop.  I have tried to follow steps to install libwacom.  Once I've installed and logged out of Ubuntu and relogged back in, the Graphics Tablet Settings Automatically close every time I try to open it.  By the way, I recently bought Wacom CTL-4100 tablet.

**Comment by whot** [comment]
What does `libwacom-list-local-devices` say?

**Comment by isaacelliott33** [comment]
Now, it just says no tablet detected when opening up the Graphics Tablet Settings.  However, my tablet still works as the pen is active and moving the mouse.

here's my libwacom-list-local-devices list.

[Device]
Name=Wacom Intuos S
DeviceMatch=usb:056a:0374;
Class=Bamboo
Width=8
Height=6
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
StatusLEDs=
NumStrips=0
Buttons=4
[Buttons]
Left=
Right=
Top=A;B;C;D;
Bottom=
Touchstrip=
Touchstrip2=
OLEDs=
Ring=
Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
[Device]
Name=Wacom Intuos S
DeviceMatch=usb:056a:0374;
Class=Bamboo
Width=8
Height=6
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
StatusLEDs=
NumStrips=0
Buttons=4
[Buttons]
Left=
Right=
Top=A;B;C;D;
Bottom=
Touchstrip=
Touchstrip2=
OLEDs=
Ring=
Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

**Comment by whot** [comment]
This output indicates that libwacom is working correctly. Check your `journal` as well in case there's an error message there. Are you using the wacom X driver? Check with xinput list-props "<device name>", the properties should be prefixed with "Wacom". If not, you're using the wrong driver and that may be why the control center can't handle it.

Either way: most likely a GNOME issue, maybe a Ubuntu issue. Closing this for now, we can reopen it if it ends up being a libwacom issue.
