### ISSUE TITLE
Support for XP-PEN Star G640S

### ISSUE THREAD

**Issue by Franzcoz** [linuxwacom/libwacom#284]
Good day to everyone, and first of all I am not sure if this is the place, but since is the only place that has a "non-wacom" label I am putting it here, please let me know if I am wrong.

OS: Arch Linux
DE: KDE Plasma

I own an XP-PEN Star G640S graphic tablet and I would like to ask for help in configuring it to work with wacom drivers and/or ask for it to be supported. The device is recognized as 3 different inputs as shown with "xinput list" command (only relevant shown):

⎡ Virtual core pointer                                            id=2  
⎜   ↳ UGTABLET 6 inch PenTablet Mouse            id=15 
⎣ Virtual core keyboard                                         id=3  
    ↳ UGTABLET 6 inch PenTablet Keyboard        id=14
    ↳ UGTABLET 6 inch PenTablet                        id=16

All of which are using libinput driver and get recognized almost perfectly: the tablet is rotated 90° CW, I suppose bc it was intended for using it with Android devices through an adapter, the pad and pen work but I can't modify them.

I have tried to get wacom driver to recognize the inputs by using a .conf file in "/etc/X11/xorg.conf.d", after which the tablet gets only partially functional, i.e. there is a "stylus" device and a "touch" device, which shouldn't exist bc the tablet doesn't have touch functionality. The "keyboard" should be working as a "pad" device but there is no such device in the list, and it isn't working anymore, like it disapears.

xinput list gives this:

⎡ Virtual core pointer                                            id=2  
⎜   ↳ UGTABLET 6 inch PenTablet Mouse touch  id=14
⎜   ↳ UGTABLET 6 inch PenTablet stylus             id=15

Here is a snippet I used in the .conf file:

Section "InputClass"
        Identifier "XP-PEN Star G640S"
        MatchUSBID "28bd:0906"
        MatchProduct "UGTABLET 6 inch PenTablet"
        Driver "wacom"
        Option "Rotate" "CW"
EndSection

I have used different versions of the .conf file, for example with a different snippet for every device, with "Option" "Type" "pad" for the keybaord, among others, but never managed to get it working as I intend. The best scneario is the already described, the worst is no device recognized. 

Also, I created a .tablet and a .svg file for libwacom but that didn't work. The only thing that worked best was the .conf file.

I'll let a file with udevadm output for every input device if it is of any help.

Thanks in advance.

[udevadm.txt](https://github.com/linuxwacom/libwacom/files/4972980/udevadm.txt)

**Comment by whot** [comment]
Two things here: the `data/xp-pen-g640.tablet` file should be fairly close to what you need, you can use that file as a guide for the tablet file for your tablet. Please file a PR with such a tablet file included.

But in the end, libwacom has no effect on how the tablet works, merely how it's mapped to monitors etc. If the tablet doesn't work, that's almost always an issue with the kernel drivers not exporting the device correctly.
