### ISSUE TITLE
Support for Gaomon PD1161

### ISSUE THREAD

**Issue by PushkinKachroo** [linuxwacom/libwacom#297]
Is there support for Gaomon PD1161?

**Comment by whot** [comment]
Maybe? There's [this one](https://github.com/linuxwacom/libwacom/blob/master/data/gaomon-s56k.tablet) and [this file](https://github.com/linuxwacom/libwacom/blob/master/data/gaomon-s620.tablet) both of which match a range of devices given that it looks like gaomon re-uses the HUION usb ids.

`libwacom-list-local-devices` will tell you more, if your device has a different vid/pid, we'll need a similar-looking file for that.
