### ISSUE TITLE
Intuos M buttons not configurable through gnome-control-center

### ISSUE THREAD

**Issue by dinojr** [linuxwacom/libwacom#300]
I'm using a Wacom intuos reported by libwacom as
`Name=Wacom Intuos BT M
ModelName=CTL-6100WL`

It shows up in the Tablet part of gnome-control-center, I can configure the stylus buttons but the 4 top buttons don't show up in the tablet configuration tab (see the attached picture)
![intuos](https://user-images.githubusercontent.com/2698065/98447398-d02bc200-2124-11eb-9f36-8e4f78dd7041.png)

I can however configure them through xsetwacom.

**Comment by whot** [comment]
this seems to be a bug in the GNOME stack then, the data file looks correct and lists 4 buttons. You can confirm this with `libwacom-list-local-devices`.

If that lists the buttons, then the issue is in what *consumes* libwacom, not libwacom itself.
