### ISSUE TITLE
How would I go about contributing Huion H950P compatibility

### ISSUE THREAD

**Issue by jconnolly837** [linuxwacom/libwacom#307]
Out of the box, my Huion H950P didn't show up in Gnome tablet settings, and after discovering libwacom and learning how to make a .tablet file, it now works perfectly. [Here's the one that I made for it](https://pastebin.com/aheZBuDi), it's based off of the Huion H610Pro .tablet file. I want to help add out-of-the-box compatibility for the H950P, but I hardly know a thing about github or libwacom, and anything with coding is out of the question for me. 

What would I need to do? and I'm probably gonna need help doing it too. I briefly looked at making a pull request, but have no idea what I'm doing.

**Comment by whot** [comment]
Not much needed tbh, just a PR that adds that file to the list. #304 is the most recent example, use that as boilerplate and just sub your file in. The [github docs](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) have some info on how to create a PR.

**Comment by jconnolly837** [comment]
I believe I've done this correctly. If so, tell me and I'll close the issue.
#308
