### ISSUE TITLE
Messed up Tablet Button Mapping in Gnome settings with my Wacom Intuos Pen & Touch M

### ISSUE THREAD

**Issue by Zhormos** [linuxwacom/libwacom#313]
Hello, 
Thank you for allowing me to use my tablet on Linux!

OS: Ubuntu 20.04.1 LTS
Gnome version: 3.36.3

This is something I noticed since 2018 but it was probably there before.
(for clarity this is the button layout from the file intuos-m-pt.tablet)
```
# Wacom
# Intuos Pen & Touch Medium
# CTH-680
#
# Successor of Bamboo3 series
#
# stylus with two buttons and eraser; 16FG touch
# Pen active area: 8.5 x 5.3in
# Touch active area: 8.5 x 5.3in
#
# Button Map:
# (A=RIGHT, B=LEFT, C=FORWARD, D=BACKWARD)
#
#     A                     C
#     B                     D
#    *-----------------------*
#    |                       |
#    |                       |
#    |        TABLET         |
#    |                       |
#    |                       |
#    *-----------------------*
```
**The issue**
In Gnome settings "map buttons" panel
- When I press the physical hardware button **A** on my tablet, the button **C** is highlighted and editable on the screen layout,
- Also the physical button **B** maps to **A** on screen
- When I press the button **C** nothing happens on screen, so I cannot remap this one.
- But the button **D** works as intended!
Now, even if the screen doesn't match I can remap the buttons A, B and D on my tablet with no more issue. 

This is the output of libinput debug events where i press the buttons, so that we can see the events are triggered for each button.
```
$ sudo libinput debug-events
(...)
-event16  DEVICE_ADDED     Wacom Intuos PT M Pad             seat0 default group7  cap:P buttons:4 strips:0 rings:0 mode groups:1
(...)
# [pressed button A]
-event16  TABLET_PAD_BUTTON +1.756s	  1 pressed (mode 0)
 event16  TABLET_PAD_BUTTON +2.070s	  1 released (mode 0)
# [pressed button B]
 event16  TABLET_PAD_BUTTON +4.898s	  0 pressed (mode 0)
 event16  TABLET_PAD_BUTTON +5.206s	  0 released (mode 0)
# [pressed button C]
 event16  TABLET_PAD_BUTTON +7.905s	  2 pressed (mode 0)
 event16  TABLET_PAD_BUTTON +8.271s	  2 released (mode 0)
# [pressed button D]
 event16  TABLET_PAD_BUTTON +9.615s	  3 pressed (mode 0)
 event16  TABLET_PAD_BUTTON +9.945s	  3 released (mode 0)
```
So the button C triggers an event as expected.
I noted there is something strange with button labels, A->1 B->0 C->2 D->3 although this may be another issue.
I opened the .tablet and .layout files with the hope to work around the issue by editing this files but I failed to find a way to make it work. 
Unfortunately I'm not skilled enough to investigate any further as well as I do not understand how libwacom and libinput are related together.

So it would be nice if you could investigate in this or give me some direction to work around.
Thanks in advance!

**Comment by jigpu** [comment]
This is a fairly well known issue that has been around for a long time. It affects the Bamboo and early (non-professional) Intuos devices. The root cause is GNOME expecting the driver to send a different set of button events than actually happens (it expects X11 button numbers 1, 2, 3, 8; we actually send 1, 3, 8, 9).

I have a script available at https://gist.github.com/jigpu/fde784840ba5731726e7382952b0d5ed which can be used to come up with an appropriate remapping. The script's comment explains what it does and how to use it. After the script ends it will temporarily reprogram the tablet and print out an xorg.conf.d snippet that you can use to make the configuration permanent.
