### ISSUE TITLE
How to map board to one of two screens

### ISSUE THREAD

**Issue by ily666666** [linuxwacom/libwacom#314]
I have two screens that connected computer.When I move pencil on 472 board, cursor moves on two screens.I want to know how to match one screen? I have installed libwacom through building

**Comment by jigpu** [comment]
If you are using the GNOME desktop, you can configure the monitor mapping in their control panel. See https://help.gnome.org/users/gnome-help/stable/wacom-multi-monitor.html.en for instructions.

If you are using KDE, you may be able to do something similar in their control panel, though I cannot find instructions.

For other desktops, you will probably need to use the `xsetwacom` command-line utility. You will first need to get the name of your stylus and eraser devices by running `xsetwacom list`. Next you will need to find the name of the monitor you want to map to by running `xrandr` and finding which display (e.g. "DVI-I-2", "HDMI-0", etc.) matches the display you want the tablet to be mapped to. Finally run `xsetwacom set "<name>" MapToOutput <monitor>` for both the stylus and eraser to map them to that monitor.

Alternatively, you could instead run `xsetwacom set "<name>" MapToOutput next` multiple times to cause the tablet to be mapped to each monitor. Just stop running the command when the tablet is mapped to the desired monitor.

**Comment by ily666666** [comment]
thanks

**Comment by ily666666** [comment]
when I run xrandr in command-line .
It shows 
```
Screen 0: minimum 8 x 8, current 3360 x 1080, maximum 32767 x 32767
HDMI-0 connected primary 1920x1080+1440+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+  59.94    50.00    50.00  
   1680x1050     59.95  
   1440x900      74.98    59.89  
   1280x1024     75.02    60.02  
   1280x720      60.00    59.94    50.00    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.93    59.94  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 connected 1440x900+0+180 (normal left inverted right x axis y axis) 408mm x 255mm
   1440x900      59.89*+
   1360x768      59.66  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
DP-5 disconnected (normal left inverted right x axis y axis)

```
SO, I run xsetwacom set "Wacom One by Wacom S Pen stylus" MapToOutput HDMI-0 ,but it shows that Unable to find an output 'HDMI-0'.

**Comment by jigpu** [comment]
The command you've provided looks fine to me; HDMI-0 should be exactly what you'd use. Out of curiosity, does DP-4 work or not?
