### ISSUE TITLE
Uninstalling libwacom-common or libwacom-2 breaks system functions in ubuntu 20.04

### ISSUE THREAD

**Issue by olivershetler** [linuxwacom/libwacom#332]
I can't uninstall libwacom-common and libwacom-2 because it will destroy my ubuntu operating system. Will libwacom be updated so that it doesn't act like malware??

**Comment by jigpu** [comment]
This is not a libwacom issue. Ubuntu (and practically every other distro) has chosen to enable Wacom support in packages like libinput and GNOME. Removing libwacom requires the system to also remove everything that depends on it, which is going to be much of the desktop environment. Similar "destruction" would occur if you removed other components depended on at a low level (e.g. libpng, libdbus, libevdev, etc.).
