### ISSUE TITLE
Wacom Intuos Pro S works but does not show up in Ubuntu 18.04 configuration panel

### ISSUE THREAD

**Issue by aleksejs-fomins** [linuxwacom/libwacom#334]
Wrote details in a [StackExchange](https://unix.stackexchange.com/questions/630047/no-tablet-detected-on-settings-devices-wacom-tablet-ubuntu-18-04) post. Please help

**Comment by jigpu** [comment]
Can you please run `lsusb -d 056a:` and post the output? There are two models of the Intuos Pro S and you'll need the correct tablet definition installed to have it appear in the control panel.

As a general answer, if a tablet does not show up in the control panel but _does_ show up in xsetwacom, it means that your system is missing a libwacom tablet definition file. As Wacom releases new products we have to release new definitions to go along with them for the control panel to work properly. The current set of tablet definitions can be found at https://github.com/linuxwacom/libwacom/tree/master/data but may or may not be compatible with older versions of libwacom. If you can identify the specific tablet that you need a definition for (e.g. through the lsusb command above) then we can provide you with an appropriate file and instructions on how to install it.

**Comment by aleksejs-fomins** [comment]
```
$ lsusb -d 056a:
Bus 003 Device 002: ID 056a:0392 Wacom Co., Ltd
```

**Comment by whot** [comment]
quick git suggests commit 851d0ea703e2a631bb21657094ad2194c2a7a714 added in Apr 2019, so that'd probably explain why ubuntu 18.04 doesn't have it. Your easiest approach is updating to libwacom 0.34 or grater. Atlernatively, you can copy that file (from that commit, not from current git) into your local directory and hope it works. You may have to remove the `ModelName=PTH-460` line though, can't remember when that was added.

**Comment by aleksejs-fomins** [comment]
I have followed the installation instructions to install the latest release (1.7). Now my settings do not start
```
$ gnome-control-center 
Failed to register: Timeout was reached
```
I'll try with an earlier version

**Comment by aleksejs-fomins** [comment]
Ok I am completely screwed. I have tried several different versions of libwacom and the behaviour persists that gnome-control-center does not even start. I have tried
```
sudo apt remove libwacom2 libwacom-common
sudo apt install gnome-control-center
```
and still the control center does not start. Please help

**Comment by jigpu** [comment]
Please run `find /usr -name "libwacom*"` and post the results. Its possible that the version you built from source was not completely removed. It would also help if you ran `gnome-control-center` from the command-line and copied all messages it prints out into your reply. Or is it only the `Failed to register: Timeout was reached` message you provided earlier? Many of the search results for that message suggest trying `killall gnome-control-center` -- can you check if that helps?

**Comment by aleksejs-fomins** [comment]
`killall gnome-control-center` worked and now I finally see the GUI. Thanks for your help

```
$ find /usr -name "libwacom*"
/usr/lib/x86_64-linux-gnu/libwacom.la
/usr/lib/x86_64-linux-gnu/libwacom.so.2.6.1
/usr/lib/x86_64-linux-gnu/pkgconfig/libwacom.pc
/usr/lib/x86_64-linux-gnu/libwacom.so
/usr/lib/x86_64-linux-gnu/libwacom.so.2
/usr/lib/x86_64-linux-gnu/libwacom.a
/usr/share/man/man1/libwacom-list-local-devices.1
/usr/share/libwacom
/usr/share/libwacom/libwacom.stylus
/usr/share/doc/libwacom-bin
/usr/share/doc/libwacom-common
/usr/share/doc/libwacom2
/usr/bin/libwacom-list-local-devices
/usr/include/libwacom-1.0
/usr/include/libwacom-1.0/libwacom
/usr/include/libwacom-1.0/libwacom/libwacom.h
```

**Comment by jigpu** [comment]
Thanks. Looks like there's no trace of a /usr/local version, which is good news. Does the control center work normally after a reboot, or do you have to `killall` again?

**Comment by aleksejs-fomins** [comment]
I reinstalled gnome-control-center, ubuntu-desktop and xorg. I'm not sure it was necessary. Just that I might have screwed something else up and my computer was freezing at login when I restarted. But when I reinstalled all of these from shell now everything boots normally, settings tab opens from the first try (no killall) and I can see the tablet

**Comment by jigpu** [comment]
That's great news. I'll close the issue since it seems to be resolved.
