### ISSUE TITLE
Yoga Y1 Gen 5 stylus not recognized

### ISSUE THREAD

**Issue by mathsen** [linuxwacom/libwacom#344]
Hello,

I have a Yoga X1 Gen 5 convertible and the stylus works, but is not detected in GNOME's configuration panel.
On the stylus I see the serial number "SD60M68134".

In my journal the pen seems to get detected:

kernel: input: Wacom Pen and multitouch sensor Pen as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/0003:056A:5229.0001/input/input14
kernel: input: Wacom Pen and multitouch sensor Finger as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/0003:056A:5229.0001/input/input15
kernel: wacom 0003:056A:5229.0001: hidraw0: USB HID v1.11 Mouse [Wacom Co.,Ltd. Pen and multitouch sensor] on usb-0000:00:14.0-6/input0

I have also uploaded system infos [here in this wacom-hid-descriptors issue](https://github.com/linuxwacom/wacom-hid-descriptors/issues/135)

Maybe someone can help here - if further information is required I can of course provide this.

**Comment by jigpu** [comment]
I've opened #345 to add a tablet definition for your device. Please try saving [this file](https://raw.githubusercontent.com/linuxwacom/libwacom/2ba9087f506b73032a862ef70e65de93074f0652/data/isdv4-5229.tablet) as `/usr/share/libwacom/isdv4-5229.tablet` and then rebooting.

**Comment by mathsen** [comment]
@jigpu Thanks for the support! Your file works great, the stylus gets recognized with your new file, as expected! Thanks for the fast help!
