### ISSUE TITLE
Wacom Intuous S New stylus isn't detected

### ISSUE THREAD

**Issue by Carpfire** [linuxwacom/libwacom#349]
`<!--`
**NOTE:** libwacom is a descriptive library and has no effect on the
tablet events. Only file a bug for libwacom if the tablet works but does not
show up in GNOME's configuration panel.

If your tablet does not work, please follow the instructions here:
  https://github.com/linuxwacom/libwacom/wiki/Troubleshooting
-->

After accidentally losing the stylus that came with my Intuous S (Which worked great) I have bought a new Wacom Pen 2k from Amazon. However I have no ability ot use it with the Wacom tablet. In settings it still display the old stylus as the one to configure and when running xsetwacom --list devices 

```
Wacom Intuos S Pen stylus       	id: 12	type: STYLUS    
Wacom Intuos S Pad pad          	id: 13	type: PAD       
Wacom Intuos S Pen eraser       	id: 21	type: ERASER    
Wacom Intuos S Pen cursor       	id: 22	type: CURSOR 
```

wacom-list-local-devices produces this 

```
`# Device node: `/dev/input/event8``
[Device]
Name=Wacom Intuos S
ModelName=CTL-4100
DeviceMatch=usb:056a:0374;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
#338 Left=
 Right=
Top=A;B;C;D;

# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=

EvdevCodes=0x100;0x101;0x102;0x103;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
# Device node: /dev/input/event7
[Device]
Name=Wacom Intuos S
ModelName=CTL-4100
DeviceMatch=usb:056a:0374;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
`# StatusLEDs=`
NumStrips=0
Buttons=4

[Buttons]

# Left=
# Right=

Top=A;B;C;D;

# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=

EvdevCodes=0x100;0x101;0x102;0x103;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0
```

Thanks for any help

**Comment by Pinglinux** [comment]
Your pen probably is the root cause. All the information you provided only tells us that your tablet is recognized. Please follow the steps here: https://github.com/linuxwacom/input-wacom/wiki/Analysing-kernel-events to see if you get any events from the pen.

**Comment by jigpu** [comment]
Can you double-check the pen that you purchased? The 2K pen (model LP190K) is not compatible with the CTL-4100; you would need to use a 4K pen (model LP1100K). The two look similar, but the placement of "Wacom" is notably different: on the 2K it is at the end of the pen, on the 4K it is next to the buttons.

* [Wacom Pen 2K](https://estore.wacom.com/en-US/wacom-pen-2k.html)
* [Wacom 4K Pen for Intuos](https://estore.wacom.com/en-US/accessories/accessories-pens/wacom-pen-4k-lp1100k.html)

**Comment by Carpfire** [comment]
You're correct I purchased the wrong pen. Whoops.
