### ISSUE TITLE
[help needed] updating instalation to add support for a new tablet to libwacom

### ISSUE THREAD

**Issue by raphaelchinchilla** [linuxwacom/libwacom#364]
Sorry if the question is dumb, but I just spent a good amount of time trying to figure out what to do and could not.

I am using Ubuntu 20.04 with the libwacom version that is shipped by the distro.

Support to my tablet was added a couple of days ago #360 

I have downloaded the .tablet file from /data/ and copied it to /usr/share/libwacom/

According to the readme.md instructions, my next step should be:
**When updating an installed version of libwacom,** add it manually to the existing ruleset (/lib/udev/rules.d/65-libwacom.rules)

I have no idea how to add to the rule set. My device still does not appear when I run libwacom-list-local-devices

**Comment by whot** [comment]
See #366 for updated instructions please

**Comment by raphaelchinchilla** [comment]
I closed it because I thought it fixed it, but it did not... Still no results after running `libwacom-list-local-devices`

**Comment by whot** [comment]
what does `udevadm info /sys/class/input/eventXX` say about the device? `eventXX` is the event node for the device, alternatively you can use `libinput record` on most modern systems, that also includes the udev properties needed.

**Comment by raphaelchinchilla** [comment]
I have it in two events.


```

P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.3/2-1.3:1.0/0003:256C:006D.0007/input/input25/event10
N: input/event10
L: 0
S: input/by-path/pci-0000:00:1d.0-usb-0:1.3:1.0-event
S: input/by-id/usb-256c_006d-event-if00
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.3/2-1.3:1.0/0003:256C:006D.0007/input/input25/event10
E: DEVNAME=/dev/input/event10
E: MAJOR=13
E: MINOR=74
E: SUBSYSTEM=input
E: USEC_INITIALIZED=1122359473
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_VENDOR=256c
E: ID_VENDOR_ENC=256c
E: ID_VENDOR_ID=256c
E: ID_MODEL=006d
E: ID_MODEL_ENC=006d
E: ID_MODEL_ID=006d
E: ID_REVISION=0000
E: ID_SERIAL=256c_006d
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030102:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.3:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_3_1_0
E: XKBLAYOUT=br,us
E: XKBVARIANT=,
E: BACKSPACE=guess
E: LIBINPUT_DEVICE_GROUP=3/256c/6d:usb-0000:00:1d.0-1
E: DEVLINKS=/dev/input/by-path/pci-0000:00:1d.0-usb-0:1.3:1.0-event /dev/input/by-id/usb-256c_006d-event-if00
E: TAGS=:power-switch:
```


and

```
P: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.3/2-1.3:1.0/0003:256C:006D.0007/input/input25/event10
N: input/event10
L: 0
S: input/by-path/pci-0000:00:1d.0-usb-0:1.3:1.0-event
S: input/by-id/usb-256c_006d-event-if00
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.3/2-1.3:1.0/0003:256C:006D.0007/input/input25/event10
E: DEVNAME=/dev/input/event10
E: MAJOR=13
E: MINOR=74
E: SUBSYSTEM=input
E: USEC_INITIALIZED=1122359473
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_VENDOR=256c
E: ID_VENDOR_ENC=256c
E: ID_VENDOR_ID=256c
E: ID_MODEL=006d
E: ID_MODEL_ENC=006d
E: ID_MODEL_ID=006d
E: ID_REVISION=0000
E: ID_SERIAL=256c_006d
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030102:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:1d.0-usb-0:1.3:1.0
E: ID_PATH_TAG=pci-0000_00_1d_0-usb-0_1_3_1_0
E: XKBLAYOUT=br,us
E: XKBVARIANT=,
E: BACKSPACE=guess
E: LIBINPUT_DEVICE_GROUP=3/256c/6d:usb-0000:00:1d.0-1
E: DEVLINKS=/dev/input/by-path/pci-0000:00:1d.0-usb-0:1.3:1.0-event /dev/input/by-id/usb-256c_006d-event-if00
E: TAGS=:power-switch:
```

PS:
Also I should have mentioned it before: the device works in the sense that since I installed digimend-kernel-drivers, it is recognized, for instance if I run
```
xsetwacom --list devices
HID 256c:006d Touch Strip pad   	id: 12	type: PAD       
HID 256c:006d Pad pad           	id: 15	type: PAD       
HID 256c:006d stylus            	id: 17	type: STYLUS  
```
My goal when I started this was to make the Ubuntu/Gnome Settings recognize the device so that I could easily configure it. It is starting to become more complicated than using the command line to do it so if it becomes a waste of time for you, just let it go =).

**Comment by whot** [comment]
```
E: ID_INPUT=1
E: ID_INPUT_KEY=1
```
This indicates that `ID_INPUT_TABLET` which is handled through the hwdb database isn't set correctly. Without that, libwacom won't pick it up and the rest follows from there. The issue is thus that the hwdb match doesn't work, so something in #366 was forgotten, either by me or by you :)

I wrote a blog post ages ago about [updating the hwdb](http://who-t.blogspot.com/2019/02/adding-entries-to-udev-hwdb.html) which has more info but unfortunately debugging this is painful because all the tools are terrible. I think you're better off just trying to update to a newer libwacom version that includes the fix out-of-the-box.

**Comment by raphaelchinchilla** [comment]
I think I did exactly as you told me, here is the file:

```
  GNU nano 4.8              99-libwacom-new-tablet.hwdb  

libwacom:name:*:input:b0003v256cp006d*
 ID_INPUT=1
 ID_INPUT_TABLET=1
 ID_INPUT_JOYSTICK=0

libwacom:name:* Finger:input:b0003v256cp006d*:
 ID_INPUT_TOUCHPAD=1

libwacom:name:* Pad:input:b0003v256cp006d*:
 ID_INPUT_TABLET_PAD=1
```
what is not clear for me is, shouldn't the ID in ID_INPUT, etc, match those that I get when I run `--xsetwacom --list devices`?

Anyway, I am going to read your blog post out of curiosity! Thanks for the help =). A bit annoying that Canonical does not update libwacom by itself and I have to do all of this.

**Comment by whot** [comment]
change the hex codes to *uppercase*, that should do the trick.

`xsetwacom` is really just a tool for whether the xorg wacom driver is in use. `ID_INPUT_*` is at the udev level, libwacom is on the side, it's not used by the X driver. So the various tools are quite different.

**Comment by raphaelchinchilla** [comment]
Still nothing. I think at this point we can let it go. 

Thanks for the support though :). If you ever have an idea of what could it be, let me know.
