### ISSUE TITLE
cross-compilation support

### ISSUE THREAD

**Issue by Mindavi** [linuxwacom/libwacom#365]
Hey, I was looking at getting cross-compilation working (for aarch64 in this case) for nixpkgs since libwacom is a dependency of one of the packages I'm trying to compile (libinput, which is in turn a dependency of phoc). However, it seems like libwacom doesn't support cross-compilation completely due to a small oversight in the meson.build file; generators (which should run on the build platform) are not tagged with `native: true`, which signals to meson that the build machine compiler and environment should be consulted instead of that of the host (/target) machine.

I'm trying to do this within the nixpkgs repository, but that shouldn't really matter to you.

I've made a patch, but I think it terrible, so I'd like to hear how this could be done in a cleaner way (or if not, I'd like to hear that too). However, it seems like it at least successfully compiles with this patch and the correct dependencies setup, so there's that.

Also: if we can figure out a nice way to do this, are patches for cross-compilation accepted?

Main thing here is that the 'build' and 'host' platforms should be properly distinguished, all the way up the dependency chain (afaict).

<details><summary>The patch in question</summary>

```diff

diff --git a/meson.build b/meson.build
index 32ef797..282d9ab 100644
--- a/meson.build
+++ b/meson.build
@@ -45,9 +45,11 @@ cflags = cc.get_supported_arguments(
 add_project_arguments(cflags, language: 'c')
 
 # Dependencies
-pkgconfig   = import('pkgconfig')
-dep_gudev   = dependency('gudev-1.0')
-dep_glib    = dependency('glib-2.0')
+pkgconfig      = import('pkgconfig')
+dep_gudev      = dependency('gudev-1.0')
+dep_glib       = dependency('glib-2.0')
+build_dep_gudev = dependency('gudev-1.0', native: true)
+build_dep_glib  = dependency('glib-2.0', native: true)
 
 includes_include = include_directories('include')
 includes_src = include_directories('libwacom')
@@ -68,6 +70,10 @@ deps_libwacom = [
            dep_glib
 ]
 
+build_deps_libwacom = [
+           build_dep_gudev,
+           build_dep_glib
+]
 inc_libwacom = [
             includes_include,
             includes_src,
@@ -87,7 +93,22 @@ lib_libwacom = shared_library('wacom',
                                '-DDATADIR="@0@"'.format(dir_data),
                              ],
                              install: true)
+build_lib_libwacom = shared_library('wacom-for-generator',
+                             src_libwacom,
+                             include_directories: inc_libwacom,
+                             dependencies: build_deps_libwacom,
+                             version: libwacom_so_version,
+                             link_args: version_flag,
+                             link_depends: mapfile,
+                             c_args: [
+                               '-DG_LOG_DOMAIN="@0@"'.format(meson.project_name()),
+                               '-DDATADIR="@0@"'.format(dir_data),
+                             ],
+                             install: false,
+                             native: true)
+
 dep_libwacom = declare_dependency(link_with: lib_libwacom)
+build_dep_libwacom = declare_dependency(link_with: build_lib_libwacom)
 
 install_headers('libwacom/libwacom.h', subdir: 'libwacom-1.0/libwacom')
 
@@ -135,10 +156,11 @@ tools_cflags = ['-DTOPSRCDIR="@0@"'.format(meson.source_root())]
 
 gen_hwdb = executable('generate-hwdb',
                      'tools/generate-hwdb.c',
-                     dependencies: [dep_libwacom, dep_glib],
+                     dependencies: [build_dep_libwacom, build_dep_glib],
                      include_directories: [includes_src],
                      c_args: tools_cflags,
-                     install: false)
+                     install: false,
+                     native: true)
 custom_target('hwdb',
              command: gen_hwdb,
              capture: true,

```

**Comment by whot** [comment]
Ok, so the problem here seems to be that `generate-hwdb` which is run as part of the build mustn't be cross-compiled since it's run as part of the build process and thus runs on the build machine, not the host machine (I'd like to stick to [meson's terms here](https://mesonbuild.com/Cross-compilation.html)).

The patch looks correct enough here, but I also wonder whether a much simpler solution here would be to switch the `generate-hwdb` tool to Python. All it needs to do is run through the directory and extract the matches from the .tablet files. @jigpu, any opinion here?

**Comment by Mindavi** [comment]
I don't really mind which way you want to go, however it does seem like less work to apply the patch (I've updated it to use build_ prefixes now). I don't really like the repetition of what's around it, but maybe this is the only way to do it with meson, not really sure. It does make it obvious though.

I'm not really sure if it's that easy to change the generate-hwdb tool, it seems to link to the whole library (as far as I understand). I'd think that that is done because it requires stuff from the library and rewriting everything might be quite involved. Anyhow, this is the first time I see this codebase so forgive my ignorance.

**Comment by Mindavi** [comment]
Great, thanks for looking at this and resolving.

This all seems to work and we can now cross-compile properly. We do have to patch the shebang line to the correct interpreter, but in principle we always have to do that in nixpkgs anyway (since it's replaced with a path to the nix store in `/nix/store/...`.

I don't know if it would be logical to try to find the 'native' python in meson and call the tool with that during build (so something like `find_program(python3, native: true)` and then calling the tool with that)? That would prevent relying on the shebang line for finding the correct python. Not sure if that's logical, but it does seem reasonable. I think that would prevent any need for patching before running the build.
