### ISSUE TITLE
not all Huion H950Ps use the same Device ID

### ISSUE THREAD

**Issue by Big-FG** [linuxwacom/libwacom#379]
While this isnt something you guys can remedy I did feel it was necessary to report it to make it known to you and to the community is that not all H950P devices use the same ID.

Many of the Huion H950P ID with  256c:006d but some like in the case of mine use 256c:006e. This is some weirdness on Huions part but requires select users to have to edit the huion-h950p.tablet and huion-new-1060-plus.tablet to reflect the specific ID for their system so the H950p in question doesnt try to be a 1060+ and you can have the proper button layout.

While it will still work OOTB when it is identified as a 1060+ but setting up buttons can be a bit different . Also of note is that the top and bottom buttons are flipped on the pen in settings for the 256c:006e model of H950P (not sure if this is ALL of them though)

EDIT:

Fixing it for these models you need to swap DeviceMatch= in the new-1060 and the H950P .tablet files

in the H950P file change
`DeviceMatch=usb:256c:006d` -> `DeviceMatch=usb:256c:006e:HID 256c:006e Pen;usb:256c:006e:HID 256c:006e Pad`

and vice versa for the 1060+ file

**Comment by whot** [comment]
I wonder: the best solution here may just be to allow devices in `/etc/` to contain duplicate matches - this way you only have to drop one `.tablet` file into that folder (and given the weirdness with HUION devices we don't have much choice on that) without having to fix up system files.

**Comment by Big-FG** [comment]
> I wonder: the best solution here may just be to allow devices in `/etc/libwacom` to contain duplicate matches - this way you only have to drop one `.tablet` file into that folder (and given the weirdness with HUION devices we don't have much choice on that) without having to fix up system files.

Im not sure this is within the scope of this project but maybe some way to select which model you have? I use Gnome so may have to put in something with them in that case but Im not 100% sure. Being able to select the model you have would seem easy in theory but not sure about in practice trying to add that.

**Comment by whot** [comment]
Theoretically possible, but it balloons out very quickly. It's a hardware device so you shouldn't need to select it, the whole raison d'etre of libwacom is that we know which tablet it is (and what the tablet can do). Having a selection option means having to write the GUI code including storing all this *somewhere*. And there are a few users of libwacom where that's simply not feasable - libinput for example can't pop up a selection dialog.

It's (luckily) a bit of a niche case currently only affecting a few devices, so having an option to make libwacom behave correctly OOTB for all its users is simpler, both in terms of development but also for users.

**Comment by Big-FG** [comment]
@whot yeah i figured as much, looking at that commit seems like an good enough solution to dealing with this sorta issue when it pops up. Its not hard for a user in this edge case to add the file in /etc/libwacom

**Comment by Big-FG** [comment]
I suppose another question, is there a simple way to swap the pen button positions so theyre correct in the gnome settings and not swapped? Its not a big deal as you just set the pen differently in the settings and i assume that this is because of HUION probably changing the pen somehow and them not supporting anything but being a generic pen

**Comment by whot** [comment]
the position of the buttons is only in the SVG, libwacom itself doesn't expose (or know) that information. To swap them, you'd have to swap the two button IDs in the SVG itself - doable and you can link to your own custom SVG in the `.tablet` file but that's not something quite as trivial as copy/pasting a `tablet` file to /etc.

**Comment by Big-FG** [comment]
@whot thats easy enough for me, ill figure it out thank you

**Comment by whot** [comment]
no, the SVG is actually part of libwacom and it has [fixed requirements](https://github.com/linuxwacom/libwacom/blob/master/data/layouts/README.md). gnome settings just relies on those to render it which is why swapping `ButtonA` with `ButtonB` should do the trick here (for the visual configuration anyway).

**Comment by Big-FG** [comment]
> no, the SVG is actually part of libwacom and it has [fixed requirements](https://github.com/linuxwacom/libwacom/blob/master/data/layouts/README.md). gnome settings just relies on those to render it which is why swapping `ButtonA` with `ButtonB` should do the trick here (for the visual configuration anyway).

Ill try going through the documentation and see if i can figure it out, this stuff with the SVG is a bit beyond me atm and im not gonna waste your time on a trivial issue. I havent been able to find an SVG for the stylus itself or how to make that properly just yet so my ignorance to this stuff is the blocker atm

**Comment by whot** [comment]
*facepalm*

I'm sorry - yes, the stylus drawing is (iirc) a gnome thing, we don't provide the svg for that. sorry, got so focused on the buttons that I thought only of the pad buttons which is what we provide the SVGs for. sorry for the noise

**Comment by Big-FG** [comment]
@whot no worries, youve done more than enough :+1:
