### ISSUE TITLE
Add Toshiba Portege X20W-D Convertible and Toshiba TruPen

### ISSUE THREAD

**Issue by tom0105** [linuxwacom/libwacom#41]
Hello, I created a model description file (libwacom/data) for the Toshiba Portege X20W-D Convertible and Toshiba TruPen.

The isdv4-502a.tablet file (unfortunately as .txt, because .tablet could not be uploaded): [isdv4-502a.txt](https://github.com/linuxwacom/libwacom/files/2366575/isdv4-502a.txt)

```
# Toshiba Portege X20W-D Convertible and Toshiba TruPen

[Device]
Name=Wacom ISDv4 50a2
DeviceMatch=usb:056a:50a2
Class=ISDV4
Width=11
Height=6
IntegratedIn=Display;System

[Features]
Stylus=true
Touch=true
Buttons=0
```

This is the output from:  `sudo lsusb | grep Wacom`

```
Bus 001 Device 002: ID 056a:50a2 Wacom Co., Ltd
```

I added `Class=ISDV4` to the description file, although it does not appear in the above output.
I did this based on the previously added convertibles.

After moving the isdv4-502a.tablet to /usr/share/libwacom/ the device appears in the gnome-settings panel under wacom tablets.

**Comment by whot** [comment]
Looks good, thanks. The class tag is a historical leftover anyway, no-one really uses it afaik. Can you submit this as pull request? Would be the easiest way to handle everything with the right attributions.
