### ISSUE TITLE
Support HP Pavilion Convertible 14-dw1xxx Pen(ELAN:2513)

### ISSUE THREAD

**Issue by kuroehanako** [linuxwacom/libwacom#416]
I made custom .tablet file and tested on GIMP. Here is screenshot.
![Screenshot from 2021-07-26 19-43-58](https://user-images.githubusercontent.com/78864678/126979972-b707cab2-055c-483d-b720-ef2198dd410d.png)

and custom .tablet file.

```
# ELAN touchscreen/pen sensor present in the HP Pavilion x360 Convertible 14-dh0xxx

# sysinfo.6IzIUhfUYF
# https://github.com/linuxwacom/wacom-hid-descriptors/issues/163#issue-936701718

[Device]
Name=ELAN 2513
ModelName=
DeviceMatch=i2c:04f3:2b5f
Class=ISDV4
Width=12
Height=7
IntegratedIn=Display;System

[Features]
Stylus=true
Touch=true
Buttons=0
```

![Screenshot from 2021-07-26 19-54-37](https://user-images.githubusercontent.com/78864678/126980392-d53be262-5f31-44fb-b345-56056eeee2b4.png)

Tablet works well. except Gnome Settings Wacom Tablet menu.

Can you add tablet file?

**Comment by whot** [comment]
Fixed in #417
