### ISSUE TITLE
Dell Latitude 7320 Detachable with Active Pen (PN7320A)

### ISSUE THREAD

**Issue by thekswenson** [linuxwacom/libwacom#432]
I have a new Dell Latitude 7320 Detachable. The pen does intermitently work modulo a bug (https://github.com/linuxwacom/input-wacom/issues/281). It does not show up in the Wacom configuration for Gnome settings, however. I submitted a HID descriptor here: https://github.com/linuxwacom/wacom-hid-descriptors/issues/174

Thank you!

**Device name**

> ...
7320 Detachable Active Pen

**Device model identifier**

> ...
 PN7320A

**udevadm info output**

P: /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-WCOM49A3:00/0018:056A:49A3.0001/input/input9/event4
N: input/event4
L: 0
S: input/by-path/pci-0000:00:15.0-platform-i2c_designware.0-event-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-WCOM49A3:00/0018:056A:49A3.0001/input/input9/event4
E: DEVNAME=/dev/input/event4
E: MAJOR=13
E: MINOR=68
E: SUBSYSTEM=input
E: USEC_INITIALIZED=2709083
E: ID_INPUT=1
E: ID_INPUT_TABLET=1
E: ID_INPUT_WIDTH_MM=274
E: ID_INPUT_HEIGHT_MM=182
E: ID_SERIAL=noserial
E: ID_PATH=pci-0000:00:15.0-platform-i2c_designware.0
E: ID_PATH_TAG=pci-0000_00_15_0-platform-i2c_designware_0
E: LIBINPUT_DEVICE_GROUP=18/56a/49a3:i2c-WCOM49A3:00
E: DEVLINKS=/dev/input/by-path/pci-0000:00:15.0-platform-i2c_designware.0-event-mouse

**Comment by jigpu** [comment]
Pull request opened as #458

**Comment by jigpu** [comment]
Pull request merged. Tablet definition can be found [here](https://raw.githubusercontent.com/jigpu/libwacom/8c56e779819d9bf16661f1d18e0a74dc26406fd1/data/isdv4-49a3.tablet) and saved to `/usr/share/libwacom` while waiting for the next release.
