### ISSUE TITLE
One by wacom

### ISSUE THREAD

**Issue by RomanSilinenko** [linuxwacom/libwacom#440]
HI.
Sorry, it is rather a request for some extended functionality. Not sure it is the right place. 
It is possible somehow to map a tablet to just a fraction of a monitor?

**Device name**
One by wacom

> ...

**Device model identifier**

> ...
CTL-472

**udevadm info output**

**Comment by whot** [comment]
in X you can set the transformation matrix directly ([first link i found](https://wiki.ubuntu.com/X/InputCoordinateTransformation)). In Wayland it depends what your compositor exposes (if at all) and the popular ones do not expose the matrix afaik

**Comment by RomanSilinenko** [comment]
Hello. Thank you a lot for directing me to the subject.
