### ISSUE TITLE
Support for ZBook G5 Convertible

### ISSUE THREAD

**Issue by Popkultur** [linuxwacom/libwacom#46]
Hi,

is support possible for this type of Convertible? It has Wacom built in.

**Comment by whot** [comment]
adding it to libwacom is simple enough, just create a data file (check your `/usr/share/libwacom` directory and start with a matching one). Use the `evtest` output to get the VID/PID for the DeviceMatch and the name, the rest is fairly simple. The [wiki](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting) has a bit more here.

If the tablet doesn't work however, then we need to add kernel support first. In that case, please file an issue with the [input-wacom](https://github.com/linuxwacom/input-wacom) project first.

**Comment by jigpu** [comment]
Please file an issue at https://github.com/linuxwacom/wacom-hid-descriptors/issues/, being sure to attach the tarball generated by running our [sysinfo.sh script](https://github.com/linuxwacom/wacom-hid-descriptors/blob/master/scripts/sysinfo.sh). This will give us all the relevant information for your device.

**Comment by whot** [comment]
closing, no updates since last october and the instructions are all here.
