### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by nnawata** [linuxwacom/libwacom#461]
I am using Intuous(s) on Linuxmint20.3, however, my system does not recognize the tablet.

lsusb shows below;
> Bus 001 Device 005: ID 056a:0374 Wacom Co., Ltd CTL-4100 [Intuos (S)]

But, `gnome-control-center` does not, neither `xsetwacom --list`

Then, I tired to install libwacom following the instructions here.
https://github.com/linuxwacom/libwacom/wiki

At the moment of, 
>./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu/
>make

Ive got the following error messages, but I dont know how to resolve it.
>$ ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu/
>autoreconf: 'configure.ac' or 'configure.in' is required

Am I missing any important steps? Or any other solutions to let my system ecognize the tablet?

**Comment by whot** [comment]
See [building with meson](https://github.com/linuxwacom/libwacom/wiki#building-with-meson) if you're building from git master
