### ISSUE TITLE
 HP ProBook X360 11 G5 EE

### ISSUE THREAD

**Issue by MSmolarz** [linuxwacom/libwacom#465]
**Device name**

>  HP ProBook X360 11 G5 EE

**Device model identifier**

> elan-2a70

I don't know how to make a Pull Request so I can't push my changes there.
I've written the .tablet description for my HP ProBook X360 11 G5 EE below.
[elan-2a70.tablet.zip](https://github.com/linuxwacom/libwacom/files/7864543/elan-2a70.tablet.zip)
I would be happy if it is included in library.

This is the related issue for wacom-hid-descriptors:
https://github.com/linuxwacom/wacom-hid-descriptors/issues/185

Thanks
Mark

**Comment by whot** [comment]
thanks for the issue but please don't attach zip files, just copy/paste the file and it's easier to view and comment. a zip file just adds several layers of clicking for no benefit. or, even better, spend the time to figure out how to file a github PR because we're all hopelessly overloaded :(

**Comment by jigpu** [comment]
Closed by #466
