### ISSUE TITLE
Creating a new *.tablet file (huion-h610x) and buttons only work in a tty

### ISSUE THREAD

**Issue by Matthew-Tate-Scarbrough** [linuxwacom/libwacom#468]
As stated.  None of the 8 buttons on the actual tablet/pad work.  Of the 2 button stylus (regular tip, middle click, then right-click), the top button does not work on the stylus.

While they do not work on X, strangely, they do work when dropping into a tty, albeit they return as keycodes.  For instance, button A in a tty returns "b".  I use the `dvorak-programmer` layout, so by default it actually returns `x`.

I should also mention that hitherto, I have had to add a file, `50-tablet.conf`, to `X11/xorg.conf.d` in order for X to see the tablet and it work.
I have not thought to remove that and restart X and see if it will work.

On that note, `xinput list`  does not show the tablet itself.  It shows an `eraser` and a `stylus`, but not a `pad` like with my old drawing tablet and I think most:

```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   [...]
⎜   ↳ HUION Huion Tablet_H610X stylus         	id=14	[slave  pointer  (2)]
⎜   ↳ HUION Huion Tablet_H610X eraser         	id=23	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ [...]
```

I have attached both the \*.tablet file and the file I added to xorg.conf.d.  I don't think that there are any errors in it.  It was initially just based off the `huion-610-pro` file, as they are the same tablet—this is just a USB-C version.  It needs not mentioning, but I have changed their extensions from \*.{conf,tablet} to \*.tx

[huion-h610x.txt](https://github.com/linuxwacom/libwacom/files/7938288/huion-h610x.txt)

[50-tablet.txt](https://github.com/linuxwacom/libwacom/files/7938290/50-tablet.txt)

- - - -

Edit: After reading through a few other issues, I found that the issues are related to the hardware.
The buttons actually send keycodes rather than BTN_0–BTN_7.

```
event14 - HUION Huion Tablet_H610X: libinput bug: missing tablet capabilities: resolution. Ignoring this device.
event15 - HUION Huion Tablet_H610X: libinput bug: missing tablet capabilities: xy pen btn-stylus resolution. Ignoring this device.
```

**Comment by raghu-kamath** [comment]
Hi @Matthew-Tate-Scarbrough I have the same tablet, Can you tell me what to do for the buttons to work?
