### ISSUE TITLE
Installing an older version (1.12.1) with autotools broke my system

### ISSUE THREAD

**Issue by SimoneGirardi** [linuxwacom/libwacom#482]
I have an ubuntu 18.04 LTS system on an asus tuf portable computer and an Intuos BT S CTL-4100WL. Both the tablet and the pen works (almost entirely) without the need of extra software. I tried to install "libwacom" to be able to use the 4 tablet buttons. After following the install guide with autotools for the 1.12.1 version of libwacom my system was no longer able to open the settings tab. I disinstalled then libwacom by following the instructions but, after rebooting the computer, the system wasn't able to boot (even in recovery mode and with a different kernel) because it was no longer able to check the filesystem. I also tried to run the filesystem check from the root command line but with no results, my computer wasn't able to perform it no more.

**Comment by whot** [comment]
From the [FAQ](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work): "libwacom is a glorified database for information that the kernel device does not provide (e.g. whether it is integrated into the screen or not). libwacom has no effect on whether the device works or not."

If libwacom bails out with an error, this *may* affect the gnome session. This can happen if there are duplicate devices in the database for exampe. It's hard to tell what the exact issue is without any logs though.

If you are struggling to do a filesystem check that means something else has gone significantly wrong, maybe your HD is dying (if you're on a 4 year old system that is likely the MTBF of your hardware).

**Comment by SimoneGirardi** [comment]
My pc isn't that old fortunately, I have an nvme as drive. I checked for duplicated diveces and found one that shouldn't be there, so I followed the guide but with no luck.. So, what should I do in order to make my tablet visible into the gnome settings?

**Comment by whot** [comment]
`libwacom-list-local-devices` shows the devices libwacom matches for on your local system - what's the output of that? Any errors there will hint to what's wrong with the local setup. 

Notably: if you just installed a new libwacom over the system libwacom on 18.04, renamed data files may mean you have a mess in `/usr/share/libwacom` now of old and new files (likely the cause for that duplicate). I'd recommend removing the .tablet files in that directory and installing the ones from 1.12.1 instead.

**Comment by SimoneGirardi** [comment]
It worked! Thank you so much for your time!
