### ISSUE TITLE
HP ProBook x360 435 G8

### ISSUE THREAD

**Issue by blk-ole** [linuxwacom/libwacom#483]
**Device name**
HP ProBook x360 435 G8

**Device model identifier**
3Z6Q9ES#ABD

Related to #424 

The suggested solution in the linked issue does not work for me, as the descriptor files of the G7 do not work for my tablet. The touch screen of the device works fine, but the stylus support is not working. When using my stylus (HP Pro Pen, only two buttons), the buttons are not working and cannot be remapped.

Could someone help me with writing a working description file?

**udevadm info output**
https://github.com/linuxwacom/wacom-hid-descriptors/issues/204

**Comment by whot** [comment]
what does `libwacom-list-local-devices` show for the device?

**Comment by blk-ole** [comment]
`# libwacom-list-local-devices `
`/dev/input/event15 is a tablet but not supported by libwacom`
`Failed to find any devices known to libwacom.`

**Comment by whot** [comment]
Have a look at the `data/elan-24d8.tablet` file in the libwacom repo. That's for the G7 of that same laptop, it's likely that there's not a huge amount of difference to the G8. Copy that file, rename to whatever the device advertises itself as (`2da1` from a quick peek at the sysinfo output) and change the `DeviceMatch` line accordingly. And maybe any of the other fields if needed.

That should do the trick for libwacom, but note that libwacom is just a database, adding it will not make the device *work*, merely show up in those tools that query libwacom (like the GNOME settings).

**Comment by blk-ole** [comment]
Sorry for the late reply, I have been fairly busy with private stuff.

I tried to write a tablet file, but it didn't really change anything about the behavior.
It seems to be correct for me though.

Attached is the tablet file (just replace .log with .tablet; .tablet files are not allowed as attachment)
[elan-2da1.log](https://github.com/linuxwacom/libwacom/files/8859389/elan-2da1.log)

**Comment by whot** [comment]
Can you file a pull request for this one please? Thanks

**Comment by whot** [comment]
Closing, please file a pull request for this tablet file, thanks.
