### ISSUE TITLE
Touchscreen HP Pavilion x360 Convertible 14-ba0xx

### ISSUE THREAD

**Issue by serhumanos** [linuxwacom/libwacom#488]
**Device name**

> Touchscreen HP Pavilion x360 Convertible 14-ba0xx

**Device model identifier**

>  ELAN0732:00 04F3:2522 (?)

**udevadm info output**

P: /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-ELAN0732:00/0018:04F3:2522.0001/input/input46/event4
N: input/event4
L: 0
S: input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event
E: DEVPATH=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-ELAN0732:00/0018:04F3:2522.0001/input/input46/event4
E: DEVNAME=/dev/input/event4
E: MAJOR=13
E: MINOR=68
E: SUBSYSTEM=input
E: USEC_INITIALIZED=10335560
E: ID_INPUT=1
E: ID_INPUT_TOUCHSCREEN=1
E: ID_INPUT_WIDTH_MM=300
E: ID_INPUT_HEIGHT_MM=172
E: ID_PATH=pci-0000:00:15.1-platform-i2c_designware.1
E: ID_PATH_TAG=pci-0000_00_15_1-platform-i2c_designware_1
E: LIBINPUT_DEVICE_GROUP=18/4f3/2522:i2c-ELAN0732:00
E: DEVLINKS=/dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event

The sysinfo data is in [this issue](https://github.com/linuxwacom/wacom-hid-descriptors/issues/199).
Thanks!

**Comment by whot** [comment]
Please file a pull request for the tablet data file, there's a simliar one in `data/elan-2513.tablet` which should work well as a guide
