### ISSUE TITLE
Assign Buttons Wacom Intuos Pro M

### ISSUE THREAD

**Issue by crchmatefis** [linuxwacom/libwacom#496]
After installing Ubuntu 22.04(wayland and xorg), I tried to assign keystrokes to the buttons of my wacom tablet, but, the system does not let me select the option, in general it does not let me select any of the options. Has anyone an idea how to fix it?

Note: in ubuntu 20.04 I could assign keystrokes to each button on my tablet.

**Comment by whot** [comment]
libwacom is merely a database with a C API, it does not do the mapping or any functionality.

Unless libwacom says your tablet has no buttons, the actual mapping is handled by either the wacom X11 driver or the wayland compositor. Closing in favour of https://github.com/linuxwacom/xf86-input-wacom/issues/271
