### ISSUE TITLE
Stylus setting not show after upgrade to Ubuntu 18.04

### ISSUE THREAD

**Issue by sonvirgo** [linuxwacom/libwacom#50]
Device ISDv4 104, built in 2ic Wacom digitizer pen stylus
Stylus setting center used to work on 17.10 downward
Stylus no longer detected in Setting after upgrade to Ubuntu 18.04

**Comment by whot** [comment]
does `libwacom-list-local-devices` show the tablet correctly? Does it work?

**Comment by sonvirgo** [comment]
> does `libwacom-list-local-devices` show the tablet correctly? Does it work?

Yet it work well except stylus button, no way to configure.
Btw I figure something out: change setting in American Trend bios to custom default.
Will test it to night and report back.

**Comment by sonvirgo** [comment]
Update, I try again, messing something in BIOS, then load CUSTOM DEFAULT the tablet and  stylus did actually work flawless at boot.
But however, no stylus setting in Setting Center.
I suspect the issues relate to NO ERASER STYLUS. As I use a new one.
My old pen with eraser is just dead, which show in Setting Center in 17,04 as in this https://youtu.be/GaX797u1MpI?t=120

**Comment by sonvirgo** [comment]
Solved the issue by also install from source x86-input-wacom.
