### ISSUE TITLE
Erro autoreconf: 'configure.ac' or 'configure.in' is required

### ISSUE THREAD

**Issue by cristianofmc** [linuxwacom/libwacom#502]
I can not install the lib
autoreconf: 'configure.ac' or 'configure.in' is required
![Screenshot from 2022-07-02 15 54 23](https://user-images.githubusercontent.com/27186405/177013065-64ec4f7a-5627-48b5-b332-c838909bea95.png)

**Comment by whot** [comment]
autotools support was removed in 67f24d60dbd6cf20fa99ee635afa560678f1b710, so you need to build with meson now, see [the wiki](https://github.com/linuxwacom/libwacom/wiki#building-with-meson). I've removed `autogen.sh` now in #503, this was a leftover, thanks.
