### ISSUE TITLE
Documentation update?

### ISSUE THREAD

**Issue by thismatters** [linuxwacom/libwacom#51]
I'm going through the install procedure listed here https://github.com/linuxwacom/libwacom/wiki and ran into some dependencies that needed to be installed before the build would work, namely (for lubuntu 18.04): `autoconf` and `libtool`. Once those were installed everything worked fine for me. Thanks for your effort in maintaining this!

**Comment by whot** [comment]
did you use the `sudo apt-get build-dep libwacom` command? If so, I'd say that's a ubuntu issue if the build-deps don't pull in autotools because without those, building is rough...

**Comment by jigpu** [comment]
Looks like anything in the "build-essentials" package [may be omitted](https://www.debian.org/doc/debian-policy/ch-relationships.html#relationships-between-source-and-binary-packages-build-depends-build-depends-indep-build-depends-arch-build-conflicts-build-conflicts-indep-build-conflicts-arch) from the "Build-Depends" entry. I've updated the doc to include "build-essentials".
