### ISSUE TITLE
Request for tablet definition file creation - Lenovo Yoga 900S-12ISK 

### ISSUE THREAD

**Issue by Iskatu** [linuxwacom/libwacom#513]
An issue in wacom-hid-descriptors, containing the sysinfo: https://github.com/linuxwacom/wacom-hid-descriptors/issues/213

Result of the `libwacom-list-local-devices` command:

>/dev/input/event10 is a tablet but not supported by libwacom
>Failed to find any devices known to libwacom.

**Device name**

> Lenovo Yoga 900S

**Device model identifier**

> 900S-12ISK

**udevadm info output**

> P: /devices/pci0000:00/0000:00:15.3/i2c_designware.2/i2c-3/i2c-ELAN21EF:00/0018:04F3:2283.0001/input/input17/event10
N: input/event10
L: 0
S: input/by-path/pci-0000:00:15.3-platform-i2c_designware.2-event-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:15.3/i2c_designware.2/i2c-3/i2c-ELAN21EF:00/0018:04F3:2283.0001/input/input17/event10
E: DEVNAME=/dev/input/event10
E: MAJOR=13
E: MINOR=74
E: SUBSYSTEM=input
E: USEC_INITIALIZED=6670738
E: ID_INPUT=1
E: ID_INPUT_TABLET=1
E: ID_INPUT_WIDTH_MM=275
E: ID_INPUT_HEIGHT_MM=156
E: ID_SERIAL=noserial
E: ID_PATH=pci-0000:00:15.3-platform-i2c_designware.2
E: ID_PATH_TAG=pci-0000_00_15_3-platform-i2c_designware_2
E: LIBINPUT_DEVICE_GROUP=18/4f3/2283:i2c-ELAN21EF:00
E: DEVLINKS=/dev/input/by-path/pci-0000:00:15.3-platform-i2c_designware.2-event-mouse

**Comment by whot** [comment]
Please file a pull request for the tablet file, the `data/isdv4-5110.tablet` file is for a smiliar model and should work fine as guide
