### ISSUE TITLE
Upload public key of release signature to keyserver

### ISSUE THREAD

**Issue by langfingaz** [linuxwacom/libwacom#528]
Thanks for providing a PGP signature for the releases.

At the moment I did not find the corresponding public key on any keyserver. Have you thought of uploading it to a keyserver? This would allow automatic fetching of the key and verification of the signature when building a distribution specific libwacom package.

The [libwacom-surface package in the Arch User Repository](https://aur.archlinux.org/packages/libwacom-surface) does already include the PGP signature. But one has either to manually import the public key (e.g. from https://github.com/Joshua-Dickens.gpg) or use `--skippgpcheck` when building it.

**Comment by Joshua-Dickens** [comment]
Hi there, my apologies I had recently made the key due to having a new system and forgot to upload it to a public key server. Yesterday I uploaded it to the Ubuntu keyserver and should be available from there. Apologies for the initial issues.

**Comment by langfingaz** [comment]
No worries, thanks for the quick reply and your work on this project. I can confirm that fetching the key does now work.
