### ISSUE TITLE
Graphic Tablet settings in Linux Mint 21 (Ubuntu 20.04) does not show PTH-660 Wacom Pro M

### ISSUE THREAD

**Issue by Mint-me123** [linuxwacom/libwacom#529]
I have problems getting my Wacom Intuos Pro M PTH-660 (the model called 2 in the .svg and .tablet files) to come up in the Graphics Tablet settings windows on a Linux Mint 21 (Vanessa equiv to Ubuntu 22.04). The tablet is working, as in the STYLUS and TOUCH is working but I can't customise it as shown on a youtube video where the svg image just pops up and buttons and ring action can be assigned as easy as. The Graphics Tablet settings shows that it has found the tablet but gives a generic list of 9 buttons which doesn't react to any input. I can list the devices with xsetwacom and I can assign buttons (not the ring) with xsetwacom too. I have made scripts which can run xsetwacom settings but I would think using the Graphics Tablet GUI which comes with Mint 21 would make things easier and more complete (like the ring and toggle button in the ring). The libwacom installation went fine in the end.  I used meson to build and I got one red NO for missing Valgrind. I selected sources in the sources settings, I cloned the git, I build the dependencies. I installed Valgrind. I installed the git files again - all green. I tested for duplicates and found 2 files had doubles. All commands were copy paste from the github. I compared the 4 duplicates (was for the PTH-651 and the PTH-660) in Meld and both only had one change - an added entry under STYLUS which was @propengen2. I removed the older versions (the two without propengen2) manually as the explanation in the troubleshooting guide left me perplexed. I tested again with no db error. I restarted. No joy. I cannot see the tablet layout or assign buttons. I am stuck basically. I have started from scratch 3 times with a new git clone, build etc. I ran the test bash ./run-full-test.sh and had one error Pytest timed out but in the beginning of the test python3-pytest is found so perhaps an invoking error in the script? Only thing that is perplexing is that the libwacom terminal installation shows the version to be the latest 2.5.0 but when I check in synaptic it has a much older version 2.2.0 listed as the only version available. The idea of uninstalling from synaptic to see if that "helps" fills me with dread when I see what is also removed (looks like half the OS). So what to do? Needless to say I have lived on google, forums and gits for a few days now to sort it but no. I am sure it is a small mistake I have done somewhere (or not done) but I don't know what - where. 
![youtube](https://user-i
![GraphicsTabletMint](https://user-images.githubusercontent.com/61146241/199013280-99f64988-c30e-403d-b773-180b82c452fb.png)
mages.githubusercontent.com/61146241/199013206-ce9c675d-61e6-4108-aac0-3aa98fdf55e5.png)
![gitlibwacom250](https://user-images.githubusercontent.com/61146241/199013230-75e9f053-cec4-4610-ac28-0c2b36b8eeaf.png)
![synaptic220](https://user-images.githubusercontent.com/61146241/199013249-0352b670-44cf-48f7-bebc-82772d19a07f.png)

**Comment by Pinglinux** [comment]
We don't need two tickets to track the same issue. Close this one so we focus on the latest report.

**Comment by Mint-me123** [comment]
My apologies.
I made a mistake on the first one and I thought I could edit but I must
have erred somehow and actually made a new one.
