### ISSUE TITLE
Trying to include Wacom BambooFun 4x5 Pad (CTE-450)

### ISSUE THREAD

**Issue by txelu** [linuxwacom/libwacom#54]
I'm trying to create the .tablet file for old Bamboo Fun 4x5 as it was detected and operational by Linux but missing from the gnome-control-center and libwacom. I started from the already existing "bamboo-0fg-s-p.tablet" file, which seems to be a very similar tablet but with code MTE-450 and a stylus with no rubber.
I created a new file, modified the values for Name and DeviceMatch according to the output of evtest (Name=Wacom BambooFun 4x5 Pad, DeviceMatch=usb:056a:0017) and copied that new file to /usr/share/libwacom. 
After that libwacom detects my tablet, but it shows twice the same info ([libwacom-list-local-devices.txt](https://github.com/linuxwacom/libwacom/files/2592979/libwacom-list-local-devices.txt)). I don't know if that's normal or not, but the problems I have right now are:
 * gnome-control-center **doesn't show any stylus**, so I can't configure buttons. I didn't add any stylus to the Styili parameter in .tablet file, the same of the others bamboo tablets.
 * gnome-control-center does shows the  also shows the tablet, but when I try to map the **buttons they are not correctly detected**: when I click the button A, it detects button D; when I click B, nothing happens; when I click C, it detects A; and when I click D, it detects C.

Of course, I checked the key codes using evtest clicking each button and I could confirm the that the codes for the MTE-450 models are correct for the CTE-450 ([keys_pad.txt](https://github.com/linuxwacom/libwacom/files/2592990/keys_pad.txt), [keys_stylus.txt](https://github.com/linuxwacom/libwacom/files/2592991/keys_stylus.txt)).
 * Button A = 278 (0x116)
 * Button B = 277 (0x115)
 * Button C = 272 (0x110)
 * Button D = 273 (0x111)

I don't know what I'm doing wrong. Any help will be appreciated because I really want to be able to use this tablet. I included here the .tablet I've created ([bamboo-0fg-s-p-alt.tablet.txt](https://github.com/linuxwacom/libwacom/files/2592996/bamboo-0fg-s-p-alt.tablet.txt), extension .txt is only for github allow me to upload the file).

In case it's needed I'm using Arch Linux with:
  * Kernel 4.19.2-arch1-1-ARCH
  * Gnome 3.20.2
  * libwacom 0.32-1

**Comment by jigpu** [comment]
Hi! It looks like you've done everything correctly, and that the issues you're seeing are all (unfortunately) known issues.

- The tablet being listed multiple times by `libwacom-list-local-devices` is just an artifact of how your device appears to the system and is perfectly normal.

- The issue of no stylus appearing is https://bugzilla.gnome.org/show_bug.cgi?id=793499

 - The issue of the buttons being incorrectly detected is https://bugzilla.gnome.org/show_bug.cgi?id=770464

If you'd like to let the GNOME developers know that you're affected by these two bugs, you can reply to them. You try using the `xsetwacom` command in the meantime until these issues are worked out (and putting the commands into a script once you get them worked out), though I know there's occasionally issues with GNOME Control Center overriding the xsetwacom settings.

If you'd like, I can commit your version of the bamboo-0fg-s-p-alt.tablet file to our repository, though I'll need a formal "sign-off" to apply to it. See [here](https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin) for an overview of what it means, and if you're okay with it, just reply back with the `Signed-off-by: Random J Developer <random@developer.example.org>` line I should put into the commit message. If not, I can recreate a similar file easily enough :)

**Comment by txelu** [comment]
HI Jason!

Thanks a lot for your quick help. I was puzzled by the behaviour of the
Gnome Control Center, but those two bugs were very clarifying.
If you want to commit the .tablet file I create the "sign-off" line would
be:

Signed-off-by: Jose Luis Tirado <joseluis.tirado@gmail.com>

Best regards

**Comment by itubmv** [comment]
Hi, I have a similar problem with Wacom Graphire CTE-640/S.

I have added .tablet-file for specified Wacom version, but cannot program buttons in gnome-control-center. Nor can I use tablet in GIMP. In gnome environment the cursor appears (menus and control center), in GIMP it is invisible.   

My question is to txeIu: "checked the key codes using evtest clicking each button and I could confirm the that the codes for the MTE-450 models are correct for the CTE-450".
- Can you tell how you found code for key-pad and key-pen?
- Do you think the same approach can help program Wacom Graphire?


I use pen and tablet to graphics drawing and photo editing. Just changed from Ubuntu 16.04 to Suse Leap 15.0. So kind of leaning this as I read along.

- Kernel 4.12.14-lp150.12.25.1
- Gnome 3.26.2
- libwacom 0.29-1.42

**Comment by txelu** [comment]
First of all, check the [Linux Wacom Project page](https://linuxwacom.github.io/). Adding a .tablet file is only the latest step. In my case the tablet was detected by the OS, but I was missing from the Gnome control center, so I couldn't configure it. This is exactly what the [libwacom troubleshooting page](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting) says:

> Follow the steps below if your tablet works but does not show up in the GNOME Control Center. If the tablet does not work, then the issue is either in the kernel or in the xf86-input-wacom driver.

So, if that's your case, and you need to find out the key codes follow this steps:

1. FInd out the device of the tablet: `sudo evtest` with no arguments will show the description of all the input devices. In my case, among others, it showed:
```
/dev/input/event16:	Wacom BambooFun 4x5 Pen
/dev/input/event17:	Wacom BambooFun 4x5 Pad
```
2. So I entered '17' to the question `Select the device event number [0-31]:`, getting then the following output:
```
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x56a product 0x17 version 0x100
Input device name: "Wacom BambooFun 4x5 Pad"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 277 (BTN_FORWARD)
    Event code 278 (BTN_BACK)
    Event code 331 (BTN_STYLUS)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value      0
      Min        0
      Max        1
    Event code 1 (ABS_Y)
      Value      0
      Min        0
      Max        1
    Event code 8 (ABS_WHEEL)
      Value      0
      Min        0
      Max       71
    Event code 40 (ABS_MISC)
      Value      0
      Min        0
      Max        0
Properties:
Testing ... (interrupt to exit)
```
The event codes for the buttons where exactly the same of those in the already existing  "bamboo-0fg-s-p.tablet" file, in this case in decimal format, instead of hexadecimal, but the same values. For instance, Button A = BTN_BACK = 278 in evtest, but 0x116 in .tablet file.
At this point you can also check the event codes of each button by pressing them. You should get something like this:
```
Event: time 1543267604.036496, type 1 (EV_KEY), code 278 (BTN_BACK), value 1
Event: time 1543267604.036496, type 3 (EV_ABS), code 40 (ABS_MISC), value 15
Event: time 1543267604.036496, -------------- SYN_REPORT ------------
Event: time 1543267604.124486, type 1 (EV_KEY), code 278 (BTN_BACK), value 0
Event: time 1543267604.124486, type 3 (EV_ABS), code 40 (ABS_MISC), value 0
Event: time 1543267604.124486, -------------- SYN_REPORT ------------

```
Those traces correspond to the press and release of button A in my tablet.

**Comment by jigpu** [comment]
@txelu I've opened a pull request to add the tablet file. It should be accepted soon.

@itubmv it sounds like the pen works in most of the OS, but not GIMP? If that's the case I'd check two things...

First, make sure that you aren't running a Wayland-based session. The easiest way to do that is to just run `xsetwacom list` and make sure that your tablet is listed. If nothing appears, you're in a Wayland session and should try to switch to an Xorg session at the login screen.

The second thing to check is that GIMP has been configured to use the pen. Go to Edit -> Input Devices, select the stylus device in the list at the left, and make sure the mode is set to "Screen". You'll want to also set the mode for the eraser device as well. GIMP will treat the tablet like a mouse until you make these changes.

I'm going to close this bug, but feel free to open a new one if the answers from me or txelu don't help.
