### ISSUE TITLE
Can libwacom work on FreeBSD for "XP-Pen Star G640" drawing pad?

### ISSUE THREAD

**Issue by rajhlinux** [linuxwacom/libwacom#540]
Hello,

Is it possible I can use FreeBSD to install "libwacom" and have it work for "XP-Pen Star G640" drawing pad?

If so, what are the steps to do so?

Thanks

**Comment by whot** [comment]
We have a CI job that builds on freebsd, so I'm assuming this means "yes", see https://github.com/linuxwacom/libwacom/blob/master/.github/workflows/freebsd.yml. And the G640 seems to be in our data files, so I'd say once you installed libwacom, `libwacom-list-local-devices` should show the device.

Note that libwacom is a C library around a bunch of text files, it doesn't make the tablet work, it merely provides some extra info not available from the device itself.

**Comment by rajhlinux** [comment]
Thanks for you reply.

I have installed libwacom via FreeBSD ports:
https://www.freshports.org/x11/libwacom

When I enter: `libwacom-list-local-devices`

I get no return of anything on terminal.

Thanks.

**Comment by whot** [comment]
No idea then, sorry. I don't know anything much about the BSDs. That tool just iterates through `/dev/input/event*` and tries to get the udev info for each to find a VID/PID match. Since FreeBSD doesn't use event nodes by default I'm really not sure how this would work there, maybe it's patched? I don't know.

**Comment by rajhlinux** [comment]
Alright. Thanks.

**Comment by rajhlinux** [comment]
I'm trying to figure out how I can install the CI job.

I asked the FreeBSD forum and they stated that the libwacom drivers on the the FreeBSD port seems to be outdated. Thankfully it seems like libwacom has an implementation to install it on FreeBSD.

I did some googling about CI jobs and it seems immensely involved.

Are there any simple commands to get it installed using CI job?

Thanks.

**Comment by whot** [comment]
CI jobs are *not* what you need in your case. Just run the five commands  in `prepare` and `run` in your terminal and that will do what the CI does. Plus a `meson install -C builddir` (also, you probably need to specify `--prefix` in `meson setup`)

**Comment by rajhlinux** [comment]
Alright. Thank You.

**Comment by rajhlinux** [comment]
I have removed the old libcom 1.5 installation, however FreeBSD then completely fails to read the keyboard and mouse inputs after a reboot. So I have no choice but to reinstall libwacom 1.5

I then installed the github libcom 2.5 by doing the following:
$ git clone https://github.com/linuxwacom/libwacom.git
$ cd libwacom
$ meson setup builddir && cd builddir
$ meson compile
$ meson test
$ su
$ meson install
$ exit

I did a reboot and now when I enter: `libwacom-list-local-devices`

I get the return below:

```
(libwacom-list-local-devices:1614): libwacom-CRITICAL **: 22:34:40.052: Duplicate match of 'usb:256c:006e:Tablet Monitor Pen' on device 'GAOMON S56K'.
Failed to initialize device database
```

Thanks.
