### ISSUE TITLE
Thinkpad x12 detachable and Lenovo Precision Pen

### ISSUE THREAD

**Issue by johnledezma34** [linuxwacom/libwacom#541]
**Device name**

> ... Thinkpad x12 detachable 

**Device model identifier**

> ...  Thinkpad x12 i3 version

**udevadm info output**

P: /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-1/i2c-WACF2200:00/0018:056A:525C.0005/input/input26/event14
M: event14
R: 14
U: input
D: c 13:78
N: input/event14
L: 0
S: input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-1/i2c-WACF2200:00/0018:056A:525C.0005/input/input26/event14
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event14
E: MAJOR=13
E: MINOR=78
E: USEC_INITIALIZED=6994419
E: ID_INPUT=1
E: ID_INPUT_TABLET=1
E: ID_INPUT_WIDTH_MM=259
E: ID_INPUT_HEIGHT_MM=172
E: ID_SERIAL=noserial
E: ID_PATH=pci-0000:00:15.1-platform-i2c_designware.1
E: ID_PATH_TAG=pci-0000_00_15_1-platform-i2c_designware_1
E: LIBINPUT_DEVICE_GROUP=18/56a/525c:i2c-WACF2200:00
E: DEVLINKS=/dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse

**Comment by johnledezma34** [comment]
I can also provide my /bus/input txt file and my sysinfo.sh file. I don't really know if that is the udev data required. I just got the one for the wacom hid 525 pen

**Comment by johnledezma34** [comment]
Would I also need to add anything related to the pen itself? The pen is a lenovo precision pen, it has 3 buttons, 2 side buttons and a top clicker button.

**Comment by whot** [comment]
Please have a look at [the wiki here](https://github.com/linuxwacom/libwacom/wiki/Tablet-Definition-Files), thanks

**Comment by johnledezma34** [comment]
> Please have a look at [the wiki here](https://github.com/linuxwacom/libwacom/wiki/Tablet-Definition-Files), thanks

I did thanks and I submitted the tarball. Hopefully something happens, although I saw that my device actually got submitted in sep 2022 and the issue remains open with no replies by devs  🙁

**Comment by whot** [comment]
Can you link to the sysinfo issue please? That one doesn't need to be merged, as long as we have the link, that's good enough.

And you should be able to get a data file by taking a similar one and copying it + modifying it accordingly.

**Comment by johnledezma34** [comment]
> Can you link to the sysinfo issue please? That one doesn't need to be merged, as long as we have the link, that's good enough.
> 
> And you should be able to get a data file by taking a similar one and copying it + modifying it accordingly.

 Here's mine. 
https://github.com/linuxwacom/wacom-hid-descriptors/issues/285

Here's another issue from sep 2022 with my hardware
https://github.com/linuxwacom/wacom-hid-descriptors/issues/254

**Comment by whot** [comment]
I'm gonna go out on a limb here and guess that you can take `data/isdv4-5256.tablet` and copy it, then change the few bits to update to your device. That should do the trick, unless your device is significantly different.

Unfortunately we're all overloaded, so submitting an MR for a tablet file is the most effective way to get this into libwacom.

**Comment by whot** [comment]
Please see https://github.com/linuxwacom/libwacom/wiki/Adding-a-new-device

Closing this, it needs a pull request so we can merge the `.tablet` file but there's no need to keep the issue open. Please file the PR and we can get it in quickly.
