### ISSUE TITLE
using a wacom stylus on a thinkpad yoga x1 running ubuntu

### ISSUE THREAD

**Issue by francispoulin** [linuxwacom/libwacom#547]
**Device name**

wacom stylus

**Device model identifier**

?? 

**udevadm info output**

I am trying to configure a wacom stylus on my thinkpad yoga x1 running ubuntu 22.  The built in stylus is awful and the wacom one feels great, I know as I also have a wacom tablet.  Can someone help me figure out how to set this up?  

I am very sorry for the silly question here.

**Comment by francispoulin** [comment]
I should add that when I check the local devices I get a message that my tablet (monitor) is not supported by libwacom.  Does that mean I need to help create one?

```
$ libwacom-list-local-devices
/dev/input/event7 is a tablet but not supported by libwacom
Failed to find any devices known to libwacom.
```

**Comment by whot** [comment]
libwacom is merely a text database with a C API wrapper, it has no effect on whether the device works - merely whether it's mapped to the screen correctly, etc. So if the stylus doesn't work at all, it's either a hw issue (stylus incompatible?) or a kernel-side issue.

What does `libinput record` say about that device? Can you please **attach** the output here when you use the stylus?

**Comment by francispoulin** [comment]
Thanks for the reply @whot , and sorry if I am asking the question in the wrong place. 

When I try libinput record, I see 23 events, and there is only one wacom pen, but that is the build in one. 

I asked Lenovo and they said that it should be comptabible but also mentioned they don't help set things up with linux.  Maybe this is a lost cause as it could very well be a hardware issue?

**Comment by whot** [comment]
can you attach the `libinput record` output please? that'll give us some idea of what's going on

**Comment by francispoulin** [comment]
Sorry for the late reply on my part.  I need to get my notifications sorted out.  But here are the results from `libinput record`.  My wacom stylus doesn't appear anywhere but the one that appears, eveng7?, is the built in one.  I really want to learn how to use my better stylus with this computer because otherwise it's not really usable.

```
Available devices:
/dev/input/event0:	Sleep Button
/dev/input/event1:	Lid Switch
/dev/input/event2:	Power Button
/dev/input/event3:	AT Translated Set 2 keyboard
/dev/input/event4:	Dell KB216 Wired Keyboard
/dev/input/event5:	Integrated Camera: Integrated C
/dev/input/event6:	TPPS/2 Elan TrackPoint
/dev/input/event7:	Wacom HID 52B5 Pen
/dev/input/event8:	Wacom HID 52B5 Finger
/dev/input/event9:	Logitech USB Optical Mouse
/dev/input/event10:	Intel HID events
/dev/input/event11:	SYNA8017:00 06CB:CEB2 Mouse
/dev/input/event12:	SYNA8017:00 06CB:CEB2 Touchpad
/dev/input/event13:	ThinkPad Extra Buttons
/dev/input/event14:	Integrated Camera: Integrated I
/dev/input/event15:	Dell KB216 Wired Keyboard System Control
/dev/input/event16:	Dell KB216 Wired Keyboard Consumer Control
/dev/input/event17:	Video Bus
/dev/input/event18:	DP-3
/dev/input/event19:	sof-hda-dsp Mic
/dev/input/event20:	sof-hda-dsp Headphone
/dev/input/event21:	sof-hda-dsp HDMI/DP,pcm=3
/dev/input/event22:	sof-hda-dsp HDMI/DP,pcm=4
/dev/input/event23:	sof-hda-dsp HDMI/DP,pcm=5
```

**Comment by whot** [comment]
fwiw, the stylus isn't it's own device so it won't show up as a kernel device. The built-in tablet is the device (`event7` in the listing above) and when you use a different stylus on this tablet, the events will come through that device.

Where supported, the events will have information to *identify* the stylus. That information is then used by e.g. libinput to create a new tablet tool for use by the Wayland compositor but that is all userspace only.

**Comment by fenugrec** [comment]
to rule out software config problems, you could try downloading a live-CD (like ubuntu studio, which comes with drawing software and - I assume - good default configs for tablets etc)

**Comment by whot** [comment]
Going to close this one - we still don't have a libinput record from the device and the above request was unanswered. Please re-open when we have the requested information
