### ISSUE TITLE
GAOMON S620 has duplicates graphic tablet settings in GNOME Settings

### ISSUE THREAD

**Issue by kreaninw** [linuxwacom/libwacom#557]
The issue is caused by the generated `/usr/lib/udev/hwdb.d/65-libwacom.hwdb` file that's missing these lines under `# GAOMON S620`:

```
libwacom:name:* Dial:input:b0003v256Cp006D*
 ID_INPUT_TABLET_PAD=1

libwacom:name:* Touch Strip:input:b0003v256Cp006D*
 ID_INPUT_TABLET_PAD=1
```

See more about this issue: GNOME Settings issue [#2018](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2018) and [#2019](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2019). This issue has the same cause as issue #556. Therefore, fixing issue #556 will also fix this issue.

**Comment by whot** [comment]
Should be fixed with #562 now. Let's hope, anyway :)
