### ISSUE TITLE
hwdb script in udev rules

### ISSUE THREAD

**Issue by ratijas** [linuxwacom/libwacom#564]
My "One by Wacom" tablet does not register a /dev/input/event* device on Arch, and presses are not registered or at least don't work neither on X11 or Wayland on Arch Linux.

I _suspect_ the cause is a `hwdb` invocation in `/usr/lib/udev/rules.d/65-libwacom.rules` file:

```
# use the /sys/class/input/eventXXX/device/modalias as lookup key, prefixed
# by libwacom:<device name>:
# This lookup key is a contract between the udev rules and the hwdb entries.
# It is not considered public API and may change.
KERNELS=="input*", \
  IMPORT{builtin}="hwdb --subsystem=input '--lookup-prefix=libwacom:name:$attr{name}:'"
```

First, there was no `hwdb` binary on my system. I found it in `bluez-utils` and installed that package. Then, its man page and manual command invocation did not return anything meaningful for my device.  There's a different binary, `systemd-hwdb`, but its syntax does not match the one used in udev rules either. Is this really a proper command, or is it outdated?

I'm not sure whether it's a packaging error, an outdated script or some other problem in different parts on the stack. I'm new to graphic tablets ecosystem on Linux.  All relevant packages (libwacom, xf86-input-wacom driver) are installed. My device shows up in control panel (KDE System Settings) both on X11 and Wayland, and stylus buttons seem to be configurable. Only touch events don't work.

**Comment by whot** [comment]
`hwdb` is a udev *builtin*, see `systemd/src/udev/udev-builtin-hwdb.c`. Whatever bluez-utils provide is completely unrelated. `sytemd-hwdb` is CLI tool to interact with the hwdb but is not the binary that is invoked here.

> My device shows up in control panel (KDE System Settings) both on X11 and Wayland

this means that libwacom works correctly in identifying the device, see `libwacom-list-local-devices`. If the tablet doesn't actually work that's usually a kernel issue or sometimes an X driver issue. But all data files we have for "one by wacom" devices set `Touch=false` which leads me to believe that that device doesn't support touch.

**Comment by ratijas** [comment]
Somehow I was under impression that "Touch" is for fingers, for tablets with multi-touch screens like smartphones. So I should set it to "true" and try again?  The device works fine on Windows, and IIRC I saw a thread on the internet where someone's saying it works either on Fedora or Ubuntu (haven't tried those yet).

**Comment by whot** [comment]
yes, Touch is for finger-touch like a touchscreen. Changing this to `true` won't have any effect on the *functionality* of the tablet though (see [the wiki](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting)). 

Note that the official [wacom page](https://www.wacom.com/en-us/products/pen-tablets/one-by-wacom) doesn't mention touch either.

**Comment by ratijas** [comment]
> yes, Touch is for finger-touch like a touchscreen. Changing this to true won't have any effect on the functionality of the tablet though (see [the wiki](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting)).

Got it.

There are multiple forum topics all around, indicating that it used to just work™ in past, or even just works™ today on systems other than Arch.

- https://bbs.archlinux.org/viewtopic.php?id=282740
- https://bbs.archlinux.org/viewtopic.php?id=271383
- https://github.com/linuxwacom/input-wacom/issues/242

```
❯ libwacom-list-local-devices
devices:
- name: 'One by Wacom (small)'
  bus: 'usb'
  vid: '0x056a'
  pid: '0x037a'
  nodes: 
  - /dev/input/event9

❯ libwacom-list-local-devices --format=datafile
# One by Wacom (small)
#  - /dev/input/event9
[Device]
Name=One by Wacom (small)
ModelName=CTL-472
DeviceMatch=usb:056a:037a;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Styli=0xffffe;0xfffff;

[Features]
Reversible=true
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=0

---------------------------------------------------------------
```
