### ISSUE TITLE
ASUS ZenBook duo screens no longer recognized as tablets

### ISSUE THREAD

**Issue by mtlg** [linuxwacom/libwacom#566]
After upgrading to Fedora 38, the stylus still works, but the tablets (of the internal monitors) are no longer recognized in the Gnome Settings.

Also, when the second (or an external) monitor is activated, the position is shifted, making it unusable. I used to fix this in the Gnome Settings, but now the Settings > Wacom Tablet say "No tablet detected".

In fact, libwacom-list-local-devices reports:
/dev/input/event18 is a tablet but not supported by libwacom
/dev/input/event8 is a tablet but not supported by libwacom
Failed to find any devices known to libwacom.

The tablets were recognized in Fedora 37 and before.

> rpm -qa \*wacom\*
libwacom-data-2.6.0-1.fc38.noarch
xorg-x11-drv-wacom-serial-support-1.2.0-1.fc38.x86_64
libwacom-2.6.0-1.fc38.x86_64
xorg-x11-drv-wacom-1.2.0-1.fc38.x86_64

**Comment by whot** [comment]
What does `libinput record` say about the tablet,can you attach the output here please? Thanks.

**Comment by mtlg** [comment]
> sudo libinput record
Available devices:
/dev/input/event0:      Lid Switch
/dev/input/event1:      Power Button
/dev/input/event2:      Power Button
/dev/input/event3:      AT Translated Set 2 keyboard
/dev/input/event4:      USB2.0 HD UVC WebCam: USB2.0 HD
/dev/input/event5:      USB2.0 HD UVC WebCam: USB2.0 IR
/dev/input/event6:      ELAN9008:00 04F3:2D55
/dev/input/event7:      ELAN9008:00 04F3:2D55 UNKNOWN
/dev/input/event8:      ELAN9008:00 04F3:2D55 UNKNOWN
/dev/input/event9:      ELAN9008:00 04F3:2D55 Stylus
/dev/input/event10:     ELAN9008:00 04F3:2D55 UNKNOWN
/dev/input/event11:     ELAN9008:00 04F3:2D55 UNKNOWN
/dev/input/event12:     ELAN9008:00 04F3:2D55 UNKNOWN
/dev/input/event13:     ELAN9009:00 04F3:2C1B
/dev/input/event14:     ELAN9009:00 04F3:2C1B UNKNOWN
/dev/input/event15:     ELAN9009:00 04F3:2C1B UNKNOWN
/dev/input/event16:     ELAN9009:00 04F3:2C1B Stylus
/dev/input/event17:     ELAN9009:00 04F3:2C1B Touchpad
/dev/input/event18:     ELAN1200:00 04F3:3168 Mouse
/dev/input/event19:     ELAN1200:00 04F3:3168 Touchpad
/dev/input/event20:     Video Bus
/dev/input/event21:     Video Bus
/dev/input/event22:     PC Speaker
/dev/input/event23:     Asus WMI hotkeys
/dev/input/event24:     sof-hda-dsp Headset Mic
/dev/input/event25:     sof-hda-dsp Headphone
/dev/input/event26:     sof-hda-dsp HDMI/DP,pcm=3
/dev/input/event27:     sof-hda-dsp HDMI/DP,pcm=4
/dev/input/event28:     sof-hda-dsp HDMI/DP,pcm=5
/dev/input/event29:     Logitech Wireless Keyboard PID:4023
/dev/input/event30:     Logitech Wireless Mouse
Select the device event number: 

I also tried downgrading libwacom and libwacom-data to 2.4.0 (the RPMs from Fedora 37, where the tablet was recognized), but got the same behavior (tablet not recognized). Now I'm back to v2.6.0.

**Comment by whot** [comment]
I can't find any entries in libwacom's git log for the `2c1b1 or `2d55` devices, so if that device worked in the past it would've been covered by a fallback handler in mutter/GNOME in general. Maybe that has changed or broken now but from what I can tell this device was never explicitly supported. 

Or the device changed PID in a recent firmware update but that's unlikely, I think.

Either way, fixing this would require a new tablet file for your device, see `data/elan-29a1.tablet` as a reference for a different ZenBook model. Could be used almost as-is, just needs replacing the various pids and references to the model.


Regarding `libinput record` - the list of devices is useful, but what we'll really need (eventually) is the actual output for your device, i.e. you need to select the device - e.g. `16` in the last case. Check which device sends events too, there's a chance only one of either 9 or 16 actually sends events when the stylus is in proximity - that's the one we want.

**Comment by mtlg** [comment]
Thanks for details - I'm not familiar with these tools. :-)

I attach 9.log and 12.log captured through tee while using the stylus at random for a while - today they changed the numbers again.

Note that both 9 and 12 do collect events because the notebook has 2 internal touch- and stylus-sensitive screens. In this case, 9 was sensitive to the main (lid) screen, 12 to the small one, above the keyboard.

To modify the data/elan-29a1.tablet you mention I understand that I need to change
DeviceMatch=i2c:04f3:29a1
into
DeviceMatch=i2c:04F3:2D55
for one display and
DeviceMatch=i2c:04F3:2C1B
for the other, and save each time with a different name in the same directory. I shall also change the Name=. Right?

> libwacom-list-local-devices
/dev/input/event12 is a tablet but not supported by libwacom
/dev/input/event9 is a tablet but not supported by libwacom
Failed to find any devices known to libwacom.

> sudo libinput record
Available devices:
/dev/input/event0:	Lid Switch
/dev/input/event1:	Power Button
/dev/input/event2:	Power Button
/dev/input/event3:	AT Translated Set 2 keyboard
/dev/input/event4:	ELAN9008:00 04F3:2D55
/dev/input/event5:	ELAN9008:00 04F3:2D55 UNKNOWN
/dev/input/event6:	ELAN9009:00 04F3:2C1B
/dev/input/event7:	ELAN9008:00 04F3:2D55 UNKNOWN
/dev/input/event8:	ELAN9009:00 04F3:2C1B UNKNOWN
/dev/input/event9:	ELAN9008:00 04F3:2D55 Stylus
/dev/input/event10:	ELAN9009:00 04F3:2C1B UNKNOWN
/dev/input/event11:	ELAN9008:00 04F3:2D55 UNKNOWN
/dev/input/event12:	ELAN9009:00 04F3:2C1B Stylus
/dev/input/event13:	ELAN9008:00 04F3:2D55 UNKNOWN
/dev/input/event14:	ELAN9009:00 04F3:2C1B Touchpad
/dev/input/event15:	ELAN9008:00 04F3:2D55 UNKNOWN
/dev/input/event16:	ELAN1200:00 04F3:3168 Mouse
/dev/input/event17:	ELAN1200:00 04F3:3168 Touchpad
/dev/input/event18:	Video Bus
/dev/input/event19:	Video Bus
/dev/input/event20:	Logitech Wireless Keyboard PID:4023
/dev/input/event21:	Logitech Wireless Mouse
/dev/input/event22:	PC Speaker
/dev/input/event23:	Asus WMI hotkeys
/dev/input/event24:	USB2.0 HD UVC WebCam: USB2.0 HD
/dev/input/event25:	USB2.0 HD UVC WebCam: USB2.0 IR
/dev/input/event26:	sof-hda-dsp Headset Mic
/dev/input/event27:	sof-hda-dsp Headphone
/dev/input/event28:	sof-hda-dsp HDMI/DP,pcm=3
/dev/input/event29:	sof-hda-dsp HDMI/DP,pcm=4
/dev/input/event30:	sof-hda-dsp HDMI/DP,pcm=5
Select the device event number: 

[12.log](https://github.com/linuxwacom/libwacom/files/11495811/12.log)
[9.log](https://github.com/linuxwacom/libwacom/files/11495812/9.log)
