### ISSUE TITLE
Fujitsu T935 Calibrate taps not recognized anymore in Ubuntu 23.04....

### ISSUE THREAD

**Issue by frohro** [linuxwacom/libwacom#569]
Here is the data for this tablet.  It worked fine previously, but not in Ubuntu 23.04.

```
$ libwacom-list-local-devices
devices:
- name: 'ISDv4 5019'
  bus: 'usb'
  vid: '0x056a'
  pid: '0x5019'
  nodes: 
  - /dev/input/event5
  - /dev/input/event4
```
Calibrate option in Gnome Settings does not appear unless you select Map to Monitor -> Automatic, which may also be related to this problem.  This occurs in both wayland and xorg.  I suspect it to be a problem with how the stylus/tablet is recognized.

Steps to replicate: 

1. Go to Gnome Settings.
2. Select Wacom Tablet on the left.
3. Select Map to Monitor -> Automatic (or the Calibrate option is grayed out)
4. Select Calibrate.
5. Attempt to tap the bullseye with the stylus.
6. Observe the taps are not recognized.

**Comment by frohro** [comment]
I notice an [issue in Gnome](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1871) that deals with this as well.

**Comment by frohro** [comment]
I should mention that the stylus moves the mouse cursor.  The touches to the tablet do not register.  The stylus works  fine in other programs, like xournal++.

**Comment by Pinglinux** [comment]
I think the "Calibrate" issue is in Gnome, especially since the stylus works.

How did you know the device supports touch? Can you share your dmesg output here?

**Comment by frohro** [comment]
The stylus works fine in xournalpp.  There are no messages in dmesg.  

I think it is a combination of updates to the Gnome Settings and the identification provided by libwacom.  Here is why I think that.

1. I was one who was involved in adding this laptop to libwacom, and the entries there were guesses, backed up with testing as to what worked in a previous Ubuntu.  I really suspect one of the parameters I put in was incorrect. 
 It worked fine for that version of Gnome.
2. It stopped working with a new version of Gnome.  
3. The stylus works fine for other applications as far as I can tell.  (This may mean it is a problem with Gnome too.)  In fact when I tap the screen with the stylus the color of the cursor arrow changes from black to Red (I have the red hourglass selected in Gnome Tweeks.), but the calibration is not accepted.  My theory is that Gnome started using something different, which was specified wrongly in the libwacom identifier, but I may be wrong.

**Comment by frohro** [comment]
I did leave a comment on [this bug report](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1871) (same problem) on Gnome.

**Comment by frohro** [comment]
When the cursor changes to red, it appears the very same as if I tried to calibrate by clicking my trackpad instead of using the stylus.  Maybe somehow the gnome-control-center thinks my stylus is a mouse.

**Comment by frohro** [comment]
I messed around with the .tablet file changing all kinds of things (commenting out Styli, or Stylus) and the behavior was the same.  Maybe it is a gnome-control-center bug....

**Comment by whot** [comment]
fwiw, all libwacom does is provide the information that "yes, this is a built-in tablet", nothing more. What happens with this information is up to the callers, i.e. gnome-control-center and/or mutter, depending on what you're looking at.

libwacom doesn't affect the event flow at all, it's just a C library around a bunch of static `.ini`-style files (see the `data/` directory in the source).


>  I really suspect one of the parameters I put in was incorrect.

tbh, I can't see anything in the `data/isdv4-5019.tablet` file that would be wrong or even have an effect on this behaviour. I think the only thing that could be wrong is the stylus IDs but isdv4 tablets don't have unique serials, so that's not it.

Punting this to the control-center, this needs to be debugged there first.
