### ISSUE TITLE
Wacom Cintiq 16 hid-default drivers enabled instead of Wacom

### ISSUE THREAD

**Issue by abyssmal131** [linuxwacom/libwacom#572]
So, I posted this issue initially in input-wacom. I was speaking with someone who could probably lift Mjolnir, as he fixed my problem in less than a day. Here is a link to the issue:

https://github.com/linuxwacom/input-wacom/issues/373

Essentially, that after going through the Linux Wacom Project steps, I still couldn't use my pen. He looked at the results of the my inputting the dmesg command.

From there he saw that my computer was using the hid-default drivers instead of wacom drivers. I was told to input:

sudo rmmod wacom
sudo modprobe wacom

After doing so, my pen started working. The writer asked me to post the issue here, so here I am. I would like to know what happened, and if it happens again (lets say if I were to upgrade Nobara or reinstall it) what would I do?

**Comment by Pinglinux** [comment]
Hi @whot, to save your time, I am pasting the issue relevant to you here:

"So, I have a Cintiq 16 on Nobara Linux (a fedora fork) that doesn't work when I plug it in. The computer sees it, none of my inputs go through/**in settings I can neither calibrate or use the "Test Your Settings" function** or move my pointer at all. "

I fixed the pen doesn't move the cursor issue. You probably can figure out why the tablet doesn't show up in the "Wacom Tablet" panel issue.

**Comment by abyssmal131** [comment]
Well, to clarify, the tablet did show up, just the pen wasn't doing anything. So:

Settings->Wacom Tablet

If I unplug the tablet, it will not show up at all in the settings, but it was plugged in, and I could access "Wacom Tablet" Settings. In the "Test Your Settings" tab, which is like a blank tab that you can test-draw in, nothing was happening.

**Comment by Pinglinux** [comment]
Ok, if you disconnect the tablet, it should be removed from the settings. That's a correct action since the system doesn't have the device anymore. My question is: were you able to draw in the "Test Your Settings" tab before disconnecting the tablet?

Another question is: after you disconnect and reconnect the tablet, was your pen still able to move the cursor?

**Comment by abyssmal131** [comment]
Well, I was referring to before you fixed the issue. Now, everything works completely fine, but when I restart, I have to reinput the commands:

**Comment by Pinglinux** [comment]
Then, it is not a libwacom issue. The "Test Your Settings" issue is in Gnome. The system start/reboot issue is in the system setup itself, which we'll figure out a solution together. 

Sorry for the noise Peter.
