### ISSUE TITLE
Another Yoga 260 USB ID

### ISSUE THREAD

**Issue by frohro** [linuxwacom/libwacom#573]
Hi,
I copied isdv4-5090.tablet to isdv4-5043.tablet and my particular Yoga 260 is recognized by gnome-control-center.  I also tried to use the paired ID as shows in isdv4-ec.tablet, but it did not work for me.  
Do you need a pull request for this?
Thanks,
Rob

**Comment by whot** [comment]
yes, always pull requests please, they run the CI, are easier to review, etc. Thanks
