### ISSUE TITLE
Acer Switch SA5-271P

### ISSUE THREAD

**Issue by amitkeret** [linuxwacom/libwacom#58]
Hi there,
I just wanted to preface (and apologise) my request with admitting that I (really) tried to create a `.tablet` file and make heads or tails from the output from `syslog.sh`. Here's the output: [sysinfo.w2eKVXTjLQ.tar.gz](https://github.com/linuxwacom/libwacom/files/2720951/sysinfo.w2eKVXTjLQ.tar.gz)

I'm sorry but I ran into lots of uncertainties in the process...
I also looked at the file created by @Curious-Octopus on issue #33 but I think that's missing some details.

Some more info that might help with configuring the file:
* The device in question is a touchscreen with stylus. Screen has 4 buttons, stylus has 2 buttons
* At present, both are not recognised by Wacom. Despite this:
  * Touchscreen works, all 4 buttons work as expected (suspend, volume up/down, Windows)
  * Stylus works although had to tweak xinput's `Coordinate Transformation Matrix` when it's rotated 90/180/270 degrees
  * One button on the stylus was recognised as a left mouse-click.

**Device name**
I believe the touchscreen is ELAN 5515
The PC is model SA5-271P running Ubuntu GNOME 18.10, the stylus is model ACS-032

**Device model identifier**
Unclear :( I tried to figure out the bus however I found a few mentions of PCI in the logs, however the other ELAN files say it's I2C. I also could not find the identifier in the kernel log.

**udevadm info output**
This is not present in both my udevadm output files.

This is the best I came up with:
```
[Device]
Name=ELAN 5515
DeviceMatch=??? pci:04F3:2339 or i2c:04F3:2339
PairedIDs=??? should I have this for the pen?
Class=???
IntegratedIn=Display
Styli=???

[Features]
Stylus=true
Reversible=true
Touch=true
Buttons=4

[Buttons]
Left=A;B;C;D
??? should there be definition of the two stylus buttons?
```

I'm happy to try again with a bit of guidance.
Thank you

**Comment by whot** [comment]
> DeviceMatch=??? pci:04F3:2339 or i2c:04F3:2339

the i2c one should be correct (just double-check if we use upper or lower-case hex, I can't remember right now).

> PairedIDs=

shouldn't be needed here because the touchscreen has the same usbid.

> Class=???

Use ISDV4, no-one uses this anyway.

> Styli=

not needed, your stylus doesn't have a serial number (i suspect)

> Reversible=true

Should be 'false' because there's no left-handed mode here

> Buttons=4

skip this, because I doubt the buttons are hooked up like a tablet pad. An evemu-record of the touch and the pen devices should tell us more though.

> ??? should there be definition of the two stylus buttons?

nope, not needed, they should just work. But there's a chance that the second stylus button works as the eraser button and toggles the whole thing into the eraser mode. that may be why it's not sending events.

**Comment by amitkeret** [comment]
@whot thank you so much for your reply.

### (partial) success!
The tablet is recognised. I have the option to calibrate it and that works flawlessly.
However - stylus is still not showing up in Wacom settings. To be clear - it's working alright, just not being recognised by the settings application.

Here's the definition file I've installed:
```
# ELAN touchscreen/pen present in the Acer Switch SA5-271P

[Device]
Name=ELAN 5515
DeviceMatch=i2c:04F3:2339
Class=ISDV4
IntegratedIn=Display

[Features]
Stylus=true
Touch=true
```
Note: I haven't added anything to udev rules. I looked through it and: 1) all other devices there are usb bus, which is not what I have; 2) no other ELAN device is there; 3) I got very confused :(
Could that be part of the problem?

Please help, I'm so close!...

**Comment by amitkeret** [comment]
@whot this is the current output of `libwacom-list-local-devices`:

```
(libwacom-list-local-devices:26643): libwacom-WARNING **: 16:32:50.943: Tablet 'i2c:04f3:2339' has no buttons defined, do something!
[Device]
Name=ELAN 5515
DeviceMatch=i2c:04f3:2339;
Class=ISDV4
Width=0
Height=0
IntegratedIn=Display;
Styli=0xfffff;0xffffe;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=true
TouchSwitch=false
StatusLEDs=
NumStrips=0
Buttons=0
```
So the stylus is being "auto-detected" as `0xfffff;0xffffe;`

Is this the expected result? Is that the ID of a generic pen?
How can I find out if my stylus does/doesn't have a serial number?

**Comment by amitkeret** [comment]
BTW I don't know if this helps, but here's the input from `evemu-record`:
[evemu-record.txt](https://github.com/linuxwacom/libwacom/files/2735465/evemu-record.txt)

**Comment by amitkeret** [comment]
@whot thank you for the helpful relies.

One last thing which I can't figure out from the README / .example file:
Would there be a benefit to actually defining the tablet's buttons? As in, would I be able to configure their actions? That would be nice :)
And if so, where can I find the EvdevCodes? Looks like this would be in the output from evemu-record but I can't be sure. I tried "capturing" button events as well, but they were not printing to stdout.

**Comment by amitkeret** [comment]
@whot bump?
I'd like to get this clarified in order to submit a proper PR

**Comment by whot** [comment]
thanks for the bump, this slipped through. 

The evdev codes are the ones returned by `libinput record`, `evemu-record` or `evtest`, either of them will print out the `EV_KEY` events, the matching code is the evdev code.

but a quick google shows that this thing doesn't have pad buttons (compare to e.g. an Intuos Pro), so `Buttons=0` is it, nothing else needed.

**Comment by amitkeret** [comment]
Thank you for the clarification!
