### ISSUE TITLE
Duplicated entries in Gnome, Samsung Chromebook Plus v2 XE520QAB

### ISSUE THREAD

**Issue by ShapeShifter499** [linuxwacom/libwacom#584]
I've submitted my device info here https://github.com/linuxwacom/wacom-hid-descriptors/issues/318

I've tried creating a tablet file after this issue was fixed, https://github.com/linuxwacom/xf86-input-wacom/issues/317  But I'm getting duplicated entries in Gnome, I'm guessing it's because there are two IDs that are almost the same. But one is for the actual stylus and the other seems to be for detecting the button press on a supported stylus. I'm not sure if I'm missing something or if it's a bug.

`ACPI0C50:00 2D1F:0040 Stylus` vs `ACPI0C50:00 2D1F:0040`

Attached is a screenshot of what I'm seeing in Gnome settings and the tablet file I'm trying to use. 

[isdv4-2d1f-0040.tablet.txt](https://github.com/linuxwacom/libwacom/files/12435978/isdv4-2d1f-0040.tablet.txt)
![Screenshot from 2023-08-24 22-34-21](https://github.com/linuxwacom/libwacom/assets/388665/e0ab544b-8a58-43cd-ae30-780491a6d6b1)

**Comment by whot** [comment]
> ACPI0C50:00 2D1F:0040 Stylus vs ACPI0C50:00 2D1F:0040

if you run `libinput record` as root, does the device *without* the `Stylus` appendix produce any events? What's happening here is that the device has two event nodes, both of which are labeled as tablets (because of the match you currently have) but there's no information that the two are part of the same physical device. So two devices, treated like two individual tablets by GNOME.

Tightening the match to `DeviceMatch=i2c:2D1F:0040ACPI0C50:00 2D1F:0040 Stylus` should do the trick.

**Comment by ShapeShifter499** [comment]
> Tightening the match to `DeviceMatch=i2c:2D1F:0040ACPI0C50:00 2D1F:0040 Stylus` should do the trick.

This did not seem to work for me. I tried two different versions of that string in the attached tablet files and both resulted in Gnome saying no tablet was found. 

[isdv4-2d1f-0040.tablet.v1.txt](https://github.com/linuxwacom/libwacom/files/12454033/isdv4-2d1f-0040.tablet.v1.txt)
[isdv4-2d1f-0040.tablet.v2.txt](https://github.com/linuxwacom/libwacom/files/12454034/isdv4-2d1f-0040.tablet.v2.txt)

The first device doesn't seem to have anything when I bring a stylus to the screen or try to touch the screen with my fingers. Logged from `libinput record` as root: 
[2d1f-0040.txt](https://github.com/linuxwacom/libwacom/files/12454053/2d1f-0040.txt)

The second device lights up with activity when I bring a stylus to the screen. Logged from `libinput record` as root: 
[2d1f-0040_stylus.txt](https://github.com/linuxwacom/libwacom/files/12454058/2d1f-0040_stylus.txt)

**Comment by whot** [comment]
>  both resulted in Gnome saying no tablet was found.

fwiw, once the tablet file is in `/etc/libwacom/` simply running `libwacom-list-local-devices` will show you whether it's detected - if it is it should then also show up in gnome.

and running `libwacom-list-devices` should tell you if the `.tablet` file is picked up correctly (if it is but `list-local` doesn't show the device, the match doesn't take effect).


staring at this a bit: a typo, apologies: there was a `:` missing after `0040`, I've edited https://github.com/linuxwacom/libwacom/issues/584#issuecomment-1694927699 now, the format is `bus:vid:pid:name` so here must be a `:` before `ACPI...`

**Comment by ShapeShifter499** [comment]
With the corrected string, it now appears like it should. 
[isdv4-2d1f-0040.tablet.working.txt](https://github.com/linuxwacom/libwacom/files/12468610/isdv4-2d1f-0040.tablet.working.txt)

![Screenshot from 2023-08-29 02-36-06](https://github.com/linuxwacom/libwacom/assets/388665/9998eb5f-073d-4b20-ab75-3250b0308696)

**Comment by ShapeShifter499** [comment]
@whot thank you for the help
