### ISSUE TITLE
Cintiq Pro 13 Pad is not labeled as ID_INPUT_TABLET_PAD

### ISSUE THREAD

**Issue by whot** [linuxwacom/libwacom#585]
Originally reported in [gnome-control-center#2019](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2019), cc @pinglinux

`tools/libwacom-update-db.py` treats devices without buttons as devices without pads and skips the hwdb entries for the `* Pad` suffix (see [here](https://github.com/linuxwacom/libwacom/blob/master/tools/libwacom-update-db.py#L79)). This results in the respective `Pad` device getting tagged as `ID_INPUT_TABLET` but not `ID_INPUT_TABLET_PAD`, making it appear as if there was more than one tablet connected.

This affects the Cintiq Pro 13, possibly others that don't have buttons but have a Pad event node.

This probably broke in f9cf43e431714240571c2c3b19ab6244f89dbb78, previously we ended up with a generic "* Pad" rule, thus tagging all devices ending in `Pad`.

**Comment by lokman2k5** [comment]
I am still having this issue. libwacom9 package is version 2.10.0-2
Gnome 46, Ubuntu 24.04.1
![Screenshot from 2024-09-08 18-11-25](https://github.com/user-attachments/assets/03dcc1df-ab4d-4d9a-a89a-574ac5d7e32e)

**Comment by whot** [comment]
With a Cintiq Pro 13? What does libwacom-list-local-devices say?
