### ISSUE TITLE
Please add pen support to 52fb

### ISSUE THREAD

**Issue by myviolinsings** [linuxwacom/libwacom#589]
Can we add 52fb support? I just bought the Yoga 6 13ABR8 - Type 83B2 and was finally able to get tablet mode working ONLY in GNOME desktop on Linux Mint. Mine has the AMD processors/graphics. Thought it should work in the other desktops (Cinnamon, KDE, Xfce) but it would not recognize tablet mode.

I added a comment on a previous PR (https://github.com/linuxwacom/libwacom/pull/536) and was asked to add a PR, but I am not sure how to make the required changes. Any help you can provide would be greatly appreciated. If you need more info from me related to my hardware or logs or anything feel free to ask.

Thanks!

**Comment by whot** [comment]
Please see https://github.com/linuxwacom/libwacom/wiki/Adding-a-new-device

**Comment by whot** [comment]
Closing, this needs a PR. we can re-open if there's a specific issue with this device but for now let's just wait on the PR.
