### ISSUE TITLE
Wacom Cintiq 12WX - DTZ-1200 screen detected but not working

### ISSUE THREAD

**Issue by ALEZ-DEV** [linuxwacom/libwacom#596]
I recently installed Zorin OS (with Gnome) on my laptop and I tried to connect my Wacom Cintiq 12WX - DTZ-1200 to have a third screen on my desktop, but few issue come out :
1. when I installed Zorin, gnome was able to detect the tablet screen only in the displays section and I tried to enable it, but I just can't.
2. I made some research and I understood that my tablet was not detected, so I downloaded the libwacom (I downloaded and compiled from source because the apt command was not working) driver and my Intuos tablet was detected but not my cintiq, so I searched if it was missing in the database... and no, it's there

I don't know if I made something wrong or not and if it really a bug or not, but I hope someone out there can help me

**Comment by whot** [comment]
Please see https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work

**Comment by whot** [comment]
closing, this doesn't appear to be a libwacom issue
