### ISSUE TITLE
XP-Pen Deco Pro Medium

### ISSUE THREAD

**Issue by zoqaeski** [linuxwacom/libwacom#599]
**Device name**
XP-Pen Deco Pro Medium

**Device model identifier**
Deco Pro_M

[sysinfo.B6ZaGzjkSu.tar.gz](https://github.com/linuxwacom/libwacom/files/13065727/sysinfo.B6ZaGzjkSu.tar.gz)

**Issue**
This tablet defaults to a vertical orientation, and needs the ability to rotate in order to be useful with a computer.

**Comment by whot** [comment]
Looks like this was added in #552 and it has the `Reversible=true` key set, so from our side this should be done.

Note that libwacom only says "this isn't symmetrical", whether it's rotated or not is actually up to the implementation (libinput, xf86-input-wacom, or whatever else is out there). If the tablet is in a wrong rotation by default, please file a bug with either libinput (if Wayland) or xf86-input-wacom (if X11) and we can debug it there further.

Please also specify the distro and desktop environment you're using, thanks.

**Comment by zoqaeski** [comment]
The Deco Pro M is a different model to the Deco Pro MW. When I plug mine in, the USB identifier is different, which is why I opened this issue with the sysinfo data.

**Comment by whot** [comment]
Unfortunately we don't have the bandwidth anymore to create tablet files ourselves. Please file as issue with https://github.com/linuxwacom/wacom-hid-descriptors for the sysinfo and a PR for a new tablet file here, reviewing and merging is still possible (though with delays, often...)
