### ISSUE TITLE
Support for Wireless Bamboo Pad

### ISSUE THREAD

**Issue by AniMysore74** [linuxwacom/libwacom#6]
I'm trying to add the .tablet configuration file for the Wacom Wireless Bamboo Pad, since it is currently not listed in `usr/share/libwacom` (but it is listed [here](http://linuxwacom.sourceforge.net/wiki/index.php/Device_IDs))

This is the output when I run `sudo cat /proc/bus/input/devices` :

```
I: Bus=0003 Vendor=056a Product=0319 Version=0110
N: Name="Wacom Wireless Bamboo PAD Pen"
P: Phys=usb-0000:00:14.0-1/input0
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:056A:0319.002D/input/input117
U: Uniq=
H: Handlers=mouse0 event6 
B: PROP=1
B: EV=b
B: KEY=c03 0 0 0 0 0
B: ABS=1000003

I: Bus=0003 Vendor=056a Product=0319 Version=0110
N: Name="Wacom Wireless Bamboo PAD Finger"
P: Phys=usb-0000:00:14.0-1/input3
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.3/0003:056A:0319.0030/input/input127
U: Uniq=
H: Handlers=mouse2 event17 
B: PROP=1
B: EV=b
B: KEY=e420 30000 0 0 0 0
B: ABS=260800000000003
```
I am unsure how to find the right button positions and stylus ID. Any help with making the file / adding support for this would be much appreciated.

**Comment by jigpu** [comment]
Tablet definition will be available in the next libwacom release.
