### ISSUE TITLE
PenPower/Huion RemoteGo LCD

### ISSUE THREAD

**Issue by Aqua1ung** [linuxwacom/libwacom#618]
Let me apologize profusely for opening a new issue for the same device, but I realize that you guys are busy people, and may not afford the time to keep up with the deluge of posts in the [previous thread](https://github.com/linuxwacom/libwacom/issues/608), which is why we seem to be talking past each other. This post will summarize my progress in the matter of assimilating the RemoteGo LCD tablet into `libwacom`.

There are two goals to this quest:

1. Figure out the `EVDEV_ABS_xx` parameters in the `hwdb.d/60-evdev.hwdb` file:
```
# PenPower RemoteGo LCD RMGL01
evdev:input:b0003v256Cp5101*
 EVDEV_ABS_00=::?
 EVDEV_ABS_01=::?
```
2. Figure out a way to make the tablet show up in the ["Wacom Tablet" section of Gnome settings](https://i.imgur.com/a7iNWb8.png), if possible.

Here is, again, what **UCLogic reports** about the tablet:
```
dad@DadsGram~/Downloads $ uclogic-decode < probe.txt
    |           Manufacturer: HUION
    |                Product: PenPower RemoteGo LCD Writing Pad
 64 |        Params block #1: ???????????????????????????????????????????????????????????????????????????????????????????????????
    |                          Max X: 8192
    |                          Max Y: 357
    |                   Max pressure: 2273
    |                     Resolution: 2048
    |
 79 |         Internal model: ???????????????????????????????????????????????????????????????????????????????????????????????????
 7b |         Buttons status: ???????????????????????????????????????????????????????????????????????????????????????????????????
 c8 |        Params block #2: ??s?????
    |                          Max X: 42000
    |                          Max Y: 29600
    |                   Max pressure: 8191
    |                     Resolution: 5080
    |
 c9 |       Firmware version: 05OEM_T219_220709
```
And here is a photo of the tablet box:

![box](https://github.com/linuxwacom/libwacom/assets/12104779/95ae44fe-6ec1-40e0-a09c-6820c12e4106)

I have to confess that I find the UCLogic output quite confusing, which is why I keep pressing that you guys let me know what to make of it. In particular, I am not sure what to make of  that `block #1` and `block #2 `stuff: what's with all those `Max` values, and what's the deal with the two resolutions?

Many thanks, and, again, apologies for being so persistent. The good news, as I said, is that the system recognizes the tablet, and the stylus moves the computer cursor, which is more that I had ever hoped.

**Comment by whot** [comment]
>    Figure out the EVDEV_ABS_xx parameters in the hwdb.d/60-evdev.hwdb file:

measure it to get the right size in mm, then look at the `libinput record` output for `ABS_X` and `ABS_Y`. Resolution is `(max - min)/size-in-mm` for each axis separately. Should be 200 units/mm if the package doesn't lie, see [this comment](https://github.com/linuxwacom/libwacom/issues/608#issuecomment-1862136831) for the calculation.

Example from my touchpad which is 98mm: `(3052 - 0)/98 == 31.4` hence a resolution of 31.
```
    # Event type 3 (EV_ABS)
    #   Event code 0 (ABS_X)
    #       Value        2606
    #       Min             0
    #       Max          3052
    #       Fuzz            0
    #       Flat            0
    #       Resolution     31
```

the params block #1 looks like the pen pressure so you can ignore that.

> Figure out a way to make the tablet show up in the ["Wacom Tablet" section of Gnome settings](https://i.imgur.com/a7iNWb8.png), if possible.

You need a `.tablet` file added to libwacom, as per [the wiki](https://github.com/linuxwacom/libwacom/wiki/Adding-a-new-device)

**Comment by Aqua1ung** [comment]
> measure it to get the right size in mm,

I measured it, and it's precisely what the box says: 148x210 mm.

>then look at the `libinput record` output for `ABS_X` and `ABS_Y`.

Here's what `libinput record` says:
```
    # Event type 3 (EV_ABS)
    #   Event code 0 (ABS_X)
    #       Value       18712
    #       Min             0
    #       Max         32767
    #       Fuzz            0
    #       Flat            0
    #       Resolution     20
    #   Event code 1 (ABS_Y)
    #       Value       12005
    #       Min             0
    #       Max         32767
    #       Fuzz            0
    #       Flat            0
    #       Resolution     30
```
Hence I am guessing that `hwdb.d/60-evdev.hwdb` should look like this:
```
# PenPower RemoteGo LCD RMGL01
evdev:input:b0003v256Cp5101*
 EVDEV_ABS_00=::156
 EVDEV_ABS_01=::221
```
Right? Or should I go with "200" for EVDEV_ABS_01, and ... what for EVDEV_ABS_00?

**Comment by whot** [comment]
00 is the x axis which is 210mm (not sure why the measurements on the package are height/width instead of width/height). So that hwdb entry you posted looks correct.
