### ISSUE TITLE
Huion Kamvas Pro 24 (GT-240, QHD)

### ISSUE THREAD

**Issue by AesaraB** [linuxwacom/libwacom#624]
- **Device name**: Huion Kamvas Pro 24 (QHD)
- **Device model identifier**: GT-240
- **libwacom version**: 2.8.0

- [x] I understand that libwacom does affect whether the device works (see [Troubleshooting](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work))

- [ ] **udevadm info output**: 
- [x] sysinfo issue in [wacom-hid-descriptors](https://github.com/linuxwacom/wacom-hid-descriptors/issues/351):

# Duplicate USB ID

This tablet has the same USB ID (256c:006e) as the [Huion Kamvas Pro 13](https://github.com/linuxwacom/wacom-hid-descriptors/issues/160), Gaomon S56K, and [Gaomon M10K](https://github.com/linuxwacom/wacom-hid-descriptors/tree/master/Gaomon%20M10K%202018).

|Device|Huion Kamvas Pro 13|Huion Kamvas Pro 24|Gaomon S56K|
|:-|:-|:-|
|Buttons|5|20|0|
|Sliders|0|2|0|

Matching strings with DeviceMatch String isn't possible, compare [/data/kamvas-pro-13.tablet](https://github.com/linuxwacom/libwacom/blob/master/data/kamvas-pro-13.tablet) with the evtest listings for Kamvas Pro 24
```
/dev/input/event13:	Tablet Monitor Pen
/dev/input/event14:	Tablet Monitor Pad
/dev/input/event16:	Tablet Monitor Touch Strip
/dev/input/event17:	Tablet Monitor Dial
```

I'll create the tablet file after #610 is fixed.

# libinput issues
Some inputs are not recognised on this device, see [this](https://gitlab.freedesktop.org/libinput/libinput/-/issues/989) issue.

**Comment by Eckoa** [comment]
I created a tablet file and svg (im not great with inkscape though), Im unsure as to how to set the buttons as being left vs right of the display with the EvdevCodes or if they should all be in just a large list. Currently Digimend and libinput are waiting on a patch for the buttons/touch strips to all work so This is only for the left side buttons. It includes the touch strips but the obviously wont work at the moment.


```

# Huion
# Kamvas Pro 24
# GT240
#
#
# Button Map:
# (A=1, B=2, C=3, ...)
#
#    *-----------------------*
#    |                       |
#  A |                       | K
#  B |                       | L
#  C |                       | M
#  D |                       | N
#  E |        TABLET         | O
#    |                       |
#    |                       |
#  F |                       | P
#  G |                       | Q
#  H |                       | R
#  I |                       | S
#  J |                       | T
#    |                       |
#    *-----------------------*
#
#
# Touch Strip Map:
# (a=strip min, A=strip max)
# Touch Strips are mirrored and do not map seperately
#
#    *-----------------------*
#    |                       |
#    |                       |
#    |                       |
#    |                       |
#    |                       |
#    |        TABLET         |
#  A |                       | A
#  a |                       | a
#    |                       |
#    |                       |
#    |                       |
#    |                       |
#    |                       |
#    |                       |
#    *-----------------------*

[Device]
Name=Huion Kamvas Pro 24
ModelName=GT240
DeviceMatch=usb:256c:006e:Tablet Monitor Pad;usb:256c:006e:Tablet Monitor Pen;usb:256c:006e:Tablet Monitor Touch Strip
Class=Cintiq
Width=21
Height=12
IntegratedIn=Display
Layout=huion-kamvas-pro-24.svg
Styli=@generic-no-eraser

[Features]
Stylus=true
Reversible=false
Touch=false
TouchSwitch=false
Ring=false
NumStrips=1

[Buttons]
Left=A;B;C;D;E;F;G;H;I;J
EvdevCodes=BTN_0;BTN_1;BTN_2;BTN_3;BTN_4;BTN_5;BTN_6;BTN_7,BTN_8,BTN_9
```

![huion-kamvas-pro-24](https://github.com/linuxwacom/libwacom/assets/120538016/6f398b27-01a5-43bd-bb59-5d03473463ff)

**Comment by whot** [comment]
>  or if they should all be in just a large list.

IIRC the `EvdevCodes` is in the order `A;B;C;`, the location doesn't matter. So one large list.

**Comment by AesaraB** [comment]
It might be better to add further comments about the actual files in the [draft pr](#654)

**Comment by AesaraB** [comment]
@Eckoa this might be more a thing for future reference, as I've created the new SVG file, but SVGs are actually at their core fairly simple XML files. Go ahead and open a couple of the layout files in a text editor.
