### ISSUE TITLE
Tablet is included in database or not?

### ISSUE THREAD

**Issue by mpaglia0** [linuxwacom/libwacom#642]
- **Huion**: 
- **H610 Pro**: 
- **2.8**:

- [x] I understand that libwacom does affect whether the device works (see [Troubleshooting](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work))

# Bug description
libwacom-list-local-devices output says my tables is NOT supported by libwacom

libwacom-list-devices shows Huion H610 Pro among the listed tablets

**Comment by whot** [comment]
what's the output of `libinput record` for this device?

**Comment by mpaglia0** [comment]
Ciao @whot !
`libinput record` output:

Available devices:
/dev/input/event4:      HUION PenTablet Pen
/dev/input/event5:      HUION PenTablet Pad
/dev/input/event6:      HUION PenTablet Mouse

`libwacom-list-local-devices` output:

/dev/input/event6 is a tablet but not supported by libwacom
devices:
- name: 'Huion H610 Pro'
  bus: 'usb'
  vid: '0x256c'
  pid: '0x006e'
  nodes: 
  - /dev/input/event4: 'HUION PenTablet Pen'
- name: 'Huion H610 Pro'
  bus: 'usb'
  vid: '0x256c'
  pid: '0x006e'
  nodes: 
  - /dev/input/event5: 'HUION PenTablet Pad'

Thank you!
Maurizio

**Comment by whot** [comment]
Thanks, looks like we're all good.

> /dev/input/event6 is a tablet but not supported by libwacom

That's expected - note how your tablet has three event nodes for pen, pad and a mouse. The latter is the one not supported by libwacom because it's not a tablet. The other ones are as you can see.
