### ISSUE TITLE
Profile included but not recognized

### ISSUE THREAD

**Issue by Jopp-gh** [linuxwacom/libwacom#655]
- **Device name**: XP-Pen Star03
- **Device model identifier**: STR03B
- **libwacom version**: no idea how to get this info (Linux Mint Cinnamon, 21.3)

- [x] I understand that libwacom does affect whether the device works (see [Troubleshooting](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work))

# Bug description
my tablet is included in `/usr/share/libwacom/xp-pen-star03.tablet`(please see profile at bottom page), but I cannot use my tablet in combination with https://github.com/tb2097/wacom-gui. Results of Wacom-gui:
```
~/Downloads/wacom-gui-master/wacom-gui$ python3 wacom-gui.py
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,100'
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 90,90,90,90'
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,100'
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 90,90,90,90'
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,100'
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 90,90,90,90'
unknown desktop environment
/dev/input/event25 is a tablet but not supported by libwacom
/dev/input/event25 is a tablet but not supported by libwacom
```

Wacom-gui is a pretty nice gui to configure multiple tablet profiles, linux Mint alone doesn't allow the configuration of multiple tablet profiles. 

>I don't know if libwacom is the culprit of this bug or Wacom-gui.

Here's the content of `/usr/share/libwacom/xp-pen-star03.tablet`:
```
# XP-Pen
# Star 03
#

[Device]
Name=XP-Pen Star 03
ModelName=
DeviceMatch=usb:5543:0081:UC-Logic TABLET 1060N Pen;usb:5543:0081:UC-Logic TABLET 1060N Pad;usb:28bd:0907:UGTABLET 10 inch PenTablet
Class=Bamboo
Width=10
Height=6
IntegratedIn=
Layout=xp-pen-star03.svg
Styli=0xffffd;

[Features]
Stylus=true
Reversible=true
Touch=false
Buttons=8

[Buttons]
Left=A;B;C;D;E;F;G;H
EvdevCodes=0x100;0x101;0x102;0x103;0x104;0x105;0x106;0x107
```

**Comment by whot** [comment]
What does `libwacom list-local-devices` say about the device? And what does `libinput record` say about the device nodes (you probably have multiple of those). Please **attach** the output of `libinput record`, do not copy/paste.

**Comment by whot** [comment]
> I prefer to not mess with these system packages,

either tool may be in a `libwacom-utils`, `libwacom-tools`, `libinput-utils`, etc. package, whatever it's named. Alternatively both of these will run from the respective git build dirs without needing to install them.

**Comment by whot** [comment]
Closing, cannot proceed without information
