### ISSUE TITLE
middle mouse button scroll

### ISSUE THREAD

**Issue by fMagVen** [linuxwacom/libwacom#671]
![Settings_001](https://github.com/linuxwacom/libwacom/assets/78576546/5bd46b22-445c-4df3-a219-78edf71dd06b)

feature request

**Comment by whot** [comment]
Please see the bot comment above, this is a software feature and would have to be implemented in whatever handles tablet events. There's an open [libinput PR](https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/981) and I've worked on this for mutter but it's ... not trivial. So we're aware this feature is wanted but esp. in Wayland it cannot easily be implemented (focus issues, will require an update of the wayland tablet protocol).

**Comment by fMagVen** [comment]
Thank you for your effort
