### ISSUE TITLE
Add support for Thinkpad Yoga 370

### ISSUE THREAD

**Issue by galengold** [linuxwacom/libwacom#7]
[linuxwacom/wacom-hid-descriptors#11](https://github.com/linuxwacom/wacom-hid-descriptors/issues/11)

Currently, with xsetwacom, I can remap the upper button on the stylus (towards the non-sensitive tip of the stylus) using the stylus' identifier.

I can provide more information if needed.

**Comment by jigpu** [comment]
Tablet definition will be available in the next libwacom release.
