### ISSUE TITLE
Add support to XP Pen Artist 22R Pro

### ISSUE THREAD

**Issue by katsuenya** [linuxwacom/libwacom#706]
Hello, please add support for XP Pen Artist 22R Pro. XP Pen drivers works perfectly fine under X11, but on Wayland the pointer is shown on wrong monitor. While using Wayland compositor in driver settings I see black screen and regardless which monitor I select the pointer is shown in wrong location.  

I made a reddit post on /r/xppen to inform people on my findings https://www.reddit.com/r/XPpen/comments/1d10i2k/if_you_using_linux_do_not_use_wayland_desktop/

- **Device name**: XP Pen Artist 22R Pro https://www.xp-pen.com/product/artist-22r-pro.html
- **Device model identifier**: Artist 22R Pro
- **libwacom version**: 2.11.0

- [ ] I understand that libwacom does affect whether the device works (see [Troubleshooting](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work))

- [ ] **udevadm info output**: 
- [ ] sysinfo issue in [wacom-hid-descriptors](https://github.com/linuxwacom/wacom-hid-descriptors):

**Comment by whot** [comment]
> but on Wayland the pointer is shown on wrong monitor

fwiw, there's no such thing as "Wayland" in this bug, it's a bug in the compositor you're using (much like HTTP isn't at fault when Firefox renders to the wrong window). Best to file a bug with them.
