### ISSUE TITLE
Surface Pro pen/stylus NTRIG does not rotate

### ISSUE THREAD

**Issue by prog-amateur** [linuxwacom/libwacom#76]
Hello, on the Jakeday kernel git (kernel to adapt Linux to Microsoft Surface Pro), an .deb version of libwacom has been proposed to support the NTRIG stylus. 

[In my case](https://github.com/jakeday/linux-surface/issues/415#issuecomment-473718514) (`Debian 10`, `kernel 4.19`, `libwacom-0.32 deb file`), I didn't install the Jakeday kernel, only the libwacom.deb. And unfortunately, if the stylus is properly taken into account, when the screen rotates in portrait or reverse landscape mode, the stylus retains its original orientation (e. g. in portrait, if I move the stylus to the right, the cursor goes up). 

We think that a script or an adjustment of the.deb is necessary to take into account the stylus rotation, but we don't have the knowledge to implement it. 

Do you think you can help us solve this problem, please? 

In any case, thank you for your help.

**Comment by whot** [comment]
For the screen rotation - that is handled in the desktop environment (GNOME/KDE/whatever applies). AFAICT only GNOME currently uses libwacom. And the auto-screen rotation will only happen for built-in tablets  - that's where libwacom comes in. So the first question is: what's the output of `libwacom-list-local-devices`? Does it list the tablet at all and with what features?

**Comment by prog-amateur** [comment]
Thank you for your feedback. The output of `libwacom-list-local-devices` gives me nothing (no device listed). 
If I use `xinput list`, it gives me : 
```
~$ xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Type Cover Consumer Control	id=9	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Type Cover Touchpad   	id=10	[slave  pointer  (2)]
⎜   ↳ NTRG0001:01 1B96:1B05                   	id=14	[slave  pointer  (2)]
⎜   ↳ NTRG0001:01 1B96:1B05 Pen Pen (0)       	id=16	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ Surface Pro 3/4 Buttons                 	id=7	[slave  keyboard (3)]
    ↳ Microsoft Surface Type Cover Keyboard   	id=8	[slave  keyboard (3)]
    ↳ Microsoft LifeCam Front: Micros         	id=11	[slave  keyboard (3)]
    ↳ Microsoft LifeCam Rear: Microso         	id=12	[slave  keyboard (3)]
    ↳ NTRG0001:01 1B96:1B05 Pen               	id=13	[slave  keyboard (3)]
    ↳ Microsoft Surface Type Cover Consumer Control	id=15	[slave  keyboard (3)]

```



Please find also some data about my setup : 

```
uname -a : 
4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux
Gnome version : 3.30.2
```
It is like if all devices are taken into account (and it is true) by something, but not libwacom.

**Comment by prog-amateur** [comment]
Sorry, any news please ?

**Comment by whot** [comment]
Copy and modify `data/n-trig-pen.tablet` for your usbid (1b96, 1b05) and drop it into libwacom's data dir (/usr/sharelibwacom). That should do the job, `libwacom-list-devices` should then list the device and it'll be available to GNOME too (after a restart). Ideally that takes care of screen rotation then too.

If the size is the same as the existing ntrig entry, you can just add your usb ID to the DeviceMatch line (there are examples for this in the `data/` directory).

**Comment by prog-amateur** [comment]
I have changed `n-trig-pen.tablet` in both repositories `usr/share/libwacom/` & `usr/share/libwacom/` as below : 
```

[Device]
Name=N-Trig Pen
DeviceMatch=usb:1b96:1b05
Class=ISDV4
Width=10
Height=6
IntegratedIn=Display;System

[Features]
Stylus=true
Touch=true
Buttons=2
```

then, I have restarted and... no change. Maybe I have mishandled something (for instance, to change `usb:1b96:1b05` by `NTRG0001:01 1B96:1B05` ? 
Thank you !

**Comment by whot** [comment]
run  `libinput record` or `evemu-record` and select the pen device. In the first few lines there's the ID line which lists the usb ids for this tablet. That one has to match the `DeviceMatch` line, maybe it is something other than what you have here?

After any changes, check with `libwacom-list-local-devices`. Until the device shows up there it won't get picked up by anything else either. If it *does* show up but the screen rotation doesn't work the issue is in GNOME somewhere.

**Comment by whot** [comment]
Any updates?

**Comment by whot** [comment]
Can you submit a PR for the change to the libwacom data file please? And a PR for xf86-input-wacom for the NTrig addition to the xorg.conf file too, thanks.

**Comment by prog-amateur** [comment]
Hi, despite my nickname, I'm not a programmer, so I don't know anything about PR. If someone can help, please, that would be great, thank you!

**Comment by whot** [comment]
PR is a "pull request" and the main method on github to get your changes integrated into a repository. 
So you basically git clone the repository, make your changes locally, test them, and then push them to your own fork of the repo. Once done, you can file a pull request (or merge request, same thing) and we can review and merge the patches quickly.

github has plenty of documentation about this process. It's how most projects take contributions these days, so learning that process is time will be well spent.

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks
