### ISSUE TITLE
Backporting tablet file to libwacom fails when DB update

### ISSUE THREAD

**Issue by Int-Circuit** [linuxwacom/libwacom#772]
- **Device name**: 
- **Device model identifier**: 
- **libwacom version**: 2.11

- [x] I understand that libwacom does affect whether the device works (see [Troubleshooting](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work))

# Bug description

Running Fedora 40 with GNOME 46

After connecting my tablet and backporting the .tablet and layout file in /etc/libwacom and /etc/libwacom/layouts, I run 
`
libwacom-update-db /etc/libwacom/
`
to update the database.
When running it I get this error
Failed to process match usb|256c|0067 in /etc/libwacom/huion-inspiroy-2-m---h951p.tablet
Traceback (most recent call last):
  File "/usr/bin/libwacom-update-db", line 217, in <module>
    db = TabletDatabase(ns.path)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/libwacom-update-db", line 118, in __init__
    self.tablets = sorted(self._load(path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/libwacom-update-db", line 136, in _load
    raise e
  File "/usr/bin/libwacom-update-db", line 133, in _load
    bus, vid, pid, *_ = match.split(":")
    ^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected at least 3, got 1)

**Comment by whot** [comment]
The format of the `DeviceMatch` changed recently - previously it was `usb:1234:abcd` and now the `:` is instead a `|`, i.e. `usb|1234|abcd`. Correcting between the two will fix the issue you're seeing.

**Comment by whot** [comment]
F40 has libwacom 2.11 with the old format, i.e. `:`. You can see in the backtrace that it tries to split by `:`, not the pipe symbol. So your local `.tablet` file needs to use `:` instead of the upstream `|`.
