### ISSUE TITLE
No configuration of Inspiroy 2M possible in GNOME 47

### ISSUE THREAD

**Issue by Int-Circuit** [linuxwacom/libwacom#775]
- **Device name**: 
- **Device model identifier**: 
- **libwacom version**: 2.13

- [x] I understand that libwacom does affect whether the device works (see [Troubleshooting](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work))

# Bug description
After upgrading to fedora 41 Beta and libwacom 2.13 (which partly fixed  #772, the tablet is now detected) , the GNOME 47 control center reports the tablet and the stylus as a generic one, with no option to configure the buttons and sensibility of it.

![image](https://github.com/user-attachments/assets/62e11ff7-7472-4cf2-a715-6d9853e74835)

![image](https://github.com/user-attachments/assets/6c3d3fc2-b17b-458c-b3d0-f39e64591da6)

![image](https://github.com/user-attachments/assets/d92dbc1f-18cd-496a-982d-2c26d2555bc4)

![image](https://github.com/user-attachments/assets/05310e28-272c-4542-ac2c-1116b1a9f1a4)

This is a major deal breaker as the tablet picks up the stylus position from around two centimetres from the tablet's surface.

**Comment by whot** [comment]
>  the GNOME 47 control center reports the tablet and the stylus as a generic one, with no option to configure the buttons and sensibility of it.

That's a misunderstanding. The tablet is an *external* one, not a generic one, so it should allow for button mappings. And the sensibility and stylus button mappings are configurable right there, isn't it?

What's missing are the external pad buttons but they don't show up in the `list-local-devices` output either so right now my guess is that the `Pad` device doesn't have `ID_INPUT_TABLET_PAD` assigned to it.

Using `libinput record` can you see the `Pad` device and if so what is its output? **attach** the output here please, don't copy it.


> This is a major deal breaker as the tablet picks up the stylus position from around two centimetres from the tablet's surface.

Proximity? That is expected, yes. What exactly is the wrong behaviour here, can you expand please?

**Comment by whot** [comment]
right, so this tablet needs a kernel driver or, better, a BPF to make it work properly. This is the `M` version of my `S` I think, so you should be able to use the [existing one from udev-hid-bpf](https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/-/merge_requests/85).

By changing [this line](https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/-/blob/main/src/bpf/stable/0010-Huion__Inspiroy-2-S.bpf.c?ref_type=heads#L15) to add your device. Basically it should look like this:
```c
#define PID_INSPIROY_2_S 0x0066
#define PID_INSPIROY_2_M 0x0067

HID_BPF_CONFIG(
	HID_DEVICE(BUS_USB, HID_GROUP_GENERIC, VID_HUION, PID_INSPIROY_2_S),
	HID_DEVICE(BUS_USB, HID_GROUP_GENERIC, VID_HUION, PID_INSPIROY_2_M),
);
```

Then you should be able to install it, replug the device and hooray. There's a [tutorial](https://libevdev.pages.freedesktop.org/udev-hid-bpf/tutorial.html) and other docs to explain what happens.

This may not give you all buttons, and you will also need [huion-switcher](https://github.com/whot/huion-switcher) to switch to raw mode but the pieces should all be there. See #718 for an outline though.

**Comment by whot** [comment]
> Did it make some progress

not yet, huion-switcher is still required, there's no BPF hook to do what it does just yet. `ETIME` and tbh I'm kinda punting this to @bentiss anyway ;)

> Quick question do you know which package in fedora installs libudev?

Best approach: `sudo dnf "pkgconfig(libudev)"` - that way dnf looks up what package provides `libudev.pc` so you don't have to care. Works with pretty much any meson error about a missing package.

**Comment by whot** [comment]
closing this, we need the device to be supported by the kernel (via BPF), nothing libwacom can do here

/close
