### ISSUE TITLE
README instructions are wrong?

### ISSUE THREAD

**Issue by redstrate** [linuxwacom/libwacom#785]
It says to quickly backport a device descriptor, put them into `/etc/libwacom`. But the directory seems to be `/usr/share/libwacom` nowadays? I would make a quick PR to fix it, but I don't know which version that was changed in :D

**Comment by redstrate** [comment]
I figured it out, apparently `/etc/libwacom` is correct - I just didn't have that directory on my system. `/usr/share/libwacom` for the system's definitions, and I made this clarification in the wiki. I also created a PR to move these instructions from the README.

**Comment by whot** [comment]
fwiw, this is a pattern quite generic across multiple projects: distribution files go into `/usr/share/abcd`, system-local files go into `/etc/abcd` and user-specific files go into `$XDG_CONFIG_HOME/abcd` (the last of which we don't support but arguably should)
