### ISSUE TITLE
Generate the device Class programmatically

### ISSUE THREAD

**Issue by whot** [linuxwacom/libwacom#790]
Nothing uses `libwacom_get_class()` (except for identifying remotes, see #779) but we still have to add it each `.tablet` file. Since we don't have any known callers we can just generate the value:
- `IntegratedIn=Display` -> Cintiq
- `IntegratedIn=Display;System` -> ISDV4
- `IntegratedIn=` -> Bamboo

**Comment by redstrate** [comment]
I started work on this, but it dawned on me that there's a _lot_ of classes other than Cintiq, ISDV4 and Bamboo. I guess it makes sense to only generate it programmatically if it doesn't have an explicit one defined?

**Comment by whot** [comment]
The only class that currently matters is the `WCLASS_REMOTE`, all the others are never used for anything (afaik). Many are expired and now pointless anyway (Intuos*, Bamboo, Graphire). So the only ones that "matter" are Cintiq, Intuos5 and ISDV4 - all of which we can auto-assign.

And the remote of course :)

**Comment by whot** [comment]
Fixed in #814
