### ISSUE TITLE
Add support for multiple devices from wacom-hid-descriptors

### ISSUE THREAD

**Issue by jigpu** [linuxwacom/libwacom#8]
At least the following tablet PCs need support added to libwacom:

- [x] Dell XPS 13 9365
    - 0018:056a:4831
    - Touch: 29.38 cm x 16.52 cm (11752x6608)
    - Pen: 29.376 cm x 16.524 cm (29376x16524)
- [x] HP EliteBook x360 1030 G2
    - 0018:056a:481a
    - Touch: 29.38 cm x 16.52 cm (11752x6608)
    - Pen: 29.376 cm x 16.524 cm (29376x16524)
- [x] Dell Latitude 5285
    - 0018:056a:484c
    - Touch: 25.92 cm x 17.28 cm (10368x6912)
    - Pen: 25.920 cm x 17.280 cm (25920x17280)
- [x] Lenovo ThinkPad Yoga 720
    - i2c?:056a:50f8
    - Touch: 344x194mm
    - Pen: 344x194mm
- [x] Lenovo ThinkPad Yoga 260 (Version C)
    - usb:056a:5090
    - Touch: 27.65 cm x 15.55 cm (11060x6220)
    - Pen: 27.648 cm x 15.552 cm (27648x15552)

**Comment by jigpu** [comment]
Dell XPS 13 9365, HP EliteBook x360 1030 G2, and Dell Latitude 5385 are already supported. Patch for later tablets sent to mailinglist.

**Comment by jigpu** [comment]
Tablet definition will be available in the next libwacom release.

**Comment by plasmasolutions** [comment]
Hi jigpu, 

I just forked the repo to send you a pull request for fixing the Yoga 720 15" but as I tracked down the insertion of the Lenovo Yoga to this point I first have to ask here: Where did you verify the device id from the Yoga 720 15" pen (no HiDPI, 2017 version)? Mine was not shown in the gnome-control-center and when I checked, it didn't have the 056a:50f8 but the 056a:50fb ...

Changing the identifier and id was bringing it up in the control center and configuring was a breeze...

Best, Thomas

**Comment by jigpu** [comment]
Hey Thomas,

It isn't uncommon for slightly different SKUs of the same device to have different IDs. The 056a:50f8 ID was used by [this tablet PC](https://github.com/linuxwacom/wacom-hid-descriptors/tree/b1e111d5b2d54947738d11c312392abfcedd7fc0/Lenovo%20Yoga%20720/sysinfo.eeC7GzOmG2), reported in [this bug report](https://github.com/linuxwacom/wacom-hid-descriptors/issues/4). The "machine.txt" file identifies itself as a "Lenovo YOGA 720-15IKB" and the "xinput.txt" (indirectly) identifies the sensor as being 056a:50f8.

Would you mind running our [sysinfo.sh script](https://github.com/linuxwacom/wacom-hid-descriptors/blob/master/scripts/sysinfo.sh) and attaching the generated tarball to a [new bug on the wacom-hid-descriptors repository](https://github.com/linuxwacom/wacom-hid-descriptors/issues/)? This will give us some additional information specific to your unit that may be valuable in the future.

We'd welcome a pull request of libwacom to support your 50fb sensor as well :)
