### ISSUE TITLE
Is it possible to know which screen is the tablet's?

### ISSUE THREAD

**Issue by redstrate** [linuxwacom/libwacom#819]
I noticed this line in the README that greatly interests me:

> libwacom is currently used by GUI toolkits (GNOME, KDE, others?) to map built-in tablets to the correct screen 

But I don't see any obvious API in libwacom to do this. Surely there is a way to figure out which screen belongs to the tablet right? If it's not in libwacom, maybe somewhere else?

**Comment by whot** [comment]
Hmm, that line is a bit of an overstatement, more correct would be "used by GUI toolkits ... to check if tablets are internal or external so they can be mapped to the correct screen".

The logic in mutter is (iirc): Display + System - map to internal monitor, e.g. eDP, Display map to first non-internal monitor that matches vendor ID, size, or aspect ratio, in that sequence.

A long time ago there was #48 though I never finished that and eventually dropped it - and the world hasn't ended so I guess those heuristics are good enough :)

**Comment by redstrate** [comment]
Thanks, that's exactly what I wanted to know. I'll ask the KWin people at some point if it makes sense for us to do the same. We already do it for touchscreens IIRC, so it doesn't seem out of place to do it for internal tablet screens too.

**Comment by whot** [comment]
I'm pretty sure the mutter code for this is the same function so you can definitely share it (don't quote me on that and I don't have the sources in front of me right now).
