### ISSUE TITLE
On dell 7390-2-1 i cannot see the tablet in the control panel.

### ISSUE THREAD

**Issue by lukyluket** [linuxwacom/libwacom#82]

**Comment by lukyluket** [comment]
I have understood I should add a .tablet file but I cannot find the USB id of the device, 

I get 
 xsetwacom --list
Wacom HID 4841 Pen stylus       	id: 11	type: STYLUS    
Wacom HID 4841 Finger touch     	id: 12	type: TOUCH     
Wacom HID 4841 Pen eraser       	id: 21	type: ERASER    

So I actually do not see any tablet. and furthermore 
lsusb gives

Bus 004 Device 002: ID 0bda:8153 Realtek Semiconductor Corp. 
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 0bda:0328 Realtek Semiconductor Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 1bcf:2b96 Sunplus Innovation Technology Inc. 
Bus 001 Device 004: ID 0a5c:5834 Broadcom Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
and 
lspci gives

00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 08)
00:13.0 Non-VGA unclassified device: Intel Corporation Sunrise Point-LP Integrated Sensor Hub (rev 21)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
00:15.1 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 (rev 21)
00:15.2 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #2 (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:16.3 Serial controller: Intel Corporation Device 9d3d (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 (rev f1)
00:1c.7 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #8 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Intel(R) 100 Series Chipset Family LPC Controller/eSPI Controller - 9D4E (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
01:00.0 PCI bridge: Intel Corporation JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016] (rev 02)
02:00.0 PCI bridge: Intel Corporation JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016] (rev 02)
02:01.0 PCI bridge: Intel Corporation JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016] (rev 02)
02:02.0 PCI bridge: Intel Corporation JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016] (rev 02)
02:04.0 PCI bridge: Intel Corporation JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016] (rev 02)
37:00.0 USB controller: Intel Corporation JHL6540 Thunderbolt 3 USB Controller (C step) [Alpine Ridge 4C 2016] (rev 02)
6c:00.0 Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
6d:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981


So no wacom anywhere, how can I proceed?
Cheers

**Comment by jigpu** [comment]
Please run [our sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) to gather the necessary information. You can drag and drop the generated tarball onto the comment box here to attach it for review.

**Comment by lukyluket** [comment]
Here it goes, thanks
[sysinfo.lTIdlhsqpl.tar.gz](https://github.com/linuxwacom/libwacom/files/3069316/sysinfo.lTIdlhsqpl.tar.gz)

**Comment by jigpu** [comment]
Thanks! Looks like a tablet definition was added for your particular device as a part of pull request #80. There hasn't been a libwacom release with the data yet, however. A quick workaround would be to save [this file](https://github.com/linuxwacom/libwacom/blob/master/data/isdv4-4841.tablet) as `/usr/share/libwacom/isdv4-4841.tablet` and then reboot.

Let me know if that fixes the detection issue.

Note that I believe the version of GNOME that comes with your distribution is affected by a bug that prevents the stylus configuration options from appearing. See [here](https://bugzilla.gnome.org/show_bug.cgi?id=793499) for more info. IIRC, a fix should be present in GNOME 3.32 which is supposed to be installed with Ubuntu 19.04.

**Comment by whot** [comment]
fwiw,I just released libwacom 0.33 with that fix, so you could pester your distro maintainers to include that one in your distribution version.

**Comment by lukyluket** [comment]
Thanks using the file you provided  both pen and tablet can be configured in 18.04
Everythings works right now
thanks 
Luca
