### ISSUE TITLE
Microsoft Surface IPTS device integration

### ISSUE THREAD

**Issue by qzed** [linuxwacom/libwacom#89]
Hi all, I just wanted to get a discussion started about including the surface specific patches (e.g. from https://github.com/geoffholden/libwacom and https://github.com/qzed/libwacom-surface), originally created by @geoffholden.

The devices in question are Intel Precise Touch and Stylus (IPTS) devices connected via the Intel Management Engine (MEI) bus, so to integrate the devices this bus type would need to be supported ([00_mei-bus.patch](https://github.com/qzed/libwacom-surface/blob/176f72de68c6311624d9c743a2e784efba643ce5/00_mei-bus.patch)).

On the device-data side, all devices are currently listed in the same file ([01_surface-tablet-data.patch](https://github.com/qzed/libwacom-surface/blob/176f72de68c6311624d9c743a2e784efba643ce5/01_surface-tablet-data.patch)). Should we change that to be per model? Also I think it would be good if someone could look over the file and check if it's up to convention (e.g. I've added the `Styli` key and I'm not sure if that's a good idea; stylus is single-button + eraser, the eraser is also a button, but that's a separate bluetooth device).

It might also be a good idea to re-check the device IDs and map them to the specific models. Here's what I know so far:

| ID | Model | Source | Note |
|-------------|------------------------|----------------------------------------------------------------------------------------------------------------------|-------|
| `1B96:005e` | Surface Book 1 | [comment](https://github.com/jakeday/linux-surface/issues/513#issuecomment-498009154) | |
| `045E:0020` | Surface Book 2 (15") | [comment](https://github.com/jakeday/linux-surface/issues/513#issuecomment-497983039) |
| `045E:0021` | Surface Book 2 (13.5") | my own device | | |
| `1B96:006A` | Surface Pro 4 | [comment](https://github.com/jakeday/linux-surface/issues/513#issuecomment-498028173) | |
| `1B96:001F` | Surface Pro 5 (2017) |  | prev. source seems to be wrong |
| `045E:001F` | Surface Pro 6 | [comment](https://github.com/jakeday/linux-surface/issues/513#issuecomment-498036450) | |
| `04F3:261A` | Surface Go | [issue](https://github.com/linuxwacom/libwacom/issues/75#issue-421842624) | hid-over-i2c, not IPTS? |

Edit: I think we've got all device IDs for the IPTS devices. I've also stumbled on [this](https://github.com/jakeday/linux-surface/blob/2b206b56e125c9fda4661dbcc91095e9bf993d28/root/etc/udev/rules.d/99-touchscreens.rules), which collaborates the list, so I think we're solid.

CC: @geoffholden (original author), @jakeday (surface-linux maintainer)

**Comment by jigpu** [comment]
The MEI bus patch looks good to me. The data file, however, should be split up as you suspect. Most of the Wacom devices are one file per sensor ID, but that's mostly because we don't know if the sensors are being reused across models. If a set of IDs can be definitively tied to a single model (e.g. the Surface Book 2), then that set could conceivably exist in a model-specific file. The `Name` property should also probably be model- or device-specific rather than simply "Microsoft Surface Device".

I don't see the `Styli` key in either of the patches; am I missing something? That particular key would be used if the kernel reports a numeric tool ID (beyond the kernel-defined stylus/eraser/etc. types). I'm not sure if the Surface pens (or the Surface pen's kernel driver) do. If a tool ID is reported, it should also be added to the `libwacom.stylus` file as well.

**Comment by qzed** [comment]
Thanks for the details!

> I don't see the Styli key in either of the patches; am I missing something? 

Ah, no sorry. I've played around with it, but I didn't end up including it in the patch (thought I did) as it didn't seem to change anything (makes sense now). The Surface pens might report something like a model ID (e.g. first generation vs. second generation vs. ...). I'll try to figure that out.

**Comment by qzed** [comment]
Sorry for the delay! I haven't been able to figure out if IPTS is capable of reporting some sort of tool ID. It doesn't look like the kernel is reporting one, so I think we should assume that there is no tool ID for now.

I've also opened a new issue on the surface-linux repo to try and figure out which device belongs to which ID. I'll prepare a PR for the MEI patch and the 2 devices we know so far.

**Comment by ShapeShifter499** [comment]
Does this have anything to do with the Surface Go?   https://github.com/linuxwacom/xf86-input-wacom/issues/52

**Comment by qzed** [comment]
@ShapeShifter499 As far as I know, the Surface Go doesn't use IPTS but rather HID-over-i2c, right? I'm a bit confused about that as the match in the old tablet data file specifies `mei:04F3:261A` (and that seems to work), I think it should be `i2c:04F3:261A` (@jigpu any thoughts?).

If it uses i2c, the only thing required for the Surface Go would be the tablet data file. If it hasn't been added already, we could add it to the other PR or create a new one.

**Comment by ShapeShifter499** [comment]
@qzed I wonder because @jigpu posted some patches that worked for me over at the issue page linuxwacom/xf86-input-wacom#52.     They also work on a different tablet, Nuvision Solo 10 Draw that also allows for the Surface Pen to work.

**Comment by qzed** [comment]
@ShapeShifter499 This shouldn't have to do anything with your earlier issue, it's only about detection of the tablet here (e.g. for Gnome settings, screen-rotation, ...). What does `libwacom-list-local-devices` give you, specifically what's the bus for `04F3:261A`?

**Comment by ShapeShifter499** [comment]
@qzed with the above patch in place. libwacom-list-local-devices doesn't give me any output on my Surface Go

**Comment by qzed** [comment]
Interesting, are you using Gnome? If so, does the tablet show up under the device settings and does screen rotation work?

**Comment by ShapeShifter499** [comment]
I'm on gnome and rotation has always worked in xorg and wayland mode.  This is with Arch Linux

**Comment by ShapeShifter499** [comment]
@qzed My pen shows up in settings under "power" showing a 1% battery life.  However "Settings > Devices > Wacom Tablet"    No stylus or tablet is detected

**Comment by qzed** [comment]
@ShapeShifter499 The battery-info should be handled via the bluetooth connection.

The rotation part is interesting. If I remember correctly, without the libwacom patches the pen did not rotate with the screen for me, I always assumed that Gnome required libwacom to handle this.

The device missing under settings is due to the missing device data file. If you want to play around a bit, you could try and add one under `/usr/local/share/libwacom`, e.g. just take [this](https://github.com/linuxwacom/libwacom/blob/034b512d73a19a42dfd829b98e44a3b7ba7e755c/data/surface-pro5.tablet) as a template and change `DeviceMatch` to `DeviceMatch=i2c:04F3:261A`.

**Comment by ShapeShifter499** [comment]
@qzed ```without the libwacom patches the pen did not rotate with the screen for me```

Do you mean when you rotated the screen something odd like the pen not being lined up with the cursor on the screen? I never experience that with the Surface Go I have.

Adding the tablet file didn't help much. Gnome settings still doesn't show any stylus but it does show a tablet. Trying to calibrate, I get a lot of "mis-click" warnings and it times out before I can complete. On time out the entire Gnome settings window has messed up font. The normally black font goes wite making it hard to see what I'm clicking, settings requires a relaunch to get it looking normal.

**Comment by ShapeShifter499** [comment]
I'm not able to get my pen to connect to my Surface Go over bluetooth.  I get it into paring mode but it never shows up in Gnome bluetooth settings.

**Comment by qzed** [comment]
@ShapeShifter499 

> Do you mean when you rotated the screen something odd like the pen not being lined up with the cursor on the screen?

Yes, basically I would move the pen horizontally, and the cursor on screen would move vertically when I had the tablet rotated 90 degrees.

> Gnome settings still doesn't show any stylus but it does show a tablet.

Yeah, unfortunately that's as far as we get I think. For the stylus to be recognized I think there would have to be some additional support via a HID driver or something (and then probably support for that in Gnome). I haven't had any issues with calibration though, except that it times out rather quickly.

> I'm not able to get my pen to connect to my Surface Go over bluetooth. I get it into paring mode but it never shows up in Gnome bluetooth settings.

Haven't had any issues there, either. Have you tried taking the battery out of the pen for a few seconds?

**Comment by ShapeShifter499** [comment]
@qzed Something must be bugged with Gnome.  In XFCE with Arch Linux on a laptop my pen shows up as "Surface Pen" in Blueman

**Comment by qzed** [comment]
Might be.

**Comment by qzed** [comment]
Okay, I think the list for the device IDs should be complete.

**Comment by idnovic** [comment]
> @ShapeShifter499 As far as I know, the Surface Go doesn't use IPTS but rather HID-over-i2c, right? I'm a bit confused about that as the match in the old tablet data file specifies `mei:04F3:261A` (and that seems to work), I think it should be `i2c:04F3:261A` (@jigpu any thoughts?).
> 
> If it uses i2c, the only thing required for the Surface Go would be the tablet data file. If it hasn't been added already, we could add it to the other PR or create a new one.

I tested it on my surface go, it is i2c:04F3:261A - see here https://github.com/linux-surface/libwacom/pull/1

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks
