### ISSUE TITLE
Lenovo Yoga 720 13

### ISSUE THREAD

**Issue by xqwzts** [linuxwacom/libwacom#9]
Hi, Gnome's settings/wacom tablet doesn't detect a stylus or tablet, I've attached the sysinfo output here, hope that helps.

[sysinfo.GumyasC18w.tar.gz](https://github.com/linuxwacom/libwacom/files/1575286/sysinfo.GumyasC18w.tar.gz)

Please let me know if any other info is required, would be happy to help and test [if someone is willing to guide me through it].

**Comment by xqwzts** [comment]
FWIW wacom-hid-descriptors lists a Lenovo Thinkpad Yoga 720, I'm not sure it matters but the 720/920 are not Thinkpads, so "Lenovo Yoga 720" might be a better descriptor.

Also it looks like that is based off the Yoga 720 15", again unsure if there is a difference, but I've attached the 13"'s info here.

**Comment by jigpu** [comment]
Thanks for the sysinfo output :) Could you also open an issue at the [wacom-hid-descriptors repository ](https://github.com/linuxwacom/wacom-hid-descriptors) with a link back to this issue? It does indeed look like the 13" uses a different sensor than the 15", so I'll want to save this sysinfo output there for future reference.

I'll update this issue once a patch is ready for testing and provide you with a guide on how to do it.

**Comment by xqwzts** [comment]
@jigpu : Thanks for the quick response! I've opened an issue and attached the sysInfo there as well.

**Comment by jigpu** [comment]
I've added this and a few other missing tablets. The easiest way to test this would be to use `gunzip` to decompress the following file and copy it into your libwacom data directory (likely `/usr/share/libwacom` -- you should see a bunch of other tablet definition files there). Once the file is in place, it should be detected by the GNOME Control Center after a reboot.

[isdv4-50f1.tablet.gz](https://github.com/linuxwacom/libwacom/files/1576895/isdv4-50f1.tablet.gz)

**Comment by xqwzts** [comment]
@jigpu Thanks so much, this worked perfectly.

**Comment by jigpu** [comment]
Reopening until the fix is actually applied

**Comment by jigpu** [comment]
Tablet definition will be available in the next libwacom release.
