### ISSUE TITLE
Duplicate match in /usr/share/libwacom

### ISSUE THREAD

**Issue by dvvvxx** [linuxwacom/libwacom#90]
As said [here](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#duplicate-matches) I've found a duplicate match for the Wacom Intuos Pro 2 L and Wacom Intuos Pro 2 L WL (basically the same version but with the grey borders). Here's the output:

```
$ libwacom-list-local-devices

(libwacom-list-local-devices:7497): libwacom-CRITICAL **: 12:55:48.076: Duplicate match of 'bluetooth:056a:0361'
on device 'Wacom Intuos Pro 2 L WL'.
Failed to initialize device database

$ grep -r "bluetooth:056a:0361"  /usr/share/libwacom

./intuos-pro-2-l.tablet:DeviceMatch=usb:056a:0358;bluetooth:056a:0361;
./intuos-pro-2-l-wl.tablet:DeviceMatch=bluetooth:056a:0361
mdes@mddesk:/usr/share/libwacom$

```

**Comment by jigpu** [comment]
The contents of the `intuos-pro-2-l-wl.tablet` file were merged into `intuos-pro-2-l.tablet` and then deleted in commit aee1636706c07a7efbcc4b9e779cd973ed0a1c48. If you recently installed libwacom from source, then that could explain why the duplicate match exists. In such a case you'll need to delete the deprecated `intuos-pro-2-l-wl.tablet` file from your system.

**Comment by dvvvxx** [comment]
Awesome thank you! Yup I've installed libwacom from source, sorry for the distraction!

**Comment by jigpu** [comment]
No problem. I've updated the wiki to have people run `libwacom-list-local-devices` after installing from source to make sure this problem doesn't occur, and linked to the Troubleshooting article with instructions for how to fix it.

**Comment by 6lancmange** [comment]
The instructions aren't clear enough. I don't know how to check whether the file is provided by libwacom or distribution. I came here to file an issue with exactly the same file, and found this thread. I had two models with and without "WL":
```
/usr/share/libwacom/intuos-pro-2-m.tablet:DeviceMatch=usb:056a:0357;bluetooth:056a:0360;
/usr/share/libwacom/intuos-pro-2-l-wl.tablet:DeviceMatch=bluetooth:056a:0361
/usr/share/libwacom/intuos-pro-2-l.tablet:DeviceMatch=usb:056a:0358;bluetooth:056a:0361;
/usr/share/libwacom/intuos-pro-2-m-wl.tablet:DeviceMatch=bluetooth:056a:0360
```

**Comment by whot** [comment]
>  I don't know how to check whether the file is provided by libwacom or distribution.

if you install with the same prefix (and thus into the same location) as your distribution package, there is no difference between the two. a package removal should remove all packaged files though, and make uninstall will remove all source-installed files. You'd need to do both to make sure they're all gone.

Or alternatively: remove the system package before installing from git, make uinstall before re-installing the system package.

**Comment by swapsCAPS** [comment]
Had the same issue for Wacom Intuos Bluetooth S.
Had to run `rm /usr/share/libwacom/intuos-pro-2-l-wl.tablet`

In the "before building" instructions it lists `libwacom` as a dependency. Is this correct or will this cause these kind of duplicates?

FWIW:
```
Model: CTL-4100WL
Ubuntu 18.04
GNOME Shell 3.28.4
```

**Comment by whot** [comment]
Are you referring to [this page](https://github.com/linuxwacom/libwacom/wiki)? If so, it uses `build-dep` which installs the various packages *required* by libwacom, not libwacom itself.

`intuos-pro-2-l-wl.tablet` was removed, so if you still have that one around it's from an older libwacom installation and should be removed.

**Comment by swapsCAPS** [comment]
Whoops my bad! Was unfamiliar with the `build-dep` feature and read it as a dependency too :sweat_smile:

**Comment by DeastinY** [comment]
Interestingly this caused my gnome-control-center not to start. Just wanted to put that out here if someone runs into the same issues :man_shrugging:.
It's fixed now, so no detailed Ideal what failed besides this:
`g_once_init_leave: assertion 'result != 0' failed`
