### ISSUE TITLE
Group pens into specific sets

### ISSUE THREAD

**Issue by whot** [linuxwacom/libwacom#99]
See #57 for the need/reasoning.

Basic idea: instead of each tablet listing every possible serial number, group those into various sets, e.g. "Pro Pen" or "AES Pen". Then add those sets to the tablets.

Advantages:
- easier to identify if we forgot to add a specific pen to a tablet
- easier to update the serials when they change (e.g. some tablets support multiple generations of the same pen)

The first big TODO item here is to identify the current serial numbers and identify which ones could be grouped by sets.

**Comment by skomra** [comment]
That seems like a good idea. Here are the uniq lines:

```
Styli=0x006;0x802;0x804;0x806;0x80a;0x80c;0x902;0x90a;0x100802;0x100804;0x10080a;0x10080c;0x100902;0x10090a;0x120802;0x140802;0x14080a;0x160802;0x16080a;
Styli=0x007;0x094;0x096;0x812;0x822;0x82a;0x832;0x842;0x852;0x85a;0x912;0x91a;
Styli=0x017;0x097;0x801;0x813;0x81b;0x823;0x82b;0x885;0x913;0x91b;
Styli=0x094;0x096;0x812;0x822;0x82a;0x832;0xd12;0xd1a;
Styli=0x100802;0x100804;0x10080a;0x10080c;0x100902;0x10090a;0x120802;0x140802;0x14080a;0x160802;0x16080a;
Styli=0x180802;0x18080a;
Styli=0x801;0x813;0x81b;0x823;0x82b;0x885;0x913;0x91b;
Styli=0x802;0x804;0x40802;0x80c;0x80a;0x4080a;0x90a;0x20802;0x902;
Styli=0x802;0x804;0x806;0x80a;0x80c;0x902;0x90a;0x100802;0x100804;0x10080a;0x10080c;0x100902;0x10090a;0x120802;0x140802;0x14080a;0x160802;0x16080a;
Styli=0x802;0x804;0x80a;0x80c;0x902;0x90a;0x100802;0x100804;0x10080a;0x10080c;0x100902;0x10090a;0x120802;0x140802;0x14080a;0x160802;0x16080a;
Styli=0x842;0x84a;0x80842;0x100802;0x100804;0x10080a;0x10080c;0x100842;0x10084a;0x100902;0x10090a;0x120802;0x140802;0x14080a;0x160802;0x16080a;
Styli=0x862;
Styli=0x8e2;
Styli=0xffffd
Styli=0xffffd;
Styli=0xffffe;0xfffff;
# Styli=0xfffff;
```
I was surprised to see how few lines there were. I started decomposing them by number:

```
# Styli
Styli=0x006;low-numbers;mid-numbers;high-numbers;0x806;
Styli=0x007;0x094;0x096;old-numbers;0x842;0x852;0x85a;0x912;0x91a; # note this is the first (ignored) x842
Styli=0x017;0x097;0x801;0x813;0x81b;0x823;0x82b;0x885;0x913;0x91b;
Styli=0x094;0x096;old-numbers;0xd12;0xd1a;
Styli=mid-numbers;high-numbers
Styli=0x180802;0x18080a;
Styli=0x801;0x813;0x81b;0x823;0x82b;0x885;0x913;0x91b;
Styli=low-numbers;0x4080a;0x20802;0x40802;
Styli=low-numbers;mid-numbers;high-numbers;0x806;
Styli=low-numbers;mid-numbers;high-numbers
Styli=mobile-studio-gen;mid-numbers;high-numbers
Styli=0x862;
Styli=0x8e2;
Styli=0xffffd
Styli=0xffffd;
Styli=0xffffe;0xfffff;
# Styli=0xfffff;

high-numbers;-0x100902;0x10090a;0x120802;0x140802;0x14080a;0x160802;0x16080a;
mid-numbers;-0x100802;0x100804;0x10080a;0x10080c;
low-numbers;-0x802;0x804;0x80a;0x80c;0x902;0x90a;
old-numbers;-0x812;0x822;0x82a;0x832;
mobile-studio-gen;0x842;0x84a;0x80842;0x100842;0x10084a
```

but you probably want to do this based on function 

maybe
low-numbers-> classic-tools
high-numbers -> airbrush, inking, classic, pro pen 1
mid-numbers -> grip, art
old-numbers-> Intuos / Intuos2
mobile-studio -> mobile-studio

**Comment by whot** [comment]
doh, didn't realise we'd overlap here, otherwise I wouldn't have stayed up late last night.  My approach was to print a CSV with all styli numbers and then look at it from a distance to see the grouping. 

gist is here: https://gist.github.com/whot/00a7b09431e426c2a5a20065419ec2d6 because I can't upload CSV files. Import that into a spreadsheet or view it there.

The groups I found:
- 0x017, 0x097
- 0x801, 0x813, 0x81b, 0x823, 0x82b, 0x885, 0x913, 0x91b
- 0x006
- 0x007, 0x842, 0x852, 0x85a, 0x912, 0x91a
- 0x094, 0x096, 0x812, 0x822, 0x82a, 0x832,
- 0x8e2
- 0xd12, 0xd1a
- 0x842, 0x84a, 0x80842, 0x100842, 0x10084a
- 0x862
- 0x806
- 0x180802, 0x18080a
- 0x802, 0x804, 0x80a, 0x80c, 0x902, 0x90a, 
- 0x100802, 0x100804, 0x10080a, 0x10080c, 0x100902, 0x10090a, 0x120802, 0x140802, 0x14080a, 0x160802, 0x16080a
- 0xffffe, 0xfffff
- 0xffffd

All of these have at least 2 users, the 802 group is the largest with 22 users. Most tablets would have 2 groups, e.g. intuos3 have the 0x12 and the 0x801 group.
